import type {CSSProperties, ReactNode} from 'react';
import {BadgeDollarSign, Ban, Check, FileCheck2, FileX2, Gavel, Landmark, RotateCcw, Scale, Settings2, ShieldAlert, SlidersHorizontal, Users} from 'lucide-react';
import {interpolate, useCurrentFrame} from 'remotion';
import {CLAMP} from '../../../../../shared/remotion-runtime';

const M={bg:'#dbe3e5',steel:'#52636a',ink:'#172126',orange:'#ef6b3c',green:'#24876d',yellow:'#f1be38',white:'#f8fbfb'};
const Pop=({children,delay,style}:{children:ReactNode;delay:number;style?:CSSProperties})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+16],[0,1],CLAMP);return <div style={{opacity:p,scale:p,translate:`0 ${20*(1-p)}px`,...style}}>{children}</div>};
const Machine=({code,title,children}:{code:string;title:string;children:ReactNode})=><div style={{position:'absolute',inset:0,overflow:'hidden',backgroundColor:M.bg,color:M.ink,fontFamily: 'var(--inkloom-animation-body)'}}><div style={{position:'absolute',left:0,right:0,top:0,height:32,backgroundColor:M.ink}}/><div style={{position:'absolute',left:72,top:58,fontSize:18,fontWeight:850,color:M.orange}}>APPRAISAL CALIBRATION / {code}</div><h1 style={{fontFamily: 'var(--inkloom-animation-title)', position:'absolute',left:72,top:94,margin:0,fontSize:56,fontWeight:900}}>{title}</h1><div style={{position:'absolute',left:72,right:72,top:174,height:5,backgroundColor:M.steel}}/>{children}<div style={{position:'absolute',left:72,bottom:28,fontSize:17,fontWeight:750,color:M.steel}}>鉴定意见 · 校准流程</div></div>;

export const InitiationScene=()=> <Machine code="01" title="谁启动鉴定：申请为原则，职权为例外">
  <div data-layout="dual-input-appraisal-chamber" data-visual-anchor="flow-path" data-text-treatments="label-block,thin-underline,stamp" data-visual-grammar="default,exception,authorization,consequence" data-focal-rule="parties-apply-unless-the-fact-belongs-to-ex-officio-investigation" data-focal-channels="icon,connector,enclosure,contrast" style={{position:'absolute',left:72,right:72,top:214,bottom:72}}>
    <Pop delay={4} style={{position:'absolute',left:0,top:40,width:570,height:500,backgroundColor:M.white,border:`5px solid ${M.green}`,padding:'40px 44px'}}><Users size={74} color={M.green}/><div style={{marginTop:28,fontSize:40,fontWeight:900}}>原则：当事人申请</div><div style={{marginTop:22,fontSize:26,lineHeight:1.5}}>对待鉴定事实负证明责任的人<br/><b style={{color:M.green}}>在法院指定期间内申请</b></div><div style={{position:'absolute',left:44,right:44,bottom:42,padding:'18px 22px',backgroundColor:M.green,color:M.white,fontSize:25,fontWeight:850}}>不申请致事实不明 → 承担举证不能后果</div></Pop>
    <div style={{position:'absolute',left:610,top:280,width:210,height:10,backgroundColor:M.steel}}/><div style={{position:'absolute',left:810,top:267,borderTop:'18px solid transparent',borderBottom:'18px solid transparent',borderLeft:`28px solid ${M.steel}`}}/>
    <Pop delay={28} style={{position:'absolute',left:850,top:140,width:360,height:300,backgroundColor:M.ink,color:M.white,display:'grid',placeItems:'center',textAlign:'center'}}><Settings2 size={82} color={M.yellow}/><div style={{fontSize:38,fontWeight:900,marginTop:-60}}>鉴定程序</div></Pop>
    <div style={{position:'absolute',left:1210,top:280,width:86,height:10,backgroundColor:M.orange}}/><div style={{position:'absolute',left:1182,top:267,borderTop:'18px solid transparent',borderBottom:'18px solid transparent',borderRight:`28px solid ${M.orange}`}}/>
    <Pop delay={52} style={{position:'absolute',right:0,top:0,width:480,height:580,backgroundColor:M.orange,color:M.white,padding:'40px 44px'}}><Landmark size={72}/><div style={{marginTop:26,fontSize:37,fontWeight:900}}>例外：法院依职权决定</div><div style={{marginTop:28,fontSize:26,lineHeight:1.65}}>国家 / 社会 / 第三人利益<br/>身份关系<br/>程序性事实</div><div style={{position:'absolute',left:44,right:44,bottom:46,fontSize:23}}>仅限法院应当依职权调查的事实</div></Pop>
  </div>
</Machine>;

export const PreparationScene=()=> <Machine code="02" title="鉴定人怎么定，材料能不能用">
  <div data-layout="appraiser-selection-and-material-lock" data-visual-anchor="document-fork" data-text-treatments="soft-highlight,label-block,external-negation" data-visual-grammar="selection,escalation,verification,exclusion" data-focal-rule="selection-path-depends-on-initiation-and-materials-require-cross-examination" data-focal-channels="icon,connector,enclosure,annotation" style={{position:'absolute',left:72,right:72,top:214,bottom:72}}>
    <Pop delay={4} style={{position:'absolute',left:0,top:0,width:760,height:310,backgroundColor:M.white,borderTop:`10px solid ${M.green}`,padding:'30px 36px'}}><Users size={58} color={M.green}/><div style={{marginTop:18,fontSize:31,fontWeight:900}}>当事人申请鉴定</div><div style={{marginTop:20,display:'flex',alignItems:'center',gap:20,fontSize:27}}><span style={{padding:'14px 18px',backgroundColor:M.green,color:M.white}}>先协商</span><span>→</span><span style={{padding:'14px 18px',border:`3px solid ${M.green}`}}>协商不成，法院指定</span></div></Pop>
    <Pop delay={26} style={{position:'absolute',left:0,bottom:0,width:760,height:310,backgroundColor:M.white,borderTop:`10px solid ${M.orange}`,padding:'30px 36px'}}><Landmark size={58} color={M.orange}/><div style={{marginTop:18,fontSize:31,fontWeight:900}}>法院依职权决定鉴定</div><div style={{marginTop:20,display:'flex',alignItems:'center',gap:20,fontSize:27}}><span style={{padding:'14px 18px',backgroundColor:M.orange,color:M.white}}>询问意见</span><span>→</span><span style={{padding:'14px 18px',border:`3px solid ${M.orange}`}}>法院指定</span></div></Pop>
    <Pop delay={52} style={{position:'absolute',right:0,top:60,width:800,height:560,backgroundColor:M.ink,color:M.white,padding:'42px 48px'}}><SlidersHorizontal size={72} color={M.yellow}/><div style={{marginTop:24,fontSize:39,fontWeight:900}}>材料校验门</div><div style={{marginTop:40,display:'flex',alignItems:'center',gap:28}}><FileCheck2 size={84} color={M.green}/><div><div style={{fontSize:31,fontWeight:850}}>经过质证</div><div style={{marginTop:8,fontSize:24,color:'#cbd7da'}}>可以作为鉴定根据</div></div></div><div style={{marginTop:42,display:'flex',alignItems:'center',gap:28}}><FileX2 size={84} color={M.orange}/><div><div style={{fontSize:31,fontWeight:850}}>未经质证</div><div style={{marginTop:8,fontSize:27,color:M.orange,fontWeight:900}}>不得作为鉴定根据</div></div></div></Pop>
  </div>
</Machine>;

export const AppearanceConsequencesScene=()=> <Machine code="03" title="鉴定人出庭：费用有例外，拒不到庭有三重后果">
  <div data-layout="appearance-cost-and-sanction-mechanism" data-visual-anchor="boundary" data-text-treatments="label-block,stamp,external-negation" data-visual-grammar="cost-allocation,exception,sanction" data-focal-rule="defective-opinions-shift-costs-and-refusal-destroys-evidentiary-effect" data-focal-channels="icon,contrast,enclosure,spatial" style={{position:'absolute',left:72,right:72,top:214,bottom:72}}>
    <Pop delay={4} style={{position:'absolute',left:0,top:0,width:720,height:650,backgroundColor:M.white,border:`4px solid ${M.green}`,padding:'36px 42px'}}><BadgeDollarSign size={72} color={M.green}/><div style={{marginTop:24,fontSize:38,fontWeight:900}}>出庭费用</div><div style={{marginTop:36,padding:'22px 26px',backgroundColor:M.green,color:M.white,fontSize:29,fontWeight:850}}>原则：败诉方负担</div><div style={{marginTop:28,padding:'22px 26px',border:`4px solid ${M.orange}`,fontSize:27,lineHeight:1.45}}>鉴定意见不明确 / 有瑕疵<br/><b style={{color:M.orange}}>鉴定人自行负担</b></div></Pop>
    <div style={{position:'absolute',left:770,top:0,bottom:0,width:8,backgroundColor:M.steel}}/>
    <Pop delay={34} style={{position:'absolute',right:0,top:0,width:880,height:650,backgroundColor:M.ink,color:M.white,padding:'36px 42px'}}><Ban size={72} color={M.orange}/><div style={{marginTop:24,fontSize:38,fontWeight:900}}>经法院通知，拒不出庭</div>{[[FileX2,'鉴定意见不得作为定案根据'],[RotateCcw,'退还鉴定费用'],[ShieldAlert,'建议有关部门处罚']].map(([Icon,text],i)=><div key={text as string} style={{marginTop:26,height:112,display:'flex',alignItems:'center',gap:24,padding:'18px 22px',backgroundColor:i===0?M.orange:'#2d3b40',fontSize:27,fontWeight:850}}><Icon size={52} color={i===0?M.white:M.yellow}/>{text as string}</div>)}</Pop>
  </div>
</Machine>;
