import type {ReactNode} from 'react';
import {ArrowDown, BadgeCheck, Building2, CircleX, FileKey2, Flag, Landmark, Network, Scale, ShieldQuestion, Signpost, Stamp, Users, Workflow} from 'lucide-react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';
import {CLAMP,TimelineSequence} from '../../../../shared/remotion-runtime';
import {SCENES} from './storyboard';

const C={paper:'#EDF0EA',ink:'#182126',navy:'#244B5A',red:'#C84C3C',green:'#39735B',gold:'#D8A936',sky:'#A9CAD0',white:'#FCFDF9',gray:'#CDD4CF'} as const;
const PLAYER_CONTROL_SAFE_BOTTOM = 160;
const enter=(f:number,s:number,x=0,y=22)=>({opacity:interpolate(f,[s,s+18],[0,1],CLAMP),translate:`${interpolate(f,[s,s+18],[x,0],CLAMP)}px ${interpolate(f,[s,s+18],[y,0],CLAMP)}px`});
const Shell=({code,title,kicker,children}:{code:string;title:string;kicker:string;children:ReactNode})=><AbsoluteFill data-player-control-safe-bottom={PLAYER_CONTROL_SAFE_BOTTOM} style={{background:C.paper,color:C.ink,overflow:'hidden'}}>
 <div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(#244B5A0D 1px,transparent 1px),linear-gradient(90deg,#244B5A0D 1px,transparent 1px)',backgroundSize:'40px 40px'}}/>
 <header style={{position:'absolute',left:68,right:68,top:36,height:100,display:'grid',gridTemplateColumns:'120px 1fr auto',alignItems:'center',borderBottom:`4px solid ${C.navy}`}}><b style={{fontSize:23,color:C.red}}>专题二 / {code}</b><h1 style={{fontSize:46,margin:0,fontWeight:950}}>{title}</h1><span style={{fontSize:22,fontWeight:850,color:C.green}}>{kicker}</span></header>
 <main style={{position:'absolute',left:68,right:68,top:158,bottom: PLAYER_CONTROL_SAFE_BOTTOM}}>{children}</main>
</AbsoluteFill>;

export const SubjectIdentityRadarScene=()=>{const f=useCurrentFrame();return <Shell code="01" title="行政主体不是机构名称，而是法律关系中的角色" kicker="控权对象雷达">
 <div data-layout="identity-radar-with-role-switch" data-visual-anchor="comparison-axis" data-visual-grammar="agency-role-switch,authorized-organization-to-public-liability" data-text-treatments="label-block,soft-highlight,stamp" data-focal-rule="subject-identity" data-focal-channels="contrast,icon,connector" style={{position:'absolute',inset:0}}>
  <div data-final-knowledge="agency-role-switch" style={{position:'absolute',left:20,top:36,width:720,height:570,background:C.white,border:`5px solid ${C.navy}`,padding:36,...enter(f,8)}}><Building2 size={66} color={C.navy}/><h2 style={{fontSize:38}}>同一个行政机关，两种身份</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18,fontSize:24,lineHeight:1.45}}><div style={{padding:24,background:C.navy,color:C.white}}><b style={{fontSize:30}}>行政职权享有者</b><br/>处于不平等法律关系<br/>对外行政活动<br/>承担公法责任</div><div style={{padding:24,border:`4px solid ${C.gold}`}}><b style={{fontSize:30}}>民事主体</b><br/>购买办公用品<br/>租借办公用房<br/><span style={{color:C.red}}>此时不是控权对象</span></div></div></div>
  <div data-final-knowledge="authorized-other-subjects" style={{position:'absolute',right:20,top:36,width:930,height:570,background:C.navy,color:C.white,padding:36,...enter(f,30)}}><ShieldQuestion size={66} color={C.gold}/><h2 style={{fontSize:38}}>不是行政机关，也可能是行政主体</h2><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:15,marginTop:22}}>{['地铁公司','风景名胜区','高校'].map(x=><div key={x} style={{padding:28,background:C.white,color:C.ink,fontSize:28,fontWeight:900,textAlign:'center'}}>{x}</div>)}</div><div style={{marginTop:26,padding:22,border:`4px solid ${C.gold}`,fontSize:25,lineHeight:1.5}}><b style={{color:C.gold}}>判定式：</b>在某法律关系中处于不平等地位 + 对外行政活动 + 承担公法责任 = 行政主体</div></div>
 </div></Shell>};

export const PublicPersonShellScene=()=>{const f=useCurrentFrame();return <Shell code="02" title="公法人：对内吸收人格，对外独立负责" kicker="行政主体概念的第二功能">
 <div data-layout="public-personality-absorption-shell" data-visual-anchor="flow-target" data-visual-grammar="internal-personalities-absorbed,public-person-acts-and-bears-liability" data-text-treatments="label-block,thin-underline,soft-highlight" data-focal-rule="public-person" data-focal-channels="enclosure,connector,icon" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:10,top:120,width:420,display:'grid',gap:24}}>{[['公务员',Users],['内设机构',Network]].map(([t,I],i)=>{const Icon=I as typeof Users;return <div key={t as string} style={{padding:28,background:C.white,border:`4px solid ${C.navy}`,fontSize:30,fontWeight:900,...enter(f,8+i*16)}}><Icon size={50} color={C.red} style={{verticalAlign:'middle',marginRight:18}}/>{t as string}</div>})}</div>
  <div data-final-knowledge="personality-absorption" style={{position:'absolute',left:510,top:30,width:720,height:590,borderRadius:360,background:C.navy,color:C.white,display:'grid',placeContent:'center',textAlign:'center',boxShadow:`0 0 0 22px ${C.sky}`,...enter(f,34)}}><Landmark size={84} style={{margin:'0 auto 16px'}}/><b style={{fontSize:48}}>公法意义上的法人</b><div style={{fontSize:27,color:C.gold,marginTop:12}}>吸收内部人格</div></div>
  <div style={{position:'absolute',right:10,top:96,width:420,display:'grid',gap:26}}><div data-final-knowledge="independent-activity" style={{padding:30,background:C.green,color:C.white,fontSize:27,...enter(f,58)}}><Workflow size={50}/><b style={{display:'block',fontSize:32,margin:'12px 0'}}>对外活动</b>以自己名义独立开展行政活动</div><div data-final-knowledge="independent-liability" style={{padding:30,background:C.red,color:C.white,fontSize:27,...enter(f,76)}}><Scale size={50}/><b style={{display:'block',fontSize:32,margin:'12px 0'}}>对外责任</b>独立承担行政责任</div></div>
 </div></Shell>};

export const TwelveAgencyTreeScene=()=>{const f=useCurrentFrame();const general=['国务院','省政府','市政府','县政府','乡政府'];const special=['国务院部门','省级部门','市级部门','县级部门'];const dispatched=['行政公署','区公所','街道办'];/* data-final-knowledge="agency-branch-0" data-final-knowledge="agency-branch-1" data-final-knowledge="agency-branch-2" */return <Shell code="03" title="12类行政机关：5 + 4 + 3 的正规军谱系" kicker="权的第一来源">
 <div data-layout="five-four-three-agency-tree" data-visual-anchor="flow-path" data-visual-grammar="constitutional-authorization-to-three-branches,five-four-three-counting" data-text-treatments="label-block,stamp,thin-underline" data-focal-rule="twelve-agencies" data-focal-channels="spatial,connector,icon" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:650,top:0,width:480,padding:24,background:C.ink,color:C.white,textAlign:'center',fontSize:32,fontWeight:950}}>宪法、各级组织法笼统授权</div>
  {[['5级一般权限政府',general,C.navy],['4级专门机关',special,C.green],['3类派出机关',dispatched,C.red]].map(([title,items,color],i)=><section key={title as string} data-final-knowledge={`agency-branch-${i}`} style={{position:'absolute',left:15+i*585,top:130,width:550,bottom:18,background:C.white,borderTop:`14px solid ${color}`,padding:28,...enter(f,24+i*18)}}><h2 style={{fontSize:34,margin:'0 0 20px',color:color as string}}>{title as string}</h2><div style={{display:'grid',gap:12}}>{(items as string[]).map((x,j)=><div key={x} style={{padding:'15px 20px',background:j%2?C.paper:C.gray,fontSize:25,fontWeight:820}}>{j+1}. {x}</div>)}</div>{i===1&&<div style={{marginTop:16,color:C.red,fontSize:22,fontWeight:800}}>乡政府不设对外业务部门，因此纵向只有4级</div>}</section>)}
 </div></Shell>};

export const DispatchedUnitSwitchScene=()=>{const f=useCurrentFrame();return <Shell code="04" title="派出机关与派出机构：名称相近，主体资格不同" kicker="机关恒有权，机构原则无权">
 <div data-layout="dispatched-office-platform-switch" data-visual-anchor="comparison-axis" data-visual-grammar="dispatching-government-to-office,dispatching-agency-to-unit-with-exception" data-text-treatments="label-block,external-negation,stamp" data-focal-rule="dispatched-units" data-focal-channels="contrast,connector,icon" style={{position:'absolute',inset:0,display:'grid',gridTemplateColumns:'1fr 1fr',gap:70}}>
  <section data-final-knowledge="dispatched-offices" style={{background:C.navy,color:C.white,padding:36,...enter(f,8,-20,0)}}><Signpost size={62} color={C.gold}/><h2 style={{fontSize:40}}>派出机关</h2>{['省政府 → 行政公署 ≈ 设区市政府','县政府 → 区公所','市辖区/不设区市政府 → 街道办 ≈ 乡镇政府'].map(x=><div key={x} style={{padding:22,marginTop:16,background:C.white,color:C.ink,fontSize:25,fontWeight:800}}>{x}</div>)}<div style={{marginTop:22,color:C.gold,fontSize:26,fontWeight:950}}>本身属于12类行政机关</div></section>
  <section data-final-knowledge="dispatched-institutions" style={{background:C.white,border:`5px solid ${C.red}`,padding:36,...enter(f,28,20,0)}}><Network size={62} color={C.red}/><h2 style={{fontSize:40}}>派出机构</h2><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{['派出所','市监所/分局','税务所'].map(x=><div key={x} style={{padding:22,background:C.paper,fontSize:26,fontWeight:900,textAlign:'center'}}>{x}</div>)}</div><div style={{marginTop:28,padding:22,background:C.red,color:C.white,fontSize:27,fontWeight:900}}>原则：不是行政主体</div><div style={{marginTop:16,padding:22,border:`4px solid ${C.green}`,fontSize:25}}><BadgeCheck size={36} color={C.green} style={{verticalAlign:'middle'}}/> 例外：取得有效授权时可成为行政主体<br/><b>派出所：警告、1000元以下罚款</b></div></section>
 </div></Shell>};

export const AuthorizationDelegationTracksScene=()=>{const f=useCurrentFrame();return <Shell code="05" title="行政授权与行政委托：资格沿哪条轨道移动" kicker="授权给资格，委托不给资格">
 <div data-layout="authorization-delegation-double-track" data-visual-anchor="document-fork" data-visual-grammar="law-rule-grant-to-new-subject,agency-delegation-retains-name-and-liability" data-text-treatments="label-block,soft-highlight,external-negation" data-focal-rule="authorization-vs-delegation" data-focal-channels="contrast,connector,motion" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:20,right:20,top:45,height:18,background:C.ink}}/>
  <section data-final-knowledge="authorization-track" style={{position:'absolute',left:20,top:90,width:830,bottom:20,background:C.green,color:C.white,padding:34,...enter(f,8)}}><FileKey2 size={60}/><h2 style={{fontSize:40}}>行政授权</h2><div style={{display:'grid',gridTemplateColumns:'1fr 70px 1fr',alignItems:'center',gap:14}}><div style={{padding:24,background:C.white,color:C.ink,fontSize:25}}><b>授予来源</b><br/>法律、法规或规章<br/><span style={{color:C.red}}>其他规范性文件无资格</span></div><div style={{fontSize:48}}>→</div><div style={{padding:24,border:`4px solid ${C.gold}`,fontSize:25}}><b>法律后果</b><br/>被授权者获得行政主体资格<br/>以自己名义承担责任</div></div><div style={{marginTop:24,fontSize:23}}>对象：原本无行政权能的机构、组织</div></section>
  <section data-final-knowledge="delegation-track" style={{position:'absolute',right:20,top:90,width:830,bottom:20,background:C.white,border:`5px solid ${C.navy}`,padding:34,...enter(f,28)}}><Stamp size={60} color={C.navy}/><h2 style={{fontSize:40}}>行政委托</h2><div style={{display:'grid',gridTemplateColumns:'1fr 70px 1fr',alignItems:'center',gap:14}}><div style={{padding:24,background:C.navy,color:C.white,fontSize:25}}><b>委托来源</b><br/>行政主体</div><div style={{fontSize:48}}>→</div><div style={{padding:24,border:`4px solid ${C.red}`,fontSize:25}}><b>法律后果</b><br/>受托者没有行政主体资格<br/>以委托机关名义活动</div></div><div style={{marginTop:20,fontSize:22,lineHeight:1.55}}>对象范围：机关、机构、组织、个体<br/>处罚委托给组织；许可委托给行政机关；行政强制措施不得委托</div></section>
 </div></Shell>};

export const PowerNameGatesScene=()=>{const f=useCurrentFrame();return <Shell code="06" title="两步操作法：先验权，再看名" kicker="名义不能替代授权检验">
 <div data-layout="power-first-name-second-gates" data-visual-anchor="flow-path" data-visual-grammar="power-gate-before-name-gate,invalid-normative-authorization-to-proper-defendant" data-text-treatments="stamp,external-negation,soft-highlight" data-focal-rule="power-name-test" data-focal-channels="motion,connector,contrast" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:40,top:90,width:440,padding:32,background:C.navy,color:C.white,...enter(f,6)}}><b style={{fontSize:38}}>第一步：权</b><p style={{fontSize:25,lineHeight:1.5}}>12类行政机关，或无权组织取得法律、法规、规章的有效授权</p></div><ArrowDown size={70} style={{position:'absolute',left:225,top:330}}/>
  <div data-final-knowledge="name-gate" style={{position:'absolute',left:40,top:420,width:440,padding:32,background:C.gold,...enter(f,28)}}><b style={{fontSize:38}}>第二步：名</b><p style={{fontSize:25}}>只有通过“权”的检验后，名义才有狭窄适用空间</p></div>
  <div data-final-knowledge="negative-name-signals" style={{position:'absolute',left:560,top:40,width:500,bottom:24,background:C.white,border:`5px solid ${C.red}`,padding:32,...enter(f,46)}}><CircleX size={58} color={C.red}/><h2 style={{fontSize:36}}>高危名称</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>{['指挥部','办公室','所','领导小组'].map(x=><span key={x} style={{padding:18,background:C.paper,fontSize:26,fontWeight:900}}>{x}</span>)}</div><p style={{fontSize:23,lineHeight:1.5}}>多为内设、临时或议事协调机构，一般无独立行政权，除非特别法特别授权。</p></div>
  <div data-final-knowledge="scenic-area-case" style={{position:'absolute',right:20,top:40,width:610,bottom:24,background:C.ink,color:C.white,padding:32,...enter(f,66)}}><Flag size={58} color={C.gold}/><h2 style={{fontSize:34}}>真题：风景区罚款200元</h2><p style={{fontSize:24,lineHeight:1.55}}>《旅游管理办法》只是其他规范性文件，不能有效授权风景区取得主体资格。</p><div style={{padding:20,background:C.red,fontSize:26,fontWeight:950}}>不能告风景区</div><div style={{padding:20,marginTop:14,border:`4px solid ${C.gold}`,fontSize:26,fontWeight:950}}>应告乙市文旅局</div></div>
 </div></Shell>};

export const CentralAgencyHangarsScene=()=>{const f=useCurrentFrame();/* data-final-knowledge="central-agency-type-0" data-final-knowledge="central-agency-type-1" data-final-knowledge="central-agency-type-2" */const units=[{name:'组成部门',cue:'组基本',role:'基本行政管理职能',examples:'教育部 · 公安部 · 卫健委 · 人民银行 · 审计署',rules:'有规章制定权',inside:'司、处两级',leaders:'3—5名（1正、2—4副）',color:C.navy},{name:'直属机构',cue:'直专',role:'专门业务',examples:'税务总局 · 市监总局 · 证监会',rules:'有规章制定权',inside:'司、处两级',leaders:'2—5名（1正、1—4副）',color:C.green},{name:'部管局',cue:'部管特',role:'特定业务',examples:'国家移民局 · 烟草专卖局',rules:'无规章制定权',inside:'可设司、处，也可只设处',leaders:'2—5名（1正、1—4副）',color:C.red}];return <Shell code="07" title="国务院机构三舱：职能、规章权与内设层级" kicker="组基本 · 直专 · 部管特">
 <div data-layout="three-central-agency-hangars" data-visual-anchor="comparison-axis" data-visual-grammar="institution-type-to-function,type-to-rulemaking-and-internal-levels" data-text-treatments="label-block,external-negation,stamp" data-focal-rule="central-agency-types" data-focal-channels="contrast,icon,annotation" style={{position:'absolute',inset:0,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:28}}>
  {units.map((u,i)=><section key={u.name} data-final-knowledge={`central-agency-type-${i}`} style={{position:'relative',background:C.white,border:`5px solid ${u.color}`,padding:28,...enter(f,10+i*20)}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Building2 size={54} color={u.color}/><span style={{padding:'8px 14px',background:u.color,color:C.white,fontSize:22,fontWeight:950}}>{u.cue}</span></div><h2 style={{fontSize:38,margin:'18px 0 6px'}}>{u.name}</h2><div style={{fontSize:26,color:u.color,fontWeight:900}}>{u.role}</div><p style={{fontSize:22,lineHeight:1.45,minHeight:62}}>{u.examples}</p><div style={{display:'grid',gap:12,marginTop:18}}><div style={{padding:16,background:u.rules.startsWith('无')?'#FFF1EF':C.paper,fontSize:23,fontWeight:850,color:u.rules.startsWith('无')?C.red:C.ink}}>{u.rules}</div><div style={{padding:16,background:C.gray,fontSize:23,fontWeight:850}}>{u.inside}</div><div style={{padding:16,border:`3px solid ${u.color}`,fontSize:23,fontWeight:850}}>领导职数：{u.leaders}</div></div>{i===2&&<div style={{position:'absolute',left:28,right:28,bottom:20,color:C.red,fontSize:22,fontWeight:850}}>部管不能制规章，且可以只设处。</div>}</section>)}
 </div></Shell>};

export const NonSubjectQuarantineScene=()=>{const f=useCurrentFrame();const items=[['内设机构','一般没有独立外部管理职能'],['临时机构','抽调人员完成临时任务，无独立行政管理权'],['议事协调机构','内部协调部门，一般不直接对外行使职权'],['指挥部 / 办公室 / 所 / 领导小组','一般不能作为行政诉讼被告，除非特别法特别授权']];/* data-final-knowledge="quarantine-0" data-final-knowledge="quarantine-1" data-final-knowledge="quarantine-2" data-final-knowledge="quarantine-3" */return <Shell code="08" title="非主体隔离区：名字像机关，不等于有行政权" kicker="猜题高危名称">
 <div data-layout="non-subject-quarantine-fence" data-visual-anchor="boundary" data-visual-grammar="organization-name-to-no-power-fence,exception-special-law-opens-fence" data-text-treatments="external-negation,label-block,stamp" data-focal-rule="non-subject-organizations" data-focal-channels="enclosure,contrast,icon" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:22,top:20,width:430,bottom:20,background:C.red,color:C.white,padding:30,...enter(f,8)}}><CircleX size={70}/><h2 style={{fontSize:40}}>通常没有主体资格</h2><p style={{fontSize:26,lineHeight:1.55}}>无独立行政管理权<br/>不能以自己名义对外作出行政行为<br/>不能单独成为行政诉讼被告</p></div>
  <div style={{position:'absolute',left:520,right:20,top:20,bottom:112,display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}>{items.map(([a,b],i)=><div key={a} data-final-knowledge={`quarantine-${i}`} style={{background:C.white,border:`4px solid ${C.ink}`,padding:22,...enter(f,24+i*14)}}><ShieldQuestion size={44} color={C.red}/><h2 style={{fontSize:30,margin:'8px 0 6px'}}>{a}</h2><p style={{fontSize:23,lineHeight:1.4,margin:0}}>{b}</p></div>)}</div>
  <div data-final-knowledge="quarantine-exception" style={{position:'absolute',left:650,right:20,bottom:20,height:72,display:'grid',placeItems:'center',background:C.gold,border:`4px solid ${C.ink}`,fontSize:25,fontWeight:900,...enter(f,78)}}>例外出口：特别法特别授权</div>
 </div></Shell>};

export const StaffingCommandNetworkScene=()=>{const f=useCurrentFrame();const central=[['组成部门','总理提请 → 全国人大/常委会决定'],['直属、办事、部管局','编制机关提方案 → 国务院决定'],['议事协调机构','编制机关提方案 → 国务院决定'],['司级内设','编制机关审核 → 国务院批准'],['处级内设','本行政机构决定 → 年度备案']];const local=[['地方编制总额','国务院'],['跨级调编','国务院编制管理部门'],['地方机构立撤并改','上一级政府；县级以上报同级人大常委会备案'],['职责冲突未果','本级政府'],['内设机构立撤并改','本级编制管理部门']];return <Shell code="09" title="机构编制指挥台：事项沿线路送达决定者" kicker="中央五路 + 地方五路">
 <div data-layout="central-local-staffing-routing-network" data-visual-anchor="flow-target" data-visual-grammar="central-matter-routes-to-decision-owner,local-matter-routes-to-decision-level" data-text-treatments="label-block,stamp,thin-underline" data-focal-rule="staffing-decisions" data-focal-channels="spatial,connector,annotation" style={{position:'absolute',inset:0,display:'grid',gridTemplateColumns:'1fr 1fr',gap:54}}>
  <section data-final-knowledge="central-command" style={{position:'relative',background:C.navy,color:C.white,padding:24,...enter(f,8)}}><h2 style={{fontSize:34,margin:'0 0 12px'}}>中央机构设置路线</h2><div style={{position:'absolute',left:250,top:86,bottom:70,width:7,background:C.gold}}/>{central.map(([a,b],i)=><div key={a} style={{position:'relative',display:'grid',gridTemplateColumns:'205px 1fr',gap:52,alignItems:'center',minHeight:82,fontSize:23}}><b style={{padding:10,background:'#FCFDF91C',color:C.gold}}>{a}</b><span style={{padding:10,border:`2px solid ${C.sky}`}}>{b}</span><i style={{position:'absolute',left:239,top:34,width:28,height:28,borderRadius:'50%',background:C.gold}}/></div>)}<div style={{position:'absolute',left:24,right:24,bottom:12,padding:8,border:`3px solid ${C.gold}`,fontSize:22}}>编制增减：编制机关审核→国务院批准；议事协调机构不单列编制。</div></section>
  <section data-final-knowledge="local-command" style={{position:'relative',background:C.white,border:`5px solid ${C.green}`,padding:24,...enter(f,34)}}><h2 style={{fontSize:34,margin:'0 0 12px'}}>地方事项分发路线</h2><div style={{position:'absolute',left:250,top:86,bottom:70,width:7,background:C.green}}/>{local.map(([a,b],i)=><div key={a} style={{position:'relative',display:'grid',gridTemplateColumns:'205px 1fr',gap:52,alignItems:'center',minHeight:82,fontSize:23}}><b style={{padding:10,background:C.paper,color:C.green}}>{a}</b><span style={{padding:10,border:`2px solid ${C.green}`}}>{b}</span><i style={{position:'absolute',left:239,top:34,width:28,height:28,borderRadius:'50%',background:C.green}}/></div>)}<div style={{position:'absolute',left:24,right:24,bottom:12,color:C.red,fontSize:22,fontWeight:850}}>事业编制办法：国务院编制机关审核后，由省级政府发布。</div></section>
 </div></Shell>};

export const AdministrativeSubjectCommand=()=> <AbsoluteFill>
 <TimelineSequence name="01-identity" start={SCENES['subject-identity-radar'].start} duration={SCENES['subject-identity-radar'].duration}><SubjectIdentityRadarScene/></TimelineSequence>
 <TimelineSequence name="02-person" start={SCENES['public-person-shell'].start} duration={SCENES['public-person-shell'].duration}><PublicPersonShellScene/></TimelineSequence>
 <TimelineSequence name="03-tree" start={SCENES['twelve-agency-tree'].start} duration={SCENES['twelve-agency-tree'].duration}><TwelveAgencyTreeScene/></TimelineSequence>
 <TimelineSequence name="04-dispatched" start={SCENES['dispatched-unit-switch'].start} duration={SCENES['dispatched-unit-switch'].duration}><DispatchedUnitSwitchScene/></TimelineSequence>
 <TimelineSequence name="05-tracks" start={SCENES['authorization-delegation-tracks'].start} duration={SCENES['authorization-delegation-tracks'].duration}><AuthorizationDelegationTracksScene/></TimelineSequence>
 <TimelineSequence name="06-gates" start={SCENES['power-name-gates'].start} duration={SCENES['power-name-gates'].duration}><PowerNameGatesScene/></TimelineSequence>
 <TimelineSequence name="07-types" start={SCENES['central-agency-hangars'].start} duration={SCENES['central-agency-hangars'].duration}><CentralAgencyHangarsScene/></TimelineSequence>
 <TimelineSequence name="08-quarantine" start={SCENES['non-subject-quarantine'].start} duration={SCENES['non-subject-quarantine'].duration}><NonSubjectQuarantineScene/></TimelineSequence>
 <TimelineSequence name="09-command" start={SCENES['staffing-command-network'].start} duration={SCENES['staffing-command-network'].duration}><StaffingCommandNetworkScene/></TimelineSequence>
</AbsoluteFill>;
