import type {DemoDefinition} from './demo-registry';
import {lazyDemo} from './lazy-demo';

import {DURATION_FRAMES as DURATION_01, FPS as FPS_01} from '../../animations/commercial-law/01/company-personality/remotion/storyboard';
import {DURATION_FRAMES as DURATION_02, FPS as FPS_02} from '../../animations/commercial-law/01/company-classification/remotion/storyboard';
import {DURATION_FRAMES as DURATION_03, FPS as FPS_03} from '../../animations/commercial-law/01/company-capacity/remotion/storyboard';
import {DURATION_FRAMES as DURATION_06, FPS as FPS_06} from '../../animations/commercial-law/02/shareholder-contribution/remotion/storyboard';
import {DURATION_FRAMES as DURATION_15, FPS as FPS_15} from '../../animations/commercial-law/07/llc-equity-transfer/remotion/storyboard';
import {DURATION_FRAMES as DURATION_19, FPS as FPS_19} from '../../animations/commercial-law/09/bankruptcy-grounds/remotion/storyboard';
import {DURATION_FRAMES as DURATION_28, FPS as FPS_28} from '../../animations/commercial-law/11/bankruptcy-revocation-right/remotion/storyboard';
import {DURATION_FRAMES as DURATION_29, FPS as FPS_29} from '../../animations/commercial-law/12/bankruptcy-reorganization/remotion/storyboard';
import {DURATION_FRAMES as DURATION_30, FPS as FPS_30} from '../../animations/commercial-law/12/bankruptcy-liquidation/remotion/storyboard';
import {DURATION_FRAMES as DURATION_31, FPS as FPS_31} from '../../animations/commercial-law/02/company-incorporation/remotion/storyboard';
import {DURATION_FRAMES as DURATION_32, FPS as FPS_32} from '../../animations/commercial-law/02/promoter/remotion/storyboard';

export const COMMERCIAL_LAW_STYLE_DEMOS = [
  {id: 'commercial-law-01-company-personality', slug: 'company-personality', title: '公司人格壳层', direction: 'personality-shell', component: lazyDemo(() => import('../../animations/commercial-law/01/company-personality/remotion/CompanyPersonality').then((m) => ({default: m.CompanyPersonality}))), href: '/inkloom/objective/commercial-law/01/company-personality/', durationInFrames: DURATION_01, fps: FPS_01},
  {id: 'commercial-law-01-company-classification', slug: 'company-classification', title: '双轨法人谱系', direction: 'branch-charter', component: lazyDemo(() => import('../../animations/commercial-law/01/company-classification/remotion/CompanyClassification').then((m) => ({default: m.CompanyClassification}))), href: '/inkloom/objective/commercial-law/01/company-classification/', durationInFrames: DURATION_02, fps: FPS_02},
  {id: 'commercial-law-01-company-capacity', slug: 'company-capacity', title: '担保决议柜', direction: 'resolution-cabinet', component: lazyDemo(() => import('../../animations/commercial-law/01/company-capacity/remotion/CompanyCapacity').then((m) => ({default: m.CompanyCapacity}))), href: '/inkloom/objective/commercial-law/01/company-capacity/', durationInFrames: DURATION_03, fps: FPS_03},
  {id: 'commercial-law-02-shareholder-contribution', slug: 'shareholder-contribution', title: '出资泊位港', direction: 'contribution-dockyard', component: lazyDemo(() => import('../../animations/commercial-law/02/shareholder-contribution/remotion/ShareholderContribution').then((m) => ({default: m.ShareholderContribution}))), href: '/inkloom/objective/commercial-law/02/shareholder-contribution/', durationInFrames: DURATION_06, fps: FPS_06},
  {id: 'commercial-law-07-llc-equity-transfer', slug: 'llc-equity-transfer', title: '股权流转市集', direction: 'transfer-mart', component: lazyDemo(() => import('../../animations/commercial-law/07/llc-equity-transfer/remotion/LlcEquityTransfer').then((m) => ({default: m.LlcEquityTransfer}))), href: '/inkloom/objective/commercial-law/07/llc-equity-transfer/', durationInFrames: DURATION_15, fps: FPS_15},
  {id: 'commercial-law-09-bankruptcy-grounds', slug: 'bankruptcy-grounds', title: '破产诊断台', direction: 'insolvency-diagnosis', component: lazyDemo(() => import('../../animations/commercial-law/09/bankruptcy-grounds/remotion/BankruptcyGrounds').then((m) => ({default: m.BankruptcyGrounds}))), href: '/inkloom/objective/commercial-law/09/bankruptcy-grounds/', durationInFrames: DURATION_19, fps: FPS_19},
  {id: 'commercial-law-11-bankruptcy-revocation-right', slug: 'bankruptcy-revocation-right', title: '临界期日历', direction: 'critical-period-calendar', component: lazyDemo(() => import('../../animations/commercial-law/11/bankruptcy-revocation-right/remotion/BankruptcyRevocationRight').then((m) => ({default: m.BankruptcyRevocationRight}))), href: '/inkloom/objective/commercial-law/11/bankruptcy-revocation-right/', durationInFrames: DURATION_28, fps: FPS_28},
  {id: 'commercial-law-12-bankruptcy-reorganization', slug: 'bankruptcy-reorganization', title: '重整轨道', direction: 'reorganization-rail', component: lazyDemo(() => import('../../animations/commercial-law/12/bankruptcy-reorganization/remotion/BankruptcyReorganization').then((m) => ({default: m.BankruptcyReorganization}))), href: '/inkloom/objective/commercial-law/12/bankruptcy-reorganization/', durationInFrames: DURATION_29, fps: FPS_29},
  {id: 'commercial-law-12-bankruptcy-liquidation', slug: 'bankruptcy-liquidation', title: '清偿瀑布', direction: 'distribution-cascade', component: lazyDemo(() => import('../../animations/commercial-law/12/bankruptcy-liquidation/remotion/BankruptcyLiquidation').then((m) => ({default: m.BankruptcyLiquidation}))), href: '/inkloom/objective/commercial-law/12/bankruptcy-liquidation/', durationInFrames: DURATION_30, fps: FPS_30},
  {id: 'commercial-law-02-company-incorporation', slug: 'company-incorporation', title: '设立装配线', direction: 'incorporation-assembly-line', component: lazyDemo(() => import('../../animations/commercial-law/02/company-incorporation/remotion/CompanyIncorporation').then((m) => ({default: m.CompanyIncorporation}))), href: '/inkloom/objective/commercial-law/02/company-incorporation/', durationInFrames: DURATION_31, fps: FPS_31},
  {id: 'commercial-law-02-promoter', slug: 'promoter', title: '发起人责任链', direction: 'promoter-liability-chain', component: lazyDemo(() => import('../../animations/commercial-law/02/promoter/remotion/Promoter').then((m) => ({default: m.Promoter}))), href: '/inkloom/objective/commercial-law/02/promoter/', durationInFrames: DURATION_32, fps: FPS_32},
] as const satisfies readonly DemoDefinition[];

export const COMMERCIAL_LAW_DEMO_ADDED_AT = Object.fromEntries(COMMERCIAL_LAW_STYLE_DEMOS.map((demo) => [demo.id, '2026-08-13T13:30:00+08:00'])) as Record<(typeof COMMERCIAL_LAW_STYLE_DEMOS)[number]['id'], string>;
