import {lazyDemo} from './lazy-demo';
import type {ComponentType} from 'react';
import {ADMINISTRATIVE_LAW_DEMO_ADDED_AT, ADMINISTRATIVE_LAW_STYLE_DEMOS} from './administrative-law-demo-registry';
import {DURATION_FRAMES as EVIDENCE_EXCLUSION_DURATION_FRAMES, FPS as EVIDENCE_EXCLUSION_FPS} from '../../animations/criminal-procedure/07/evidence-exclusion-lattice/remotion/storyboard';
import {DURATION_FRAMES as PROCEDURE_STRUCTURE_DURATION_FRAMES, FPS as PROCEDURE_STRUCTURE_FPS} from '../../animations/criminal-procedure/01/procedure-structure-orrery/remotion/storyboard';
import {DURATION_FRAMES as PLEA_LENIENTY_DURATION_FRAMES, FPS as PLEA_LENIENTY_FPS} from '../../animations/criminal-procedure/02/plea-leniency-caliper/remotion/storyboard';
import {DURATION_FRAMES as DELEGATED_DURATION_FRAMES, FPS as DELEGATED_FPS} from '../../animations/civil-procedure/08/delegated-agent/remotion/storyboard';
import {DURATION_FRAMES as JOINT_DURATION_FRAMES, FPS as JOINT_FPS} from '../../animations/civil-procedure/06/joint-litigation/remotion/storyboard';
import {DURATION_FRAMES as REPRESENTATIVE_DURATION_FRAMES, FPS as REPRESENTATIVE_FPS} from '../../animations/civil-procedure/06/representative-litigation/remotion/storyboard';
import {DURATION_FRAMES as REVOCATION_DURATION_FRAMES, FPS as REVOCATION_FPS} from '../../animations/civil-procedure/07/third-party-revocation/remotion/storyboard';
import {DURATION_FRAMES as STATUTORY_DURATION_FRAMES, FPS as STATUTORY_FPS} from '../../animations/civil-procedure/08/statutory-agent/remotion/storyboard';
import {DURATION_FRAMES as ADMISSION_DURATION_FRAMES, FPS as ADMISSION_FPS} from '../../animations/civil-procedure/09/admission-court-record/remotion/storyboard';
import {DURATION_FRAMES as BURDEN_DURATION_FRAMES, FPS as BURDEN_FPS} from '../../animations/civil-procedure/09/burden-of-proof-steps/remotion/storyboard';
import {DURATION_FRAMES as CAVEATS_DURATION_FRAMES, FPS as CAVEATS_FPS} from '../../animations/civil-procedure/09/burden-of-proof-caveats/remotion/storyboard';
import {DURATION_FRAMES as TYPES_DURATION_FRAMES, FPS as TYPES_FPS} from '../../animations/civil-procedure/07/third-party-types/remotion/storyboard';
import {DURATION_FRAMES as DOCUMENTARY_DURATION_FRAMES, FPS as DOCUMENTARY_FPS} from '../../animations/civil-procedure/10/documentary-evidence-rules/remotion/storyboard';
import {DURATION_FRAMES as EVIDENCE_DURATION_FRAMES, FPS as EVIDENCE_FPS} from '../../animations/civil-procedure/10/evidence-classification/remotion/storyboard';
import {DURATION_FRAMES as OFFICIAL_INTERMEDIARY_DURATION_FRAMES, FPS as OFFICIAL_INTERMEDIARY_FPS} from '../../animations/criminal/23/official-intermediary/remotion/storyboard';
import {DURATION_FRAMES as INFLUENCE_INTERMEDIARY_DURATION_FRAMES, FPS as INFLUENCE_INTERMEDIARY_FPS} from '../../animations/criminal/23/influence-intermediary/remotion/storyboard';
import {DURATION_FRAMES as PRESERVATION_DURATION_FRAMES, FPS as PRESERVATION_FPS} from '../../animations/civil-procedure/11/evidence-preservation/remotion/storyboard';
import {DURATION_FRAMES as REVIEW_DURATION_FRAMES, FPS as REVIEW_FPS} from '../../animations/civil-procedure/11/evidence-review/remotion/storyboard';
import {DURATION_FRAMES as FILING_DURATION_FRAMES, FPS as FILING_FPS} from '../../animations/civil-procedure/11/proof-filing-investigation/remotion/storyboard';
import {DURATION_FRAMES as FOCUS_DURATION_FRAMES, FPS as FOCUS_FPS} from '../../animations/civil-procedure/11/surprise-judgment-focus/remotion/storyboard';
import {DURATION_FRAMES as TRANSFER_DURATION_FRAMES, FPS as TRANSFER_FPS} from '../../animations/civil-procedure/12/pre-suit-preservation-transfer/remotion/storyboard';
import {DURATION_FRAMES as ASSET_MEASURES_DURATION_FRAMES, FPS as ASSET_MEASURES_FPS} from '../../animations/civil-procedure/12/preservation-asset-measures/remotion/storyboard';
import {DURATION_FRAMES as REMEDY_DURATION_FRAMES, FPS as REMEDY_FPS} from '../../animations/civil-procedure/12/preservation-remedy-switchboard/remotion/storyboard';
import {DURATION_FRAMES as STAGE_MAP_DURATION_FRAMES, FPS as STAGE_MAP_FPS} from '../../animations/civil-procedure/12/preservation-stage-map/remotion/storyboard';
import {DURATION_FRAMES as EXECUTION_GATES_DURATION_FRAMES, FPS as EXECUTION_GATES_FPS} from '../../animations/civil-procedure/12/provisional-execution-gates/remotion/storyboard';
import {DURATION_FRAMES as EXECUTION_RESOLUTION_DURATION_FRAMES, FPS as EXECUTION_RESOLUTION_FPS} from '../../animations/civil-procedure/12/provisional-execution-resolution/remotion/storyboard';
import {DURATION_FRAMES as BEHAVIOR_PRESERVATION_DURATION_FRAMES, FPS as BEHAVIOR_PRESERVATION_FPS} from '../../animations/civil-procedure/12/behavior-preservation/remotion/storyboard';
import {DURATION_FRAMES as PERIOD_DURATION_FRAMES, FPS as PERIOD_FPS} from '../../animations/civil-procedure/14/period-calculation/remotion/storyboard';
import {DURATION_FRAMES as SERVICE_DURATION_FRAMES, FPS as SERVICE_FPS} from '../../animations/civil-procedure/14/service-delivery-network/remotion/storyboard';
import {DURATION_FRAMES as SUMMARY_PROCEDURE_DURATION_FRAMES, FPS as SUMMARY_PROCEDURE_FPS} from '../../animations/civil-procedure/17/summary-procedure-switchyard/remotion/storyboard';
import {DURATION_FRAMES as PUBLIC_INTEREST_DURATION_FRAMES, FPS as PUBLIC_INTEREST_FPS} from '../../animations/civil-procedure/18/public-interest-litigation-network/remotion/storyboard';
import {DURATION_FRAMES as THIRD_PARTY_REMEDY_DURATION_FRAMES, FPS as THIRD_PARTY_REMEDY_FPS} from '../../animations/civil-procedure/19/third-party-revocation-remedy-map/remotion/storyboard';
import {DURATION_FRAMES as APPEAL_REVIEW_DURATION_FRAMES, FPS as APPEAL_REVIEW_FPS} from '../../animations/civil-procedure/20/appeal-review-decision-map/remotion/storyboard';
import {DURATION_FRAMES as PENALTY_ADJUSTMENT_DURATION_FRAMES, FPS as PENALTY_ADJUSTMENT_FPS} from '../../animations/civil-procedure/32/penalty-adjustment-procedure/remotion/storyboard';
import {DURATION_FRAMES as CONTRACT_BOOK_DURATION_FRAMES, FPS as CONTRACT_BOOK_FPS} from '../../animations/civil-law/contracts/contract-book-atlas/remotion/storyboard';
import {DURATION_FRAMES as SECURITY_PUBLICITY_DURATION_FRAMES, FPS as SECURITY_PUBLICITY_FPS} from '../../animations/civil-law/14/security-publicity-fate/remotion/storyboard';
import {DURATION_FRAMES as SIX_PRINCIPLES_DURATION_FRAMES, FPS as SIX_PRINCIPLES_FPS} from '../../animations/civil-law/01/six-principles-pillars/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_INTERPRETATION_DURATION_FRAMES, FPS as LEGAL_INTERPRETATION_FPS} from '../../animations/theoretical-law/17/legal-interpretation/remotion/storyboard';
import {DURATION_FRAMES as MARXIST_LAW_DURATION_FRAMES, FPS as MARXIST_LAW_FPS} from '../../animations/theoretical-law/01/marxist-law-essence/remotion/storyboard';
import {DURATION_FRAMES as FEATURES_OF_LAW_DURATION_FRAMES, FPS as FEATURES_OF_LAW_FPS} from '../../animations/theoretical-law/01/features-of-law/remotion/storyboard';
import {DURATION_FRAMES as FUNCTIONS_OF_LAW_DURATION_FRAMES, FPS as FUNCTIONS_OF_LAW_FPS} from '../../animations/theoretical-law/01/functions-of-law/remotion/storyboard';
import {DURATION_FRAMES as LIMITATIONS_OF_LAW_DURATION_FRAMES, FPS as LIMITATIONS_OF_LAW_FPS} from '../../animations/theoretical-law/01/limitations-of-law/remotion/storyboard';
import {DURATION_FRAMES as VALUE_CONFLICT_DURATION_FRAMES, FPS as VALUE_CONFLICT_FPS} from '../../animations/theoretical-law/01/value-conflict/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_RULES_DURATION_FRAMES, FPS as LEGAL_RULES_FPS} from '../../animations/theoretical-law/01/legal-rules/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_PRINCIPLES_DURATION_FRAMES, FPS as LEGAL_PRINCIPLES_FPS} from '../../animations/theoretical-law/01/legal-principles/remotion/storyboard';
import {DURATION_FRAMES as CONCEPT_OF_LAW_DURATION_FRAMES, FPS as CONCEPT_OF_LAW_FPS} from '../../animations/theoretical-law/01/concept-of-law-dispute/remotion/storyboard';
import {DURATION_FRAMES as SOURCES_OF_LAW_DURATION_FRAMES, FPS as SOURCES_OF_LAW_FPS} from '../../animations/theoretical-law/01/sources-of-law/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_DEPARTMENTS_SYSTEM_DURATION_FRAMES, FPS as LEGAL_DEPARTMENTS_SYSTEM_FPS} from '../../animations/theoretical-law/01/legal-departments-system/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_VALIDITY_DURATION_FRAMES, FPS as LEGAL_VALIDITY_FPS} from '../../animations/theoretical-law/01/legal-validity/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_RELATIONS_DURATION_FRAMES, FPS as LEGAL_RELATIONS_FPS} from '../../animations/theoretical-law/01/legal-relations/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_REASONING_DURATION_FRAMES, FPS as LEGAL_REASONING_FPS} from '../../animations/theoretical-law/01/legal-reasoning/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_FAMILIES_DURATION_FRAMES, FPS as LEGAL_FAMILIES_FPS} from '../../animations/theoretical-law/01/legal-families/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_MODERNIZATION_DURATION_FRAMES, FPS as LEGAL_MODERNIZATION_FPS} from '../../animations/theoretical-law/01/legal-modernization/remotion/storyboard';
import {DURATION_FRAMES as LAW_AND_MORALITY_DURATION_FRAMES, FPS as LAW_AND_MORALITY_FPS} from '../../animations/theoretical-law/01/law-and-morality/remotion/storyboard';
import {DURATION_FRAMES as LAW_AND_HUMAN_RIGHTS_DURATION_FRAMES, FPS as LAW_AND_HUMAN_RIGHTS_FPS} from '../../animations/theoretical-law/01/law-and-human-rights/remotion/storyboard';
import {DURATION_FRAMES as LEGISLATION_LAW_DURATION_FRAMES, FPS as LEGISLATION_LAW_FPS} from '../../animations/theoretical-law/01/legislation-law/remotion/storyboard';
import {DURATION_FRAMES as FEATURES_OF_CONSTITUTION_DURATION_FRAMES, FPS as FEATURES_OF_CONSTITUTION_FPS} from '../../animations/theoretical-law/01/features-of-constitution/remotion/storyboard';
import {DURATION_FRAMES as CREATION_OF_CONSTITUTION_DURATION_FRAMES, FPS as CREATION_OF_CONSTITUTION_FPS} from '../../animations/theoretical-law/01/creation-of-constitution/remotion/storyboard';
import {DURATION_FRAMES as CONSTITUTION_CLASSIFICATION_DURATION_FRAMES, FPS as CONSTITUTION_CLASSIFICATION_FPS} from '../../animations/theoretical-law/01/constitution-classification/remotion/storyboard';
import {DURATION_FRAMES as RESERVE_GRANARY_DURATION_FRAMES, FPS as RESERVE_GRANARY_FPS} from '../../animations/commercial-economic-law/01/profit-reserve-granary/remotion/storyboard';
import {DURATION_FRAMES as PROMOTER_ROPEWALK_DURATION_FRAMES, FPS as PROMOTER_ROPEWALK_FPS} from '../../animations/commercial-economic-law/01/promoter-liability-ropewalk/remotion/storyboard';
import {DURATION_FRAMES as REGISTER_PIGEONHOLE_DURATION_FRAMES, FPS as REGISTER_PIGEONHOLE_FPS} from '../../animations/commercial-economic-law/01/shareholder-register-pigeonhole/remotion/storyboard';
import {DURATION_FRAMES as NOMINEE_MASKS_DURATION_FRAMES, FPS as NOMINEE_MASKS_FPS} from '../../animations/commercial-economic-law/01/nominee-impersonation-masks/remotion/storyboard';
import {DURATION_FRAMES as DEFECT_AUDIT_DURATION_FRAMES, FPS as DEFECT_AUDIT_FPS} from '../../animations/commercial-economic-law/01/contribution-defect-audit/remotion/storyboard';
import {DURATION_FRAMES as GUARANTY_DESK_DURATION_FRAMES, FPS as GUARANTY_DESK_FPS} from '../../animations/commercial-economic-law/01/company-guaranty-seal-desk/remotion/storyboard';
import {DURATION_FRAMES as CAPITAL_REGIME_DURATION_FRAMES, FPS as CAPITAL_REGIME_FPS} from '../../animations/commercial-economic-law/01/capital-regime-vote-hall/remotion/storyboard';
import {DURATION_FRAMES as LIABILITY_CONCURRENCE_DURATION_FRAMES, FPS as LIABILITY_CONCURRENCE_FPS} from '../../animations/theoretical-law/01/liability-concurrence/remotion/storyboard';
import {DURATION_FRAMES as JUDICIAL_VS_ADMINISTRATIVE_DURATION_FRAMES, FPS as JUDICIAL_VS_ADMINISTRATIVE_FPS} from '../../animations/theoretical-law/01/judicial-vs-administrative/remotion/storyboard';
import {DURATION_FRAMES as APPLICATION_OF_LAW_DURATION_FRAMES, FPS as APPLICATION_OF_LAW_FPS} from '../../animations/theoretical-law/01/application-of-law/remotion/storyboard';
import {DURATION_FRAMES as LEGAL_LOOPHOLES_DURATION_FRAMES, FPS as LEGAL_LOOPHOLES_FPS} from '../../animations/theoretical-law/01/legal-loopholes/remotion/storyboard';
import {DURATION_FRAMES as ORGANS_RELAY_DURATION_FRAMES, FPS as ORGANS_RELAY_FPS} from '../../animations/criminal-procedure/03/organs-relay-map/remotion/storyboard';
import {DURATION_FRAMES as JURISDICTION_SLUICE_DURATION_FRAMES, FPS as JURISDICTION_SLUICE_FPS} from '../../animations/criminal-procedure/04/jurisdiction-sluice-terrace/remotion/storyboard';
import {DURATION_FRAMES as RECUSAL_SENTRY_DURATION_FRAMES, FPS as RECUSAL_SENTRY_FPS} from '../../animations/criminal-procedure/05/recusal-sentry-rotation/remotion/storyboard';
import {DURATION_FRAMES as DEFENSE_PILOT_DURATION_FRAMES, FPS as DEFENSE_PILOT_FPS} from '../../animations/criminal-procedure/06/defense-pilot-harbor/remotion/storyboard';
import {DURATION_FRAMES as COERCION_LADDER_DURATION_FRAMES, FPS as COERCION_LADDER_FPS} from '../../animations/criminal-procedure/08/coercion-pressure-ladder/remotion/storyboard';
import {DURATION_FRAMES as ATTACHED_SUIT_DURATION_FRAMES, FPS as ATTACHED_SUIT_FPS} from '../../animations/criminal-procedure/09/attached-suit-viaduct/remotion/storyboard';
import {DURATION_FRAMES as PERIOD_ESCAPEMENT_DURATION_FRAMES, FPS as PERIOD_ESCAPEMENT_FPS} from '../../animations/criminal-procedure/10/period-escapement-works/remotion/storyboard';
import {DURATION_FRAMES as FILING_GATEHOUSE_DURATION_FRAMES, FPS as FILING_GATEHOUSE_FPS} from '../../animations/criminal-procedure/11/case-filing-gatehouse/remotion/storyboard';
import {DURATION_FRAMES as SUPPLEMENT_LOOP_DURATION_FRAMES, FPS as SUPPLEMENT_LOOP_FPS} from '../../animations/criminal-procedure/12/supplement-invest-loop/remotion/storyboard';
import {DURATION_FRAMES as NONPROSECUTION_TOWER_DURATION_FRAMES, FPS as NONPROSECUTION_TOWER_FPS} from '../../animations/criminal-procedure/13/nonprosecution-signal-tower/remotion/storyboard';
import {DURATION_FRAMES as TRIAL_BENCH_DURATION_FRAMES, FPS as TRIAL_BENCH_FPS} from '../../animations/criminal-procedure/14/trial-bench-composition/remotion/storyboard';
import {DURATION_FRAMES as FIRST_INSTANCE_DURATION_FRAMES, FPS as FIRST_INSTANCE_FPS} from '../../animations/criminal-procedure/15/first-instance-procession/remotion/storyboard';
import {DURATION_FRAMES as APPEAL_LOCK_DURATION_FRAMES, FPS as APPEAL_LOCK_FPS} from '../../animations/criminal-procedure/16/appeal-no-escalation-lock/remotion/storyboard';
import {DURATION_FRAMES as RETRAL_LOOM_DURATION_FRAMES, FPS as RETRAL_LOOM_FPS} from '../../animations/criminal-procedure/18/retrial-rewind-loom/remotion/storyboard';
import {DURATION_FRAMES as EXECUTION_DISPATCH_DURATION_FRAMES, FPS as EXECUTION_DISPATCH_FPS} from '../../animations/criminal-procedure/19/execution-dispatch-board/remotion/storyboard';
import {DURATION_FRAMES as JUVENILE_GREENHOUSE_DURATION_FRAMES, FPS as JUVENILE_GREENHOUSE_FPS} from '../../animations/criminal-procedure/20/juvenile-observatory-greenhouse/remotion/storyboard';
import {DURATION_FRAMES as DEATH_REVIEW_DURATION_FRAMES, FPS as DEATH_REVIEW_FPS} from '../../animations/criminal-procedure/17/death-review-summit/remotion/storyboard';
import {DURATION_FRAMES as SOURCES_INTERNATIONAL_LAW_DURATION_FRAMES, FPS as SOURCES_INTERNATIONAL_LAW_FPS} from '../../animations/international-law/01/sources-of-international-law/remotion/storyboard';
import {DURATION_FRAMES as SUBJECTS_RESPONSIBILITY_DURATION_FRAMES, FPS as SUBJECTS_RESPONSIBILITY_FPS} from '../../animations/international-law/02/subjects-responsibility/remotion/storyboard';
import {DURATION_FRAMES as SPATIAL_REGIMES_DURATION_FRAMES, FPS as SPATIAL_REGIMES_FPS} from '../../animations/international-law/03/spatial-regimes/remotion/storyboard';
import {DURATION_FRAMES as INDIVIDUALS_REGIMES_DURATION_FRAMES, FPS as INDIVIDUALS_REGIMES_FPS} from '../../animations/international-law/04/individuals-regimes/remotion/storyboard';
import {DURATION_FRAMES as DIPLOMATIC_CONSULAR_DURATION_FRAMES, FPS as DIPLOMATIC_CONSULAR_FPS} from '../../animations/international-law/05/diplomatic-consular/remotion/storyboard';
import {DURATION_FRAMES as LAW_OF_TREATIES_DURATION_FRAMES, FPS as LAW_OF_TREATIES_FPS} from '../../animations/international-law/06/law-of-treaties/remotion/storyboard';
import {DURATION_FRAMES as DISPUTE_SETTLEMENT_DURATION_FRAMES, FPS as DISPUTE_SETTLEMENT_FPS} from '../../animations/international-law/07/dispute-settlement/remotion/storyboard';
import {DURATION_FRAMES as WAR_ARMED_CONFLICT_DURATION_FRAMES, FPS as WAR_ARMED_CONFLICT_FPS} from '../../animations/international-law/08/war-armed-conflict/remotion/storyboard';
import {DURATION_FRAMES as CROSS_BORDER_DISPUTES_DURATION_FRAMES, FPS as CROSS_BORDER_DISPUTES_FPS} from '../../animations/international-law/09/cross-border-disputes/remotion/storyboard';
import {DURATION_FRAMES as CONFLICT_OF_LAWS_DURATION_FRAMES, FPS as CONFLICT_OF_LAWS_FPS} from '../../animations/international-law/10/conflict-of-laws-rules/remotion/storyboard';
import {DURATION_FRAMES as APPLICABLE_LAW_DURATION_FRAMES, FPS as APPLICABLE_LAW_FPS} from '../../animations/international-law/11/applicable-law/remotion/storyboard';
import {DURATION_FRAMES as INTERREGIONAL_DURATION_FRAMES, FPS as INTERREGIONAL_FPS} from '../../animations/international-law/13/interregional-assistance/remotion/storyboard';
import {DURATION_FRAMES as WTO_DURATION_FRAMES, FPS as WTO_FPS} from '../../animations/international-law/18/wto/remotion/storyboard';
import {DURATION_FRAMES as TRANSPORT_INS_DURATION_FRAMES, FPS as TRANSPORT_INS_FPS} from '../../animations/international-law/15/goods-transport-insurance/remotion/storyboard';
import {DURATION_FRAMES as EXTRATERRITORIAL_ASSISTANCE_DURATION_FRAMES, FPS as EXTRATERRITORIAL_ASSISTANCE_FPS} from '../../animations/international-law/12/extraterritorial-assistance/remotion/storyboard';
import {DURATION_FRAMES as INTERNATIONAL_SALE_OF_GOODS_DURATION_FRAMES, FPS as INTERNATIONAL_SALE_OF_GOODS_FPS} from '../../animations/international-law/14/international-sale-of-goods/remotion/storyboard';
import {DURATION_FRAMES as INTERNATIONAL_TRADE_PAYMENT_DURATION_FRAMES, FPS as INTERNATIONAL_TRADE_PAYMENT_FPS} from '../../animations/international-law/16/international-trade-payment/remotion/storyboard';
import {DURATION_FRAMES as FOREIGN_TRADE_ADMINISTRATION_DURATION_FRAMES, FPS as FOREIGN_TRADE_ADMINISTRATION_FPS} from '../../animations/international-law/17/foreign-trade-administration/remotion/storyboard';
import {DURATION_FRAMES as OTHER_REGIMES_INTL_ECON_DURATION_FRAMES, FPS as OTHER_REGIMES_INTL_ECON_FPS} from '../../animations/international-law/19/other-regimes-international-economic-law/remotion/storyboard';
import {getAnimationTypographyConfiguration} from '../../typography/animation-registry';
import {withAnimationTypography} from '../../typography/animation-provider';
import {DURATION_FRAMES as FIGHT_DURATION_FRAMES, FPS as FIGHT_FPS} from '../../animations/criminal/22/fight-defense-diagram/remotion/storyboard';
import {DURATION_FRAMES as BRANCH_WALLET_DURATION_FRAMES, FPS as BRANCH_WALLET_FPS} from '../../animations/commercial-economic-law/01/branch-wallet-ledger/remotion/storyboard';
import {DURATION_FRAMES as VEIL_PIERCING_DURATION_FRAMES, FPS as VEIL_PIERCING_FPS} from '../../animations/commercial-economic-law/01/veil-piercing-forge/remotion/storyboard';
import {DURATION_FRAMES as ALTITUDE_DURATION_FRAMES, FPS as ALTITUDE_FPS} from '../../animations/criminal/22/high-altitude-throwing-diagram/remotion/storyboard';
import {DURATION_FRAMES as THEFT_DURATION_FRAMES, FPS as THEFT_FPS} from '../../animations/criminal/19/theft-mistake-analysis/remotion/storyboard';
import {DURATION_FRAMES as OCCUPATIONAL_DURATION_FRAMES, FPS as OCCUPATIONAL_FPS} from '../../animations/criminal/19/occupational-embezzlement-flowchart/remotion/storyboard';
import {DURATION_FRAMES as CARD_FUNDS_DURATION_FRAMES, FPS as CARD_FUNDS_FPS} from '../../animations/criminal/19/card-selling-funds-viewpoint/remotion/storyboard';
import {DURATION_FRAMES as PROPERTY_INTERESTS_DURATION_FRAMES, FPS as PROPERTY_INTERESTS_FPS} from '../../animations/criminal/19/property-interests-keypoints/remotion/storyboard';

export interface DemoDefinition {
  readonly id: string;
  readonly slug: string;
  readonly title: string;
  readonly direction: string;
  readonly component: ComponentType<Record<string, never>>;
  readonly href?: string;
  readonly durationInFrames: number;
  readonly fps: number;
}

export const STYLE_DEMOS = [
  ...ADMINISTRATIVE_LAW_STYLE_DEMOS,
  {id: 'demo-courtroom-blueprint', slug: 'courtroom-blueprint', title: '法庭蓝图', direction: 'Courtroom Blueprint', component: lazyDemo(() => import('../../animations/demo/demo-courtroom-blueprint/remotion/CourtroomBlueprintDemo').then((m) => ({default: m.CourtroomBlueprintDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-archival-dossier', slug: 'archival-dossier', title: '档案卷宗', direction: 'Archival Dossier', component: lazyDemo(() => import('../../animations/demo/demo-archival-dossier/remotion/ArchivalDossierDemo').then((m) => ({default: m.ArchivalDossierDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-newspaper-editorial', slug: 'newspaper-editorial', title: '报刊编辑', direction: 'Newspaper Editorial', component: lazyDemo(() => import('../../animations/demo/demo-newspaper-editorial/remotion/NewspaperEditorialDemo').then((m) => ({default: m.NewspaperEditorialDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-constructivist-geometry', slug: 'constructivist-geometry', title: '构成主义几何', direction: 'Constructivist Geometry', component: lazyDemo(() => import('../../animations/demo/demo-constructivist-geometry/remotion/ConstructivistGeometryDemo').then((m) => ({default: m.ConstructivistGeometryDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-ink-annotation', slug: 'ink-annotation', title: '墨迹批注', direction: 'Ink Annotation', component: lazyDemo(() => import('../../animations/demo/demo-ink-annotation/remotion/InkAnnotationDemo').then((m) => ({default: m.InkAnnotationDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-evidence-board', slug: 'evidence-board', title: '证据板', direction: 'Evidence Board', component: lazyDemo(() => import('../../animations/demo/demo-evidence-board/remotion/EvidenceBoardDemo').then((m) => ({default: m.EvidenceBoardDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-isometric-mechanism', slug: 'isometric-mechanism', title: '等距机械', direction: 'Isometric Mechanism', component: lazyDemo(() => import('../../animations/demo/demo-isometric-mechanism/remotion/IsometricMechanismDemo').then((m) => ({default: m.IsometricMechanismDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-timeline-chronicle', slug: 'timeline-chronicle', title: '时间轴编年体', direction: 'Timeline Chronicle', component: lazyDemo(() => import('../../animations/demo/demo-timeline-chronicle/remotion/TimelineChronicleDemo').then((m) => ({default: m.TimelineChronicleDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-statute-commentary', slug: 'statute-commentary', title: '法条注释', direction: 'Statute Commentary', component: lazyDemo(() => import('../../animations/demo/demo-statute-commentary/remotion/StatuteCommentaryDemo').then((m) => ({default: m.StatuteCommentaryDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-decision-tree', slug: 'decision-tree', title: '决策树', direction: 'Decision Tree', component: lazyDemo(() => import('../../animations/demo/demo-decision-tree/remotion/DecisionTreeDemo').then((m) => ({default: m.DecisionTreeDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-rights-matrix', slug: 'rights-matrix', title: '权利矩阵', direction: 'Rights Matrix', component: lazyDemo(() => import('../../animations/demo/demo-rights-matrix/remotion/RightsMatrixDemo').then((m) => ({default: m.RightsMatrixDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-kinetic-typography', slug: 'kinetic-typography', title: '动态字体', direction: 'Kinetic Typography', component: lazyDemo(() => import('../../animations/demo/demo-kinetic-typography/remotion/KineticTypographyDemo').then((m) => ({default: m.KineticTypographyDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-split-screen-comparison', slug: 'split-screen-comparison', title: '分屏比较', direction: 'Split-Screen Comparison', component: lazyDemo(() => import('../../animations/demo/demo-split-screen-comparison/remotion/SplitScreenComparisonDemo').then((m) => ({default: m.SplitScreenComparisonDemo}))), durationInFrames: 240, fps: 60},
  {id: 'demo-transit-map', slug: 'transit-map', title: '推理线路图', direction: 'Transit Map', component: lazyDemo(() => import('../../animations/demo/demo-transit-map/remotion/TransitMapDemo').then((m) => ({default: m.TransitMapDemo}))), durationInFrames: 240, fps: 60},
  {id: 'civil-procedure-06-joint-litigation', slug: 'joint-litigation', title: '共同诉讼', direction: 'Case Bindery Workshop', component: lazyDemo(() => import('../../animations/civil-procedure/06/joint-litigation/remotion/JointLitigation').then((m) => ({default: m.JointLitigation}))), href: '/inkloom/objective/civil-procedure/06/joint-litigation/', durationInFrames: JOINT_DURATION_FRAMES, fps: JOINT_FPS},
  {id: 'civil-procedure-06-representative-litigation', slug: 'representative-litigation', title: '代表人诉讼', direction: 'Representative Signal Exchange', component: lazyDemo(() => import('../../animations/civil-procedure/06/representative-litigation/remotion/RepresentativeLitigation').then((m) => ({default: m.RepresentativeLitigation}))), href: '/inkloom/objective/civil-procedure/06/representative-litigation/', durationInFrames: REPRESENTATIVE_DURATION_FRAMES, fps: REPRESENTATIVE_FPS},
  {id: 'civil-procedure-07-third-party-types', slug: 'third-party-types', title: '关系定位图', direction: 'Legal Relation Map', component: lazyDemo(() => import('../../animations/civil-procedure/07/third-party-types/remotion/ThirdPartyTypes').then((m) => ({default: m.ThirdPartyTypes}))), href: '/inkloom/objective/civil-procedure/07/third-party-types/', durationInFrames: TYPES_DURATION_FRAMES, fps: TYPES_FPS},
  {id: 'civil-procedure-07-third-party-revocation', slug: 'third-party-revocation', title: '套色印版', direction: 'Procedural Screenprint', component: lazyDemo(() => import('../../animations/civil-procedure/07/third-party-revocation/remotion/ThirdPartyRevocation').then((m) => ({default: m.ThirdPartyRevocation}))), href: '/inkloom/objective/civil-procedure/07/third-party-revocation/', durationInFrames: REVOCATION_DURATION_FRAMES, fps: REVOCATION_FPS},
  {id: 'civil-procedure-08-statutory-agent', slug: 'statutory-agent', title: '法定代理人', direction: 'Guardian Identity Ledger', component: lazyDemo(() => import('../../animations/civil-procedure/08/statutory-agent/remotion/StatutoryAgent').then((m) => ({default: m.StatutoryAgent}))), href: '/inkloom/objective/civil-procedure/08/statutory-agent/', durationInFrames: STATUTORY_DURATION_FRAMES, fps: STATUTORY_FPS},
  {id: 'civil-procedure-08-delegated-agent', slug: 'delegated-agent', title: '委托代理人', direction: 'Power-of-Attorney Contract', component: lazyDemo(() => import('../../animations/civil-procedure/08/delegated-agent/remotion/DelegatedAgent').then((m) => ({default: m.DelegatedAgent}))), href: '/inkloom/objective/civil-procedure/08/delegated-agent/', durationInFrames: DELEGATED_DURATION_FRAMES, fps: DELEGATED_FPS},
  {id: 'civil-procedure-09-admission-court-record', slug: 'admission-court-record', title: '法庭声纹图', direction: 'Court Signal Waveform', component: lazyDemo(() => import('../../animations/civil-procedure/09/admission-court-record/remotion/AdmissionCourtRecord').then((m) => ({default: m.AdmissionCourtRecord}))), href: '/inkloom/objective/civil-procedure/09/admission-court-record/', durationInFrames: ADMISSION_DURATION_FRAMES, fps: ADMISSION_FPS},
  {id: 'civil-procedure-09-burden-of-proof-steps', slug: 'burden-of-proof-steps', title: '构成举证场', direction: 'Constructivist Proof Field', component: lazyDemo(() => import('../../animations/civil-procedure/09/burden-of-proof-steps/remotion/BurdenOfProofSteps').then((m) => ({default: m.BurdenOfProofSteps}))), href: '/inkloom/objective/civil-procedure/09/burden-of-proof-steps/', durationInFrames: BURDEN_DURATION_FRAMES, fps: BURDEN_FPS},
  {id: 'civil-procedure-09-burden-of-proof-caveats', slug: 'burden-of-proof-caveats', title: '证明边界簿', direction: 'Proof Boundary Ledger', component: lazyDemo(() => import('../../animations/civil-procedure/09/burden-of-proof-caveats/remotion/BurdenOfProofCaveats').then((m) => ({default: m.BurdenOfProofCaveats}))), href: '/inkloom/objective/civil-procedure/09/burden-of-proof-caveats/', durationInFrames: CAVEATS_DURATION_FRAMES, fps: CAVEATS_FPS},
  {id: 'civil-procedure-10-evidence-classification', slug: 'evidence-classification', title: '检材透视台', direction: 'Forensic Light Table', component: lazyDemo(() => import('../../animations/civil-procedure/10/evidence-classification/remotion/EvidenceClassification').then((m) => ({default: m.EvidenceClassification}))), href: '/inkloom/objective/civil-procedure/10/evidence-classification/', durationInFrames: EVIDENCE_DURATION_FRAMES, fps: EVIDENCE_FPS},
  {id: 'civil-procedure-10-documentary-evidence-rules', slug: 'documentary-evidence-rules', title: '文书验印所', direction: 'Civic Seal Registry', component: lazyDemo(() => import('../../animations/civil-procedure/10/documentary-evidence-rules/remotion/DocumentaryEvidenceRules').then((m) => ({default: m.DocumentaryEvidenceRules}))), href: '/inkloom/objective/civil-procedure/10/documentary-evidence-rules/', durationInFrames: DOCUMENTARY_DURATION_FRAMES, fps: DOCUMENTARY_FPS},
  {id: 'civil-procedure-11-evidence-preservation', slug: 'evidence-preservation', title: '证据保全舱', direction: 'Evidence Cold Storage', component: lazyDemo(() => import('../../animations/civil-procedure/11/evidence-preservation/remotion/EvidencePreservation').then((m) => ({default: m.EvidencePreservation}))), href: '/inkloom/objective/civil-procedure/11/evidence-preservation/', durationInFrames: PRESERVATION_DURATION_FRAMES, fps: PRESERVATION_FPS},
  {id: 'civil-procedure-11-proof-filing-investigation', slug: 'proof-filing-investigation', title: '举证调度台', direction: 'Proof Dispatch Delta', component: lazyDemo(() => import('../../animations/civil-procedure/11/proof-filing-investigation/remotion/ProofFilingInvestigation').then((m) => ({default: m.ProofFilingInvestigation}))), href: '/inkloom/objective/civil-procedure/11/proof-filing-investigation/', durationInFrames: FILING_DURATION_FRAMES, fps: FILING_FPS},
  {id: 'civil-procedure-11-surprise-judgment-focus', slug: 'surprise-judgment-focus', title: '争点聚光场', direction: 'Argument Focus Theater', component: lazyDemo(() => import('../../animations/civil-procedure/11/surprise-judgment-focus/remotion/SurpriseJudgmentFocus').then((m) => ({default: m.SurpriseJudgmentFocus}))), href: '/inkloom/objective/civil-procedure/11/surprise-judgment-focus/', durationInFrames: FOCUS_DURATION_FRAMES, fps: FOCUS_FPS},
  {id: 'civil-procedure-11-evidence-review', slug: 'evidence-review', title: '心证衡量室', direction: 'Evidence Weighing Chamber', component: lazyDemo(() => import('../../animations/civil-procedure/11/evidence-review/remotion/EvidenceReview').then((m) => ({default: m.EvidenceReview}))), href: '/inkloom/objective/civil-procedure/11/evidence-review/', durationInFrames: REVIEW_DURATION_FRAMES, fps: REVIEW_FPS},
  {id: 'civil-procedure-12-preservation-stage-map', slug: 'preservation-stage-map', title: '程序潮汐盘', direction: 'Procedural Tide Dial', component: lazyDemo(() => import('../../animations/civil-procedure/12/preservation-stage-map/remotion/PreservationStageMap').then((m) => ({default: m.PreservationStageMap}))), href: '/inkloom/objective/civil-procedure/12/preservation-stage-map/', durationInFrames: STAGE_MAP_DURATION_FRAMES, fps: STAGE_MAP_FPS},
  {id: 'civil-procedure-12-pre-suit-preservation-transfer', slug: 'pre-suit-preservation-transfer', title: '法院转运台', direction: 'Court Routing Table', component: lazyDemo(() => import('../../animations/civil-procedure/12/pre-suit-preservation-transfer/remotion/PreSuitPreservationTransfer').then((m) => ({default: m.PreSuitPreservationTransfer}))), href: '/inkloom/objective/civil-procedure/12/pre-suit-preservation-transfer/', durationInFrames: TRANSFER_DURATION_FRAMES, fps: TRANSFER_FPS},
  {id: 'civil-procedure-12-preservation-asset-measures', slug: 'preservation-asset-measures', title: '财产保鲜仓', direction: 'Asset Conservation Depot', component: lazyDemo(() => import('../../animations/civil-procedure/12/preservation-asset-measures/remotion/PreservationAssetMeasures').then((m) => ({default: m.PreservationAssetMeasures}))), href: '/inkloom/objective/civil-procedure/12/preservation-asset-measures/', durationInFrames: ASSET_MEASURES_DURATION_FRAMES, fps: ASSET_MEASURES_FPS},
  {id: 'civil-procedure-12-preservation-remedy-switchboard', slug: 'preservation-remedy-switchboard', title: '救济拨盘', direction: 'Remedy Switchboard', component: lazyDemo(() => import('../../animations/civil-procedure/12/preservation-remedy-switchboard/remotion/PreservationRemedySwitchboard').then((m) => ({default: m.PreservationRemedySwitchboard}))), href: '/inkloom/objective/civil-procedure/12/preservation-remedy-switchboard/', durationInFrames: REMEDY_DURATION_FRAMES, fps: REMEDY_FPS},
  {id: 'civil-procedure-12-provisional-execution-gates', slug: 'provisional-execution-gates', title: '紧急救助分诊', direction: 'Emergency Relief Triage', component: lazyDemo(() => import('../../animations/civil-procedure/12/provisional-execution-gates/remotion/ProvisionalExecutionGates').then((m) => ({default: m.ProvisionalExecutionGates}))), href: '/inkloom/objective/civil-procedure/12/provisional-execution-gates/', durationInFrames: EXECUTION_GATES_DURATION_FRAMES, fps: EXECUTION_GATES_FPS},
  {id: 'civil-procedure-12-provisional-execution-resolution', slug: 'provisional-execution-resolution', title: '裁判清算簿', direction: 'Judgment Settlement Ledger', component: lazyDemo(() => import('../../animations/civil-procedure/12/provisional-execution-resolution/remotion/ProvisionalExecutionResolution').then((m) => ({default: m.ProvisionalExecutionResolution}))), href: '/inkloom/objective/civil-procedure/12/provisional-execution-resolution/', durationInFrames: EXECUTION_RESOLUTION_DURATION_FRAMES, fps: EXECUTION_RESOLUTION_FPS},
  {id: 'civil-procedure-12-behavior-preservation', slug: 'behavior-preservation', title: '禁令指令台', direction: 'Injunction Command Board', component: lazyDemo(() => import('../../animations/civil-procedure/12/behavior-preservation/remotion/BehaviorPreservation').then((m) => ({default: m.BehaviorPreservation}))), href: '/inkloom/objective/civil-procedure/12/behavior-preservation/', durationInFrames: BEHAVIOR_PRESERVATION_DURATION_FRAMES, fps: BEHAVIOR_PRESERVATION_FPS},
  {id: 'civil-procedure-14-period-calculation', slug: 'period-calculation', title: '期限信号台', direction: 'Deadline Signal Board', component: lazyDemo(() => import('../../animations/civil-procedure/14/period-calculation/remotion/PeriodCalculation').then((m) => ({default: m.PeriodCalculation}))), href: '/inkloom/objective/civil-procedure/14/period-calculation/', durationInFrames: PERIOD_DURATION_FRAMES, fps: PERIOD_FPS},
  {id: 'civil-procedure-14-service-delivery-network', slug: 'service-delivery-network', title: '送达卷宗流', direction: 'Service Dossier Flow', component: lazyDemo(() => import('../../animations/civil-procedure/14/service-delivery-network/remotion/ServiceDeliveryNetwork').then((m) => ({default: m.ServiceDeliveryNetwork}))), href: '/inkloom/objective/civil-procedure/14/service-delivery-network/', durationInFrames: SERVICE_DURATION_FRAMES, fps: SERVICE_FPS},
  {id: 'criminal-22-fight-defense-diagram', slug: 'fight-defense-diagram', title: '意图对抗场', direction: 'Intent Combat Field', component: lazyDemo(() => import('../../animations/criminal/22/fight-defense-diagram/remotion/FightDefenseDiagram').then((m) => ({default: m.FightDefenseDiagram}))), href: '/inkloom/objective/criminal/22/fight-defense-diagram/', durationInFrames: FIGHT_DURATION_FRAMES, fps: FIGHT_FPS},
  {id: 'commercial-economic-law-01-branch-wallet-ledger', slug: 'branch-wallet-ledger', title: '票号夹层钱柜', direction: 'Shanxi Draft Bank Counter', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/branch-wallet-ledger/remotion/BranchWalletLedger').then((m) => ({default: m.BranchWalletLedger}))), href: '/inkloom/objective/commercial-economic-law/01/branch-wallet-ledger/', durationInFrames: BRANCH_WALLET_DURATION_FRAMES, fps: BRANCH_WALLET_FPS},
  {id: 'commercial-economic-law-01-veil-piercing-forge', slug: 'veil-piercing-forge', title: '锁匠链环锻坊', direction: 'Locksmith Chain Forge', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/veil-piercing-forge/remotion/VeilPiercingForge').then((m) => ({default: m.VeilPiercingForge}))), href: '/inkloom/objective/commercial-economic-law/01/veil-piercing-forge/', durationInFrames: VEIL_PIERCING_DURATION_FRAMES, fps: VEIL_PIERCING_FPS},
  {id: 'criminal-22-high-altitude-throwing-diagram', slug: 'high-altitude-throwing-diagram', title: '垂直危险剖面', direction: 'Vertical Risk Section', component: lazyDemo(() => import('../../animations/criminal/22/high-altitude-throwing-diagram/remotion/HighAltitudeThrowingDiagram').then((m) => ({default: m.HighAltitudeThrowingDiagram}))), href: '/inkloom/objective/criminal/22/high-altitude-throwing-diagram/', durationInFrames: ALTITUDE_DURATION_FRAMES, fps: ALTITUDE_FPS},
  {id: 'criminal-19-theft-mistake-analysis', slug: 'theft-mistake-analysis', title: '双焦校准台', direction: 'Dual-Focus Calibration', component: lazyDemo(() => import('../../animations/criminal/19/theft-mistake-analysis/remotion/TheftMistakeAnalysis').then((m) => ({default: m.TheftMistakeAnalysis}))), href: '/inkloom/objective/criminal/19/theft-mistake-analysis/', durationInFrames: THEFT_DURATION_FRAMES, fps: THEFT_FPS},
  {id: 'criminal-19-occupational-embezzlement-flowchart', slug: 'occupational-embezzlement-flowchart', title: '要件质检线', direction: 'Industrial Elements Inspection', component: lazyDemo(() => import('../../animations/criminal/19/occupational-embezzlement-flowchart/remotion/OccupationalEmbezzlementFlowchart').then((m) => ({default: m.OccupationalEmbezzlementFlowchart}))), href: '/inkloom/objective/criminal/19/occupational-embezzlement-flowchart/', durationInFrames: OCCUPATIONAL_DURATION_FRAMES, fps: OCCUPATIONAL_FPS},
  {id: 'criminal-19-card-selling-funds-viewpoint', slug: 'card-selling-funds-viewpoint', title: '账户信号台', direction: 'Account Signal Router', component: lazyDemo(() => import('../../animations/criminal/19/card-selling-funds-viewpoint/remotion/CardSellingFundsViewpoint').then((m) => ({default: m.CardSellingFundsViewpoint}))), href: '/inkloom/objective/criminal/19/card-selling-funds-viewpoint/', durationInFrames: CARD_FUNDS_DURATION_FRAMES, fps: CARD_FUNDS_FPS},
  {id: 'criminal-19-property-interests-keypoints', slug: 'property-interests-keypoints', title: '价值拓扑图册', direction: 'Value Topology Atlas', component: lazyDemo(() => import('../../animations/criminal/19/property-interests-keypoints/remotion/PropertyInterestsKeypoints').then((m) => ({default: m.PropertyInterestsKeypoints}))), href: '/inkloom/objective/criminal/19/property-interests-keypoints/', durationInFrames: PROPERTY_INTERESTS_DURATION_FRAMES, fps: PROPERTY_INTERESTS_FPS},
  {id: 'criminal-23-official-intermediary', slug: 'official-intermediary', title: '财政稽核分流台', direction: 'Fiscal Audit Ledger', component: lazyDemo(() => import('../../animations/criminal/23/official-intermediary/remotion/OfficialIntermediary').then((m) => ({default: m.OfficialIntermediary}))), href: '/inkloom/objective/criminal/23/joint-crime/', durationInFrames: OFFICIAL_INTERMEDIARY_DURATION_FRAMES, fps: OFFICIAL_INTERMEDIARY_FPS},
  {id: 'criminal-23-influence-intermediary', slug: 'influence-intermediary', title: '关系引力图谱', direction: 'Private Influence Network', component: lazyDemo(() => import('../../animations/criminal/23/influence-intermediary/remotion/InfluenceIntermediary').then((m) => ({default: m.InfluenceIntermediary}))), href: '/inkloom/objective/criminal/23/joint-crime/', durationInFrames: INFLUENCE_INTERMEDIARY_DURATION_FRAMES, fps: INFLUENCE_INTERMEDIARY_FPS},
  {id: 'civil-procedure-17-summary-procedure-switchyard', slug: 'summary-procedure-switchyard', title: '程序转辙珐琅', direction: 'Enamel Procedure Switchyard', component: lazyDemo(() => import('../../animations/civil-procedure/17/summary-procedure-switchyard/remotion/SummaryProcedureSwitchyard').then((m) => ({default: m.SummaryProcedureSwitchyard}))), href: '/inkloom/objective/civil-procedure/17/summary-procedure-switchyard/', durationInFrames: SUMMARY_PROCEDURE_DURATION_FRAMES, fps: SUMMARY_PROCEDURE_FPS},
  {id: 'civil-procedure-18-public-interest-litigation-network', slug: 'public-interest-litigation-network', title: '公共公告网络', direction: 'Civic Notice Network', component: lazyDemo(() => import('../../animations/civil-procedure/18/public-interest-litigation-network/remotion/PublicInterestLitigationNetwork').then((m) => ({default: m.PublicInterestLitigationNetwork}))), href: '/inkloom/objective/civil-procedure/18/public-interest-litigation-network/', durationInFrames: PUBLIC_INTEREST_DURATION_FRAMES, fps: PUBLIC_INTEREST_FPS},
  {id: 'civil-procedure-19-third-party-revocation-remedy-map', slug: 'third-party-revocation-remedy-map', title: '裁判叠层剖面', direction: 'Judgment Palimpsest Cutaway', component: lazyDemo(() => import('../../animations/civil-procedure/19/third-party-revocation-remedy-map/remotion/ThirdPartyRevocationRemedyMap').then((m) => ({default: m.ThirdPartyRevocationRemedyMap}))), href: '/inkloom/objective/civil-procedure/19/third-party-revocation-remedy-map/', durationInFrames: THIRD_PARTY_REMEDY_DURATION_FRAMES, fps: THIRD_PARTY_REMEDY_FPS},
  {id: 'civil-procedure-20-appeal-review-decision-map', slug: 'appeal-review-decision-map', title: '上诉棱镜编排', direction: 'Appellate Editorial Prism', component: lazyDemo(() => import('../../animations/civil-procedure/20/appeal-review-decision-map/remotion/AppealReviewDecisionMap').then((m) => ({default: m.AppealReviewDecisionMap}))), href: '/inkloom/objective/civil-procedure/20/appeal-review-decision-map/', durationInFrames: APPEAL_REVIEW_DURATION_FRAMES, fps: APPEAL_REVIEW_FPS},
  {id: 'civil-law-contract-book-atlas', slug: 'contract-book-atlas', title: '条文折页', direction: 'Statute Folio', component: lazyDemo(() => import('../../animations/civil-law/contracts/contract-book-atlas/remotion/ContractBookAtlas').then((m) => ({default: m.ContractBookAtlas}))), href: '/inkloom/objective/civil-law/contracts/contract-book-atlas/', durationInFrames: CONTRACT_BOOK_DURATION_FRAMES, fps: CONTRACT_BOOK_FPS},
  {id: 'civil-law-14-security-publicity-fate', slug: 'security-publicity-fate', title: '当铺柜台', direction: 'Pledge Counter Vault', component: lazyDemo(() => import('../../animations/civil-law/14/security-publicity-fate/remotion/SecurityPublicityFate').then((m) => ({default: withAnimationTypography(m.SecurityPublicityFate, getAnimationTypographyConfiguration('security-publicity-fate'))}))), href: '/inkloom/objective/civil-law/14/security-publicity-fate/', durationInFrames: SECURITY_PUBLICITY_DURATION_FRAMES, fps: SECURITY_PUBLICITY_FPS},
  {id: 'civil-law-01-six-principles-pillars', slug: 'six-principles-pillars', title: '柱础厅', direction: 'Granite Pillar Hall', component: lazyDemo(() => import('../../animations/civil-law/01/six-principles-pillars/remotion/SixPrinciplesPillars').then((m) => ({default: withAnimationTypography(m.SixPrinciplesPillars, getAnimationTypographyConfiguration('six-principles-pillars'))}))), href: '/inkloom/objective/civil-law/01/six-principles-pillars/', durationInFrames: SIX_PRINCIPLES_DURATION_FRAMES, fps: SIX_PRINCIPLES_FPS},
  {id: 'civil-procedure-32-penalty-adjustment-procedure', slug: 'penalty-adjustment-procedure', title: '裁判控制台', direction: 'Judicial Control Desk', component: lazyDemo(() => import('../../animations/civil-procedure/32/penalty-adjustment-procedure/remotion/PenaltyAdjustmentProcedure').then((m) => ({default: m.PenaltyAdjustmentProcedure}))), href: '/inkloom/objective/civil-procedure/32/penalty-adjustment-procedure/', durationInFrames: PENALTY_ADJUSTMENT_DURATION_FRAMES, fps: PENALTY_ADJUSTMENT_FPS},
  {id: 'theoretical-law-17-legal-interpretation', slug: 'legal-interpretation', title: '宋式藻井图', direction: 'Song Caisson Paintwork', component: lazyDemo(() => import('../../animations/theoretical-law/17/legal-interpretation/remotion/LegalInterpretation').then((m) => ({default: m.LegalInterpretation}))), href: '/inkloom/objective/theoretical-law/17/legal-interpretation/', durationInFrames: LEGAL_INTERPRETATION_DURATION_FRAMES, fps: LEGAL_INTERPRETATION_FPS},
  {id: 'criminal-procedure-07-evidence-exclusion-lattice', slug: 'evidence-exclusion-lattice', title: '证物分级检验柜', direction: 'Exclusion Grading Lattice', component: lazyDemo(() => import('../../animations/criminal-procedure/07/evidence-exclusion-lattice/remotion/EvidenceExclusionLattice').then((m) => ({default: m.EvidenceExclusionLattice}))), href: '/inkloom/objective/criminal-procedure/07/evidence-exclusion-lattice/', durationInFrames: EVIDENCE_EXCLUSION_DURATION_FRAMES, fps: EVIDENCE_EXCLUSION_FPS},
  {id: 'criminal-procedure-01-procedure-structure-orrery', slug: 'procedure-structure-orrery', title: '黄铜构造星盘', direction: 'Brass Orrery Structure', component: lazyDemo(() => import('../../animations/criminal-procedure/01/procedure-structure-orrery/remotion/ProcedureStructureOrrery').then((m) => ({default: m.ProcedureStructureOrrery}))), href: '/inkloom/objective/criminal-procedure/01/procedure-structure-orrery/', durationInFrames: PROCEDURE_STRUCTURE_DURATION_FRAMES, fps: PROCEDURE_STRUCTURE_FPS},
  {id: 'criminal-procedure-03-organs-relay-map', slug: 'organs-relay-map', title: '青砖驿路图', direction: 'Slate Courier Relay', component: lazyDemo(() => import('../../animations/criminal-procedure/03/organs-relay-map/remotion/OrgansRelayMap').then((m) => ({default: m.OrgansRelayMap}))), href: '/inkloom/objective/criminal-procedure/03/organs-relay-map/', durationInFrames: ORGANS_RELAY_DURATION_FRAMES, fps: ORGANS_RELAY_FPS},
  {id: 'criminal-procedure-04-jurisdiction-sluice-terrace', slug: 'jurisdiction-sluice-terrace', title: '水闸分级渠', direction: 'Sluice Terrace Jurisdiction', component: lazyDemo(() => import('../../animations/criminal-procedure/04/jurisdiction-sluice-terrace/remotion/JurisdictionSluiceTerrace').then((m) => ({default: m.JurisdictionSluiceTerrace}))), href: '/inkloom/objective/criminal-procedure/04/jurisdiction-sluice-terrace/', durationInFrames: JURISDICTION_SLUICE_DURATION_FRAMES, fps: JURISDICTION_SLUICE_FPS},
  {id: 'criminal-procedure-05-recusal-sentry-rotation', slug: 'recusal-sentry-rotation', title: '换防哨位', direction: 'Sentry Rotation Post', component: lazyDemo(() => import('../../animations/criminal-procedure/05/recusal-sentry-rotation/remotion/RecusalSentryRotation').then((m) => ({default: m.RecusalSentryRotation}))), href: '/inkloom/objective/criminal-procedure/05/recusal-sentry-rotation/', durationInFrames: RECUSAL_SENTRY_DURATION_FRAMES, fps: RECUSAL_SENTRY_FPS},
  {id: 'criminal-procedure-06-defense-pilot-harbor', slug: 'defense-pilot-harbor', title: '灯塔引航港', direction: 'Pilot Harbor Defense', component: lazyDemo(() => import('../../animations/criminal-procedure/06/defense-pilot-harbor/remotion/DefensePilotHarbor').then((m) => ({default: m.DefensePilotHarbor}))), href: '/inkloom/objective/criminal-procedure/06/defense-pilot-harbor/', durationInFrames: DEFENSE_PILOT_DURATION_FRAMES, fps: DEFENSE_PILOT_FPS},
  {id: 'criminal-procedure-08-coercion-pressure-ladder', slug: 'coercion-pressure-ladder', title: '锅炉压力梯', direction: 'Boiler Pressure Coercion', component: lazyDemo(() => import('../../animations/criminal-procedure/08/coercion-pressure-ladder/remotion/CoercionPressureLadder').then((m) => ({default: m.CoercionPressureLadder}))), href: '/inkloom/objective/criminal-procedure/08/coercion-pressure-ladder/', durationInFrames: COERCION_LADDER_DURATION_FRAMES, fps: COERCION_LADDER_FPS},
  {id: 'criminal-procedure-09-attached-suit-viaduct', slug: 'attached-suit-viaduct', title: '双轨合流桥', direction: 'Viaduct Merge Attached Suit', component: lazyDemo(() => import('../../animations/criminal-procedure/09/attached-suit-viaduct/remotion/AttachedSuitViaduct').then((m) => ({default: m.AttachedSuitViaduct}))), href: '/inkloom/objective/criminal-procedure/09/attached-suit-viaduct/', durationInFrames: ATTACHED_SUIT_DURATION_FRAMES, fps: ATTACHED_SUIT_FPS},
  {id: 'criminal-procedure-10-period-escapement-works', slug: 'period-escapement-works', title: '机械日历坊', direction: 'Escapement Works Periods', component: lazyDemo(() => import('../../animations/criminal-procedure/10/period-escapement-works/remotion/PeriodEscapementWorks').then((m) => ({default: m.PeriodEscapementWorks}))), href: '/inkloom/objective/criminal-procedure/10/period-escapement-works/', durationInFrames: PERIOD_ESCAPEMENT_DURATION_FRAMES, fps: PERIOD_ESCAPEMENT_FPS},
  {id: 'criminal-procedure-11-case-filing-gatehouse', slug: 'case-filing-gatehouse', title: '闸门登记所', direction: 'Gatehouse Registry Filing', component: lazyDemo(() => import('../../animations/criminal-procedure/11/case-filing-gatehouse/remotion/CaseFilingGatehouse').then((m) => ({default: m.CaseFilingGatehouse}))), href: '/inkloom/objective/criminal-procedure/11/case-filing-gatehouse/', durationInFrames: FILING_GATEHOUSE_DURATION_FRAMES, fps: FILING_GATEHOUSE_FPS},
  {id: 'criminal-procedure-12-supplement-invest-loop', slug: 'supplement-invest-loop', title: '回旋检验环', direction: 'Inspection Loop Supplement', component: lazyDemo(() => import('../../animations/criminal-procedure/12/supplement-invest-loop/remotion/SupplementInvestLoop').then((m) => ({default: m.SupplementInvestLoop}))), href: '/inkloom/objective/criminal-procedure/12/supplement-invest-loop/', durationInFrames: SUPPLEMENT_LOOP_DURATION_FRAMES, fps: SUPPLEMENT_LOOP_FPS},
  {id: 'criminal-procedure-13-nonprosecution-signal-tower', slug: 'nonprosecution-signal-tower', title: '四向信号塔', direction: 'Signal Tower Nonprosecution', component: lazyDemo(() => import('../../animations/criminal-procedure/13/nonprosecution-signal-tower/remotion/NonprosecutionSignalTower').then((m) => ({default: m.NonprosecutionSignalTower}))), href: '/inkloom/objective/criminal-procedure/13/nonprosecution-signal-tower/', durationInFrames: NONPROSECUTION_TOWER_DURATION_FRAMES, fps: NONPROSECUTION_TOWER_FPS},
  {id: 'criminal-procedure-14-trial-bench-composition', slug: 'trial-bench-composition', title: '席位拼合台', direction: 'Bench Assembly Trial Organs', component: lazyDemo(() => import('../../animations/criminal-procedure/14/trial-bench-composition/remotion/TrialBenchComposition').then((m) => ({default: m.TrialBenchComposition}))), href: '/inkloom/objective/criminal-procedure/14/trial-bench-composition/', durationInFrames: TRIAL_BENCH_DURATION_FRAMES, fps: TRIAL_BENCH_FPS},
  {id: 'criminal-procedure-15-first-instance-procession', slug: 'first-instance-procession', title: '流水街', direction: 'Procession Street First Instance', component: lazyDemo(() => import('../../animations/criminal-procedure/15/first-instance-procession/remotion/FirstInstanceProcession').then((m) => ({default: m.FirstInstanceProcession}))), href: '/inkloom/objective/criminal-procedure/15/first-instance-procession/', durationInFrames: FIRST_INSTANCE_DURATION_FRAMES, fps: FIRST_INSTANCE_FPS},
  {id: 'criminal-procedure-16-appeal-no-escalation-lock', slug: 'appeal-no-escalation-lock', title: '单行闸桥', direction: 'One-Way Lock Appeal', component: lazyDemo(() => import('../../animations/criminal-procedure/16/appeal-no-escalation-lock/remotion/AppealNoEscalationLock').then((m) => ({default: m.AppealNoEscalationLock}))), href: '/inkloom/objective/criminal-procedure/16/appeal-no-escalation-lock/', durationInFrames: APPEAL_LOCK_DURATION_FRAMES, fps: APPEAL_LOCK_FPS},
  {id: 'criminal-procedure-18-retrial-rewind-loom', slug: 'retrial-rewind-loom', title: '织机回纬', direction: 'Rewind Loom Retrial', component: lazyDemo(() => import('../../animations/criminal-procedure/18/retrial-rewind-loom/remotion/RetrialRewindLoom').then((m) => ({default: m.RetrialRewindLoom}))), href: '/inkloom/objective/criminal-procedure/18/retrial-rewind-loom/', durationInFrames: RETRAL_LOOM_DURATION_FRAMES, fps: RETRAL_LOOM_FPS},
  {id: 'criminal-procedure-19-execution-dispatch-board', slug: 'execution-dispatch-board', title: '交付调度台', direction: 'Dispatch Board Execution', component: lazyDemo(() => import('../../animations/criminal-procedure/19/execution-dispatch-board/remotion/ExecutionDispatchBoard').then((m) => ({default: m.ExecutionDispatchBoard}))), href: '/inkloom/objective/criminal-procedure/19/execution-dispatch-board/', durationInFrames: EXECUTION_DISPATCH_DURATION_FRAMES, fps: EXECUTION_DISPATCH_FPS},
  {id: 'criminal-procedure-20-juvenile-observatory-greenhouse', slug: 'juvenile-observatory-greenhouse', title: '观护温室', direction: 'Observatory Greenhouse Juvenile', component: lazyDemo(() => import('../../animations/criminal-procedure/20/juvenile-observatory-greenhouse/remotion/JuvenileObservatoryGreenhouse').then((m) => ({default: m.JuvenileObservatoryGreenhouse}))), href: '/inkloom/objective/criminal-procedure/20/juvenile-observatory-greenhouse/', durationInFrames: JUVENILE_GREENHOUSE_DURATION_FRAMES, fps: JUVENILE_GREENHOUSE_FPS},
  {id: 'criminal-procedure-17-death-review-summit', slug: 'death-review-summit', title: '峰顶复审营', direction: 'Summit Camp Death Review', component: lazyDemo(() => import('../../animations/criminal-procedure/17/death-review-summit/remotion/DeathReviewSummit').then((m) => ({default: m.DeathReviewSummit}))), href: '/inkloom/objective/criminal-procedure/17/death-review-summit/', durationInFrames: DEATH_REVIEW_DURATION_FRAMES, fps: DEATH_REVIEW_FPS},
  {id: 'criminal-procedure-02-plea-leniency-caliper', slug: 'plea-leniency-caliper', title: '认罚量尺工坊', direction: 'Maple Caliper Workshop', component: lazyDemo(() => import('../../animations/criminal-procedure/02/plea-leniency-caliper/remotion/PleaLeniencyCaliper').then((m) => ({default: m.PleaLeniencyCaliper}))), href: '/inkloom/objective/criminal-procedure/02/plea-leniency-caliper/', durationInFrames: PLEA_LENIENTY_DURATION_FRAMES, fps: PLEA_LENIENTY_FPS},
  {id: 'theoretical-law-01-concept-of-law-dispute', slug: 'concept-of-law-dispute', title: '漆屏对峙', direction: 'Lacquer Twin-Screen', component: lazyDemo(() => import('../../animations/theoretical-law/01/concept-of-law-dispute/remotion/ConceptOfLawDispute').then((m) => ({default: m.ConceptOfLawDispute}))), href: '/inkloom/objective/theoretical-law/01/concept-of-law-dispute/', durationInFrames: CONCEPT_OF_LAW_DURATION_FRAMES, fps: CONCEPT_OF_LAW_FPS},
  {id: 'international-law-01-sources-of-international-law', slug: 'sources-of-international-law', title: '外交条约卷册', direction: 'Diplomatic Treaty Folio', component: lazyDemo(() => import('../../animations/international-law/01/sources-of-international-law/remotion/SourcesOfInternationalLaw').then((m) => ({default: withAnimationTypography(m.SourcesOfInternationalLaw, getAnimationTypographyConfiguration('sources-of-international-law'))}))), href: '/inkloom/objective/international-law/01/sources-of-international-law/', durationInFrames: SOURCES_INTERNATIONAL_LAW_DURATION_FRAMES, fps: SOURCES_INTERNATIONAL_LAW_FPS},
  {id: 'international-law-02-subjects-responsibility', slug: 'subjects-responsibility', title: '外交议事厅', direction: 'Envoy Assembly Chamber', component: lazyDemo(() => import('../../animations/international-law/02/subjects-responsibility/remotion/SubjectsResponsibility').then((m) => ({default: withAnimationTypography(m.SubjectsResponsibility, getAnimationTypographyConfiguration('subjects-responsibility'))}))), href: '/inkloom/objective/international-law/02/subjects-responsibility/', durationInFrames: SUBJECTS_RESPONSIBILITY_DURATION_FRAMES, fps: SUBJECTS_RESPONSIBILITY_FPS},
  {id: 'international-law-03-spatial-regimes', slug: 'spatial-regimes', title: '海图测绘室', direction: 'Nautical Survey Chart', component: lazyDemo(() => import('../../animations/international-law/03/spatial-regimes/remotion/SpatialRegimes').then((m) => ({default: withAnimationTypography(m.SpatialRegimes, getAnimationTypographyConfiguration('spatial-regimes'))}))), href: '/inkloom/objective/international-law/03/spatial-regimes/', durationInFrames: SPATIAL_REGIMES_DURATION_FRAMES, fps: SPATIAL_REGIMES_FPS},
  {id: 'international-law-04-individuals-regimes', slug: 'individuals-regimes', title: '户籍登记所', direction: 'Civil Registry Ledger', component: lazyDemo(() => import('../../animations/international-law/04/individuals-regimes/remotion/IndividualsRegimes').then((m) => ({default: withAnimationTypography(m.IndividualsRegimes, getAnimationTypographyConfiguration('individuals-regimes'))}))), href: '/inkloom/objective/international-law/04/individuals-regimes/', durationInFrames: INDIVIDUALS_REGIMES_DURATION_FRAMES, fps: INDIVIDUALS_REGIMES_FPS},
  {id: 'international-law-05-diplomatic-consular', slug: 'diplomatic-consular', title: '鸢尾紫章', direction: 'Iris Violet Chancery', component: lazyDemo(() => import('../../animations/international-law/05/diplomatic-consular/remotion/DiplomaticConsular').then((m) => ({default: withAnimationTypography(m.DiplomaticConsular, getAnimationTypographyConfiguration('diplomatic-consular'))}))), href: '/inkloom/objective/international-law/05/diplomatic-consular/', durationInFrames: DIPLOMATIC_CONSULAR_DURATION_FRAMES, fps: DIPLOMATIC_CONSULAR_FPS},
  {id: 'international-law-06-law-of-treaties', slug: 'law-of-treaties', title: '钢蓝墨水条约案', direction: 'Steel-Ink Treaty Desk', component: lazyDemo(() => import('../../animations/international-law/06/law-of-treaties/remotion/LawOfTreaties').then((m) => ({default: withAnimationTypography(m.LawOfTreaties, getAnimationTypographyConfiguration('law-of-treaties'))}))), href: '/inkloom/objective/international-law/06/law-of-treaties/', durationInFrames: LAW_OF_TREATIES_DURATION_FRAMES, fps: LAW_OF_TREATIES_FPS},
  {id: 'international-law-07-dispute-settlement', slug: 'dispute-settlement', title: '和平宫仲裁席', direction: 'Peace Palace Bench', component: lazyDemo(() => import('../../animations/international-law/07/dispute-settlement/remotion/DisputeSettlement').then((m) => ({default: withAnimationTypography(m.DisputeSettlement, getAnimationTypographyConfiguration('dispute-settlement'))}))), href: '/inkloom/objective/international-law/07/dispute-settlement/', durationInFrames: DISPUTE_SETTLEMENT_DURATION_FRAMES, fps: DISPUTE_SETTLEMENT_FPS},
  {id: 'international-law-08-war-armed-conflict', slug: 'war-armed-conflict', title: '战地公报台', direction: 'Field Bulletin Desk', component: lazyDemo(() => import('../../animations/international-law/08/war-armed-conflict/remotion/WarArmedConflict').then((m) => ({default: withAnimationTypography(m.WarArmedConflict, getAnimationTypographyConfiguration('war-armed-conflict'))}))), href: '/inkloom/objective/international-law/08/war-armed-conflict/', durationInFrames: WAR_ARMED_CONFLICT_DURATION_FRAMES, fps: WAR_ARMED_CONFLICT_FPS},
  {id: 'international-law-09-cross-border-disputes', slug: 'cross-border-disputes', title: '珊瑚港事厅', direction: 'Coral Harbor Exchange', component: lazyDemo(() => import('../../animations/international-law/09/cross-border-disputes/remotion/CrossBorderDisputes').then((m) => ({default: withAnimationTypography(m.CrossBorderDisputes, getAnimationTypographyConfiguration('cross-border-disputes'))}))), href: '/inkloom/objective/international-law/09/cross-border-disputes/', durationInFrames: CROSS_BORDER_DISPUTES_DURATION_FRAMES, fps: CROSS_BORDER_DISPUTES_FPS},
  {id: 'international-law-10-conflict-of-laws-rules', slug: 'conflict-of-laws-rules', title: '紫檀罗盘局', direction: 'Aubergine Routing Board', component: lazyDemo(() => import('../../animations/international-law/10/conflict-of-laws-rules/remotion/ConflictOfLawsRules').then((m) => ({default: withAnimationTypography(m.ConflictOfLawsRules, getAnimationTypographyConfiguration('conflict-of-laws-rules'))}))), href: '/inkloom/objective/international-law/10/conflict-of-laws-rules/', durationInFrames: CONFLICT_OF_LAWS_DURATION_FRAMES, fps: CONFLICT_OF_LAWS_FPS},
  {id: 'international-law-11-applicable-law', slug: 'applicable-law', title: '翡翠台账馆', direction: 'Emerald Ledger Hall', component: lazyDemo(() => import('../../animations/international-law/11/applicable-law/remotion/ApplicableLaw').then((m) => ({default: withAnimationTypography(m.ApplicableLaw, getAnimationTypographyConfiguration('applicable-law'))}))), href: '/inkloom/objective/international-law/11/applicable-law/', durationInFrames: APPLICABLE_LAW_DURATION_FRAMES, fps: APPLICABLE_LAW_FPS},
  {id: 'international-law-13-interregional-assistance', slug: 'interregional-assistance', title: '夜航显示牌', direction: 'Night Split-Flap Board', component: lazyDemo(() => import('../../animations/international-law/13/interregional-assistance/remotion/InterregionalAssistance').then((m) => ({default: withAnimationTypography(m.InterregionalAssistance, getAnimationTypographyConfiguration('interregional-assistance'))}))), href: '/inkloom/objective/international-law/13/interregional-assistance/', durationInFrames: INTERREGIONAL_DURATION_FRAMES, fps: INTERREGIONAL_FPS},
  {id: 'international-law-18-wto', slug: 'wto', title: '青瓷圆桌会', direction: 'Celadon Roundtable', component: lazyDemo(() => import('../../animations/international-law/18/wto/remotion/Wto').then((m) => ({default: withAnimationTypography(m.Wto, getAnimationTypographyConfiguration('wto'))}))), href: '/inkloom/objective/international-law/18/wto/', durationInFrames: WTO_DURATION_FRAMES, fps: WTO_FPS},
  {id: 'international-law-15-goods-transport-insurance', slug: 'goods-transport-insurance', title: '酒红提单台', direction: 'Burgundy Lading Desk', component: lazyDemo(() => import('../../animations/international-law/15/goods-transport-insurance/remotion/GoodsTransportInsurance').then((m) => ({default: withAnimationTypography(m.GoodsTransportInsurance, getAnimationTypographyConfiguration('goods-transport-insurance'))}))), href: '/inkloom/objective/international-law/15/goods-transport-insurance/', durationInFrames: TRANSPORT_INS_DURATION_FRAMES, fps: TRANSPORT_INS_FPS},
  {id: 'international-law-12-extraterritorial-assistance', slug: 'extraterritorial-assistance', title: '深夜邮传局', direction: 'Midnight Mail Relay', component: lazyDemo(() => import('../../animations/international-law/12/extraterritorial-assistance/remotion/ExtraterritorialAssistance').then((m) => ({default: withAnimationTypography(m.ExtraterritorialAssistance, getAnimationTypographyConfiguration('extraterritorial-assistance'))}))), href: '/inkloom/objective/international-law/12/extraterritorial-assistance/', durationInFrames: EXTRATERRITORIAL_ASSISTANCE_DURATION_FRAMES, fps: EXTRATERRITORIAL_ASSISTANCE_FPS},
  {id: 'international-law-14-international-sale-of-goods', slug: 'international-sale-of-goods', title: '混凝土码头调度板', direction: 'Concrete Quay Dispatch', component: lazyDemo(() => import('../../animations/international-law/14/international-sale-of-goods/remotion/InternationalSaleOfGoods').then((m) => ({default: withAnimationTypography(m.InternationalSaleOfGoods, getAnimationTypographyConfiguration('international-sale-of-goods'))}))), href: '/inkloom/objective/international-law/14/international-sale-of-goods/', durationInFrames: INTERNATIONAL_SALE_OF_GOODS_DURATION_FRAMES, fps: INTERNATIONAL_SALE_OF_GOODS_FPS},
  {id: 'international-law-16-international-trade-payment', slug: 'international-trade-payment', title: '勃艮第汇票行', direction: 'Oxblood Draft House', component: lazyDemo(() => import('../../animations/international-law/16/international-trade-payment/remotion/InternationalTradePayment').then((m) => ({default: withAnimationTypography(m.InternationalTradePayment, getAnimationTypographyConfiguration('international-trade-payment'))}))), href: '/inkloom/objective/international-law/16/international-trade-payment/', durationInFrames: INTERNATIONAL_TRADE_PAYMENT_DURATION_FRAMES, fps: INTERNATIONAL_TRADE_PAYMENT_FPS},
  {id: 'international-law-17-foreign-trade-administration', slug: 'foreign-trade-administration', title: '敦煌矿彩关牍', direction: 'Dunhuang Mineral Bulletin', component: lazyDemo(() => import('../../animations/international-law/17/foreign-trade-administration/remotion/ForeignTradeAdministration').then((m) => ({default: withAnimationTypography(m.ForeignTradeAdministration, getAnimationTypographyConfiguration('foreign-trade-administration'))}))), href: '/inkloom/objective/international-law/17/foreign-trade-administration/', durationInFrames: FOREIGN_TRADE_ADMINISTRATION_DURATION_FRAMES, fps: FOREIGN_TRADE_ADMINISTRATION_FPS},
  {id: 'international-law-19-other-regimes-international-economic-law', slug: 'other-regimes-international-economic-law', title: '青瓷公约馆', direction: 'Celadon Convention Gallery', component: lazyDemo(() => import('../../animations/international-law/19/other-regimes-international-economic-law/remotion/OtherRegimesInternationalEconomicLaw').then((m) => ({default: withAnimationTypography(m.OtherRegimesInternationalEconomicLaw, getAnimationTypographyConfiguration('other-regimes-international-economic-law'))}))), href: '/inkloom/objective/international-law/19/other-regimes-international-economic-law/', durationInFrames: OTHER_REGIMES_INTL_ECON_DURATION_FRAMES, fps: OTHER_REGIMES_INTL_ECON_FPS},
  {id: 'theoretical-law-01-marxist-law-essence', slug: 'marxist-law-essence', title: '蓝晒制图', direction: 'Cyanotype Drafting', component: lazyDemo(() => import('../../animations/theoretical-law/01/marxist-law-essence/remotion/MarxistLawEssence').then((m) => ({default: m.MarxistLawEssence}))), href: '/inkloom/objective/theoretical-law/01/marxist-law-essence/', durationInFrames: MARXIST_LAW_DURATION_FRAMES, fps: MARXIST_LAW_FPS},
  {id: 'theoretical-law-01-features-of-law', slug: 'features-of-law', title: '标本陈列柜', direction: 'Specimen Gallery Cabinet', component: lazyDemo(() => import('../../animations/theoretical-law/01/features-of-law/remotion/FeaturesOfLaw').then((m) => ({default: m.FeaturesOfLaw}))), href: '/inkloom/objective/theoretical-law/01/features-of-law/', durationInFrames: FEATURES_OF_LAW_DURATION_FRAMES, fps: FEATURES_OF_LAW_FPS},
  {id: 'theoretical-law-01-functions-of-law', slug: 'functions-of-law', title: '灯塔信号站', direction: 'Night Beacon Station', component: lazyDemo(() => import('../../animations/theoretical-law/01/functions-of-law/remotion/FunctionsOfLaw').then((m) => ({default: m.FunctionsOfLaw}))), href: '/inkloom/objective/theoretical-law/01/functions-of-law/', durationInFrames: FUNCTIONS_OF_LAW_DURATION_FRAMES, fps: FUNCTIONS_OF_LAW_FPS},
  {id: 'theoretical-law-01-limitations-of-law', slug: 'limitations-of-law', title: '警戒界桩', direction: 'Hazard Boundary Post', component: lazyDemo(() => import('../../animations/theoretical-law/01/limitations-of-law/remotion/LimitationsOfLaw').then((m) => ({default: m.LimitationsOfLaw}))), href: '/inkloom/objective/theoretical-law/01/limitations-of-law/', durationInFrames: LIMITATIONS_OF_LAW_DURATION_FRAMES, fps: LIMITATIONS_OF_LAW_FPS},
  {id: 'theoretical-law-01-value-conflict', slug: 'value-conflict', title: '金底嵌画', direction: 'Gold-Ground Mosaic', component: lazyDemo(() => import('../../animations/theoretical-law/01/value-conflict/remotion/ValueConflict').then((m) => ({default: m.ValueConflict}))), href: '/inkloom/objective/theoretical-law/01/value-conflict/', durationInFrames: VALUE_CONFLICT_DURATION_FRAMES, fps: VALUE_CONFLICT_FPS},
  {id: 'theoretical-law-01-legal-rules', slug: 'legal-rules', title: '红蓝账本', direction: 'Red-Blue Ledger', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-rules/remotion/LegalRules').then((m) => ({default: m.LegalRules}))), href: '/inkloom/objective/theoretical-law/01/legal-rules/', durationInFrames: LEGAL_RULES_DURATION_FRAMES, fps: LEGAL_RULES_FPS},
  {id: 'theoretical-law-01-legal-principles', slug: 'legal-principles', title: '黑板讲席', direction: 'Chalkboard Lecture', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-principles/remotion/LegalPrinciples').then((m) => ({default: m.LegalPrinciples}))), href: '/inkloom/objective/theoretical-law/01/legal-principles/', durationInFrames: LEGAL_PRINCIPLES_DURATION_FRAMES, fps: LEGAL_PRINCIPLES_FPS},
  {id: 'theoretical-law-01-sources-of-law', slug: 'sources-of-law', title: '碑林拓片', direction: 'Stele Forest Rubbing', component: lazyDemo(() => import('../../animations/theoretical-law/01/sources-of-law/remotion/SourcesOfLaw').then((m) => ({default: m.SourcesOfLaw}))), href: '/inkloom/objective/theoretical-law/01/sources-of-law/', durationInFrames: SOURCES_OF_LAW_DURATION_FRAMES, fps: SOURCES_OF_LAW_FPS},
  {id: 'theoretical-law-01-legal-departments-system', slug: 'legal-departments-system', title: '经纬织坊', direction: 'Weaving Loom Atelier', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-departments-system/remotion/LegalDepartmentsSystem').then((m) => ({default: m.LegalDepartmentsSystem}))), href: '/inkloom/objective/theoretical-law/01/legal-departments-system/', durationInFrames: LEGAL_DEPARTMENTS_SYSTEM_DURATION_FRAMES, fps: LEGAL_DEPARTMENTS_SYSTEM_FPS},
  {id: 'theoretical-law-01-legal-validity', slug: 'legal-validity', title: '验讫关防', direction: 'Frontier Pass Office', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-validity/remotion/LegalValidity').then((m) => ({default: m.LegalValidity}))), href: '/inkloom/objective/theoretical-law/01/legal-validity/', durationInFrames: LEGAL_VALIDITY_DURATION_FRAMES, fps: LEGAL_VALIDITY_FPS},
  {id: 'theoretical-law-01-legal-relations', slug: 'legal-relations', title: '青花瓷档', direction: 'Cobalt Porcelain Registry', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-relations/remotion/LegalRelations').then((m) => ({default: m.LegalRelations}))), href: '/inkloom/objective/theoretical-law/01/legal-relations/', durationInFrames: LEGAL_RELATIONS_DURATION_FRAMES, fps: LEGAL_RELATIONS_FPS},
  {id: 'theoretical-law-01-liability-concurrence', slug: 'liability-concurrence', title: '双叉共鸣台', direction: 'Tuning Fork Resonance Bench', component: lazyDemo(() => import('../../animations/theoretical-law/01/liability-concurrence/remotion/LiabilityConcurrence').then((m) => ({default: m.LiabilityConcurrence}))), href: '/inkloom/objective/theoretical-law/01/liability-concurrence/', durationInFrames: LIABILITY_CONCURRENCE_DURATION_FRAMES, fps: LIABILITY_CONCURRENCE_FPS},
  {id: 'theoretical-law-01-judicial-vs-administrative', slug: 'judicial-vs-administrative', title: '对席案牍', direction: 'Paired Desk Hall', component: lazyDemo(() => import('../../animations/theoretical-law/01/judicial-vs-administrative/remotion/JudicialVsAdministrative').then((m) => ({default: m.JudicialVsAdministrative}))), href: '/inkloom/objective/theoretical-law/01/judicial-vs-administrative/', durationInFrames: JUDICIAL_VS_ADMINISTRATIVE_DURATION_FRAMES, fps: JUDICIAL_VS_ADMINISTRATIVE_FPS},
  {id: 'theoretical-law-01-application-of-law', slug: 'application-of-law', title: '绳墨规矩', direction: 'Ink Line Rule Workshop', component: lazyDemo(() => import('../../animations/theoretical-law/01/application-of-law/remotion/ApplicationOfLaw').then((m) => ({default: m.ApplicationOfLaw}))), href: '/inkloom/objective/theoretical-law/01/application-of-law/', durationInFrames: APPLICATION_OF_LAW_DURATION_FRAMES, fps: APPLICATION_OF_LAW_FPS},
  {id: 'theoretical-law-01-legal-loopholes', slug: 'legal-loopholes', title: '补阙裱工', direction: 'Mending Press Workshop', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-loopholes/remotion/LegalLoopholes').then((m) => ({default: m.LegalLoopholes}))), href: '/inkloom/objective/theoretical-law/01/legal-loopholes/', durationInFrames: LEGAL_LOOPHOLES_DURATION_FRAMES, fps: LEGAL_LOOPHOLES_FPS},
  {id: 'theoretical-law-01-legal-reasoning', slug: 'legal-reasoning', title: '测天星盘', direction: 'Astrolabe Night Observatory', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-reasoning/remotion/LegalReasoning').then((m) => ({default: m.LegalReasoning}))), href: '/inkloom/objective/theoretical-law/01/legal-reasoning/', durationInFrames: LEGAL_REASONING_DURATION_FRAMES, fps: LEGAL_REASONING_FPS},
  {id: 'theoretical-law-01-legal-families', slug: 'legal-families', title: '胡桃对厅', direction: 'Walnut Comparison Hall', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-families/remotion/LegalFamilies').then((m) => ({default: m.LegalFamilies}))), href: '/inkloom/objective/theoretical-law/01/legal-families/', durationInFrames: LEGAL_FAMILIES_DURATION_FRAMES, fps: LEGAL_FAMILIES_FPS},
  {id: 'theoretical-law-01-legal-modernization', slug: 'legal-modernization', title: '嫁接苗圃', direction: 'Botanical Graft Nursery', component: lazyDemo(() => import('../../animations/theoretical-law/01/legal-modernization/remotion/LegalModernization').then((m) => ({default: m.LegalModernization}))), href: '/inkloom/objective/theoretical-law/01/legal-modernization/', durationInFrames: LEGAL_MODERNIZATION_DURATION_FRAMES, fps: LEGAL_MODERNIZATION_FPS},
  {id: 'theoretical-law-01-law-and-morality', slug: 'law-and-morality', title: '双秤量铺', direction: 'Twin Balance Scale Hall', component: lazyDemo(() => import('../../animations/theoretical-law/01/law-and-morality/remotion/LawAndMorality').then((m) => ({default: m.LawAndMorality}))), href: '/inkloom/objective/theoretical-law/01/law-and-morality/', durationInFrames: LAW_AND_MORALITY_DURATION_FRAMES, fps: LAW_AND_MORALITY_FPS},
  {id: 'theoretical-law-01-law-and-human-rights', slug: 'law-and-human-rights', title: '生而秉炬', direction: 'Candle Flame Gallery', component: lazyDemo(() => import('../../animations/theoretical-law/01/law-and-human-rights/remotion/LawAndHumanRights').then((m) => ({default: m.LawAndHumanRights}))), href: '/inkloom/objective/theoretical-law/01/law-and-human-rights/', durationInFrames: LAW_AND_HUMAN_RIGHTS_DURATION_FRAMES, fps: LAW_AND_HUMAN_RIGHTS_FPS},
  {id: 'theoretical-law-01-legislation-law', slug: 'legislation-law', title: '法典铸坊', direction: 'Code Forge Foundry', component: lazyDemo(() => import('../../animations/theoretical-law/01/legislation-law/remotion/LegislationLaw').then((m) => ({default: m.LegislationLaw}))), href: '/inkloom/objective/theoretical-law/01/legislation-law/', durationInFrames: LEGISLATION_LAW_DURATION_FRAMES, fps: LEGISLATION_LAW_FPS},
  {id: 'theoretical-law-01-features-of-constitution', slug: 'features-of-constitution', title: '奠基石台', direction: 'Cornerstone Terrace Workshop', component: lazyDemo(() => import('../../animations/theoretical-law/01/features-of-constitution/remotion/FeaturesOfConstitution').then((m) => ({default: m.FeaturesOfConstitution}))), href: '/inkloom/objective/theoretical-law/01/features-of-constitution/', durationInFrames: FEATURES_OF_CONSTITUTION_DURATION_FRAMES, fps: FEATURES_OF_CONSTITUTION_FPS},
  {id: 'theoretical-law-01-creation-of-constitution', slug: 'creation-of-constitution', title: '铸宪铜版', direction: 'Bronze Engraving Atelier', component: lazyDemo(() => import('../../animations/theoretical-law/01/creation-of-constitution/remotion/CreationOfConstitution').then((m) => ({default: m.CreationOfConstitution}))), href: '/inkloom/objective/theoretical-law/01/creation-of-constitution/', durationInFrames: CREATION_OF_CONSTITUTION_DURATION_FRAMES, fps: CREATION_OF_CONSTITUTION_FPS},
  {id: 'theoretical-law-01-constitution-classification', slug: 'constitution-classification', title: '编年档案屉', direction: 'Chronicle Archive Drawer', component: lazyDemo(() => import('../../animations/theoretical-law/01/constitution-classification/remotion/ConstitutionClassification').then((m) => ({default: m.ConstitutionClassification}))), href: '/inkloom/objective/theoretical-law/01/constitution-classification/', durationInFrames: CONSTITUTION_CLASSIFICATION_DURATION_FRAMES, fps: CONSTITUTION_CLASSIFICATION_FPS},
  {id: 'commercial-economic-law-01-profit-reserve-granary', slug: 'profit-reserve-granary', title: '丰廒粮栈', direction: 'Granary Harvest Reserve Hall', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/profit-reserve-granary/remotion/ProfitReserveGranary').then((m) => ({default: m.ProfitReserveGranary}))), href: '/inkloom/objective/commercial-economic-law/01/profit-reserve-granary/', durationInFrames: RESERVE_GRANARY_DURATION_FRAMES, fps: RESERVE_GRANARY_FPS},
  {id: 'commercial-economic-law-01-promoter-liability-ropewalk', slug: 'promoter-liability-ropewalk', title: '合股缆棚', direction: 'Indigo Ropewalk Shed', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/promoter-liability-ropewalk/remotion/PromoterLiabilityRopewalk').then((m) => ({default: m.PromoterLiabilityRopewalk}))), href: '/inkloom/objective/commercial-economic-law/01/promoter-liability-ropewalk/', durationInFrames: PROMOTER_ROPEWALK_DURATION_FRAMES, fps: PROMOTER_ROPEWALK_FPS},
  {id: 'commercial-economic-law-01-shareholder-register-pigeonhole', slug: 'shareholder-register-pigeonhole', title: '铜格登记廊', direction: 'Brass Pigeonhole Registry', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/shareholder-register-pigeonhole/remotion/ShareholderRegisterPigeonhole').then((m) => ({default: m.ShareholderRegisterPigeonhole}))), href: '/inkloom/objective/commercial-economic-law/01/shareholder-register-pigeonhole/', durationInFrames: REGISTER_PIGEONHOLE_DURATION_FRAMES, fps: REGISTER_PIGEONHOLE_FPS},
  {id: 'commercial-economic-law-01-nominee-impersonation-masks', slug: 'nominee-impersonation-masks', title: '朱漆脸谱箱', direction: 'Crimson Opera Mask Trunk', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/nominee-impersonation-masks/remotion/NomineeImpersonationMasks').then((m) => ({default: m.NomineeImpersonationMasks}))), href: '/inkloom/objective/commercial-economic-law/01/nominee-impersonation-masks/', durationInFrames: NOMINEE_MASKS_DURATION_FRAMES, fps: NOMINEE_MASKS_FPS},
  {id: 'commercial-economic-law-01-contribution-defect-audit', slug: 'contribution-defect-audit', title: '墨斗验讫坊', direction: 'Inkline Inspection Bench', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/contribution-defect-audit/remotion/ContributionDefectAudit').then((m) => ({default: m.ContributionDefectAudit}))), href: '/inkloom/objective/commercial-economic-law/01/contribution-defect-audit/', durationInFrames: DEFECT_AUDIT_DURATION_FRAMES, fps: DEFECT_AUDIT_FPS},
  {id: 'commercial-economic-law-01-company-guaranty-seal-desk', slug: 'company-guaranty-seal-desk', title: '靛印保状铺', direction: 'Indigo Seal-Paste Cabinet', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/company-guaranty-seal-desk/remotion/CompanyGuarantySealDesk').then((m) => ({default: m.CompanyGuarantySealDesk}))), href: '/inkloom/objective/commercial-economic-law/01/company-guaranty-seal-desk/', durationInFrames: GUARANTY_DESK_DURATION_FRAMES, fps: GUARANTY_DESK_FPS},
  {id: 'commercial-economic-law-01-capital-regime-vote-hall', slug: 'capital-regime-vote-hall', title: '宣纸票匦堂', direction: 'Xuan-Paper Vote Urn Hall', component: lazyDemo(() => import('../../animations/commercial-economic-law/01/capital-regime-vote-hall/remotion/CapitalRegimeVoteHall').then((m) => ({default: m.CapitalRegimeVoteHall}))), href: '/inkloom/objective/commercial-economic-law/01/capital-regime-vote-hall/', durationInFrames: CAPITAL_REGIME_DURATION_FRAMES, fps: CAPITAL_REGIME_FPS},
  ...COMMERCIAL_LAW_STYLE_DEMOS,
] as const satisfies readonly DemoDefinition[];

const DEMO_ADDED_AT: Record<(typeof STYLE_DEMOS)[number]['id'], string> = {
  ...ADMINISTRATIVE_LAW_DEMO_ADDED_AT,
  'demo-courtroom-blueprint': '2026-08-01T21:16:23+08:00',
  'demo-archival-dossier': '2026-08-01T21:16:23+08:00',
  'demo-newspaper-editorial': '2026-08-01T21:16:23+08:00',
  'demo-constructivist-geometry': '2026-08-01T21:16:23+08:00',
  'demo-ink-annotation': '2026-08-01T21:16:23+08:00',
  'demo-evidence-board': '2026-08-01T21:16:23+08:00',
  'demo-isometric-mechanism': '2026-08-01T21:16:23+08:00',
  'demo-timeline-chronicle': '2026-08-01T21:16:23+08:00',
  'demo-statute-commentary': '2026-08-01T21:16:23+08:00',
  'demo-decision-tree': '2026-08-01T21:16:23+08:00',
  'demo-rights-matrix': '2026-08-01T21:16:23+08:00',
  'demo-kinetic-typography': '2026-08-01T21:16:23+08:00',
  'demo-split-screen-comparison': '2026-08-01T21:16:23+08:00',
  'demo-transit-map': '2026-08-01T21:16:23+08:00',
  'civil-procedure-06-joint-litigation': '2026-08-01T16:28:59+08:00',
  'civil-procedure-06-representative-litigation': '2026-08-01T16:28:59+08:00',
  'civil-procedure-07-third-party-types': '2026-08-01T01:33:30+08:00',
  'civil-procedure-07-third-party-revocation': '2026-08-01T01:33:30+08:00',
  'civil-procedure-08-statutory-agent': '2026-08-01T15:50:28+08:00',
  'civil-procedure-08-delegated-agent': '2026-08-01T01:33:30+08:00',
  'civil-procedure-09-admission-court-record': '2026-08-01T18:28:17+08:00',
  'civil-procedure-09-burden-of-proof-steps': '2026-08-01T18:28:17+08:00',
  'civil-procedure-09-burden-of-proof-caveats': '2026-08-03T16:35:43+08:00',
  'civil-procedure-10-evidence-classification': '2026-08-01T21:35:59+08:00',
  'civil-procedure-10-documentary-evidence-rules': '2026-08-01T21:35:59+08:00',
  'civil-procedure-11-evidence-preservation': '2026-08-01T22:16:39+08:00',
  'civil-procedure-11-proof-filing-investigation': '2026-08-01T22:16:39+08:00',
  'civil-procedure-11-surprise-judgment-focus': '2026-08-01T22:16:39+08:00',
  'civil-procedure-11-evidence-review': '2026-08-01T22:16:39+08:00',
  'civil-procedure-12-preservation-stage-map': '2026-08-02T14:19:56+08:00',
  'civil-procedure-12-pre-suit-preservation-transfer': '2026-08-02T14:19:56+08:00',
  'civil-procedure-12-preservation-asset-measures': '2026-08-02T14:19:56+08:00',
  'civil-procedure-12-preservation-remedy-switchboard': '2026-08-02T14:19:56+08:00',
  'civil-procedure-12-provisional-execution-gates': '2026-08-02T14:19:56+08:00',
  'civil-procedure-12-provisional-execution-resolution': '2026-08-02T14:19:56+08:00',
  'civil-procedure-12-behavior-preservation': '2026-08-03T19:18:55+08:00',
  'civil-procedure-14-period-calculation': '2026-08-03T19:18:55+08:00',
  'civil-procedure-14-service-delivery-network': '2026-08-03T19:18:55+08:00',
  'criminal-22-fight-defense-diagram': '2026-08-01T22:16:39+08:00',
  'commercial-economic-law-01-branch-wallet-ledger': '2026-08-30T21:00:00+08:00',
  'commercial-economic-law-01-veil-piercing-forge': '2026-08-30T21:40:00+08:00',
  'criminal-22-high-altitude-throwing-diagram': '2026-08-01T22:16:39+08:00',
  'criminal-19-theft-mistake-analysis': '2026-08-01T22:16:39+08:00',
  'criminal-19-occupational-embezzlement-flowchart': '2026-08-01T22:16:39+08:00',
  'criminal-19-card-selling-funds-viewpoint': '2026-08-01T22:16:39+08:00',
  'criminal-19-property-interests-keypoints': '2026-08-01T22:16:39+08:00',
  'criminal-23-official-intermediary': '2026-08-01T22:16:39+08:00',
  'criminal-23-influence-intermediary': '2026-08-01T22:16:39+08:00',
  'civil-procedure-17-summary-procedure-switchyard': '2026-08-05T21:15:25+08:00',
  'civil-procedure-18-public-interest-litigation-network': '2026-08-05T21:15:25+08:00',
  'civil-procedure-19-third-party-revocation-remedy-map': '2026-08-05T21:15:25+08:00',
  'civil-procedure-20-appeal-review-decision-map': '2026-08-05T21:15:25+08:00',
  'civil-law-contract-book-atlas': '2026-08-08T18:17:31+08:00',
  'civil-law-14-security-publicity-fate': '2026-08-29T23:10:00+08:00',
  'civil-law-01-six-principles-pillars': '2026-08-30T02:30:00+08:00',
  'civil-procedure-32-penalty-adjustment-procedure': '2026-08-08T18:17:31+08:00',
  'theoretical-law-17-legal-interpretation': '2026-08-28T19:56:14+08:00',
  'criminal-procedure-07-evidence-exclusion-lattice': '2026-08-28T20:10:00+08:00',
  'criminal-procedure-01-procedure-structure-orrery': '2026-08-28T22:30:00+08:00',
  'criminal-procedure-03-organs-relay-map': '2026-08-29T01:30:00+08:00',
  'criminal-procedure-04-jurisdiction-sluice-terrace': '2026-08-29T14:50:00+08:00',
  'criminal-procedure-05-recusal-sentry-rotation': '2026-08-29T15:40:00+08:00',
  'criminal-procedure-06-defense-pilot-harbor': '2026-08-29T16:20:00+08:00',
  'criminal-procedure-08-coercion-pressure-ladder': '2026-08-29T16:50:00+08:00',
  'criminal-procedure-09-attached-suit-viaduct': '2026-08-29T17:20:00+08:00',
  'criminal-procedure-10-period-escapement-works': '2026-08-29T17:50:00+08:00',
  'criminal-procedure-11-case-filing-gatehouse': '2026-08-29T18:20:00+08:00',
  'criminal-procedure-12-supplement-invest-loop': '2026-08-29T18:50:00+08:00',
  'criminal-procedure-13-nonprosecution-signal-tower': '2026-08-29T19:20:00+08:00',
  'criminal-procedure-14-trial-bench-composition': '2026-08-29T19:50:00+08:00',
  'criminal-procedure-15-first-instance-procession': '2026-08-29T20:20:00+08:00',
  'criminal-procedure-16-appeal-no-escalation-lock': '2026-08-29T20:50:00+08:00',
  'criminal-procedure-18-retrial-rewind-loom': '2026-08-29T21:20:00+08:00',
  'criminal-procedure-19-execution-dispatch-board': '2026-08-29T21:50:00+08:00',
  'criminal-procedure-20-juvenile-observatory-greenhouse': '2026-08-29T22:20:00+08:00',
  'criminal-procedure-17-death-review-summit': '2026-08-29T21:20:00+08:00',
  'criminal-procedure-02-plea-leniency-caliper': '2026-08-29T01:05:00+08:00',
  'theoretical-law-01-concept-of-law-dispute': '2026-08-28T23:30:00+08:00',
  'international-law-01-sources-of-international-law': '2026-08-29T10:00:00+08:00',
  'international-law-02-subjects-responsibility': '2026-08-29T11:00:00+08:00',
  'international-law-03-spatial-regimes': '2026-08-29T12:00:00+08:00',
  'international-law-04-individuals-regimes': '2026-08-29T13:00:00+08:00',
  'international-law-05-diplomatic-consular': '2026-08-29T14:00:00+08:00',
  'international-law-06-law-of-treaties': '2026-08-29T15:00:00+08:00',
  'international-law-07-dispute-settlement': '2026-08-29T16:00:00+08:00',
  'international-law-08-war-armed-conflict': '2026-08-29T17:00:00+08:00',
  'international-law-09-cross-border-disputes': '2026-08-29T18:00:00+08:00',
  'international-law-10-conflict-of-laws-rules': '2026-08-29T19:00:00+08:00',
  'international-law-11-applicable-law': '2026-08-29T21:30:00+08:00',
  'international-law-13-interregional-assistance': '2026-08-30T01:20:00+08:00',
  'international-law-18-wto': '2026-08-30T03:40:00+08:00',
  'international-law-15-goods-transport-insurance': '2026-08-30T02:30:00+08:00',
  'international-law-12-extraterritorial-assistance': '2026-08-30T00:00:00+08:00',
  'international-law-14-international-sale-of-goods': '2026-08-30T01:00:00+08:00',
  'international-law-16-international-trade-payment': '2026-08-30T02:00:00+08:00',
  'international-law-17-foreign-trade-administration': '2026-08-30T03:00:00+08:00',
  'international-law-19-other-regimes-international-economic-law': '2026-08-30T04:00:00+08:00',
  'theoretical-law-01-marxist-law-essence': '2026-08-29T13:40:00+08:00',
  'theoretical-law-01-features-of-law': '2026-08-29T15:10:00+08:00',
  'theoretical-law-01-functions-of-law': '2026-08-29T16:40:00+08:00',
  'theoretical-law-01-limitations-of-law': '2026-08-29T18:00:00+08:00',
  'theoretical-law-01-value-conflict': '2026-08-29T19:20:00+08:00',
  'theoretical-law-01-legal-rules': '2026-08-29T20:40:00+08:00',
  'theoretical-law-01-legal-principles': '2026-08-29T22:00:00+08:00',
  'theoretical-law-01-sources-of-law': '2026-08-29T23:30:00+08:00',
  'theoretical-law-01-legal-departments-system': '2026-08-30T00:10:00+08:00',
  'theoretical-law-01-legal-validity': '2026-08-30T00:40:00+08:00',
  'theoretical-law-01-legal-relations': '2026-08-30T01:20:00+08:00',
  'theoretical-law-01-liability-concurrence': '2026-08-30T01:50:00+08:00',
  'theoretical-law-01-judicial-vs-administrative': '2026-08-30T02:20:00+08:00',
  'theoretical-law-01-application-of-law': '2026-08-30T02:50:00+08:00',
  'theoretical-law-01-legal-loopholes': '2026-08-30T03:20:00+08:00',
  'theoretical-law-01-legal-reasoning': '2026-08-30T03:30:00+08:00',
  'theoretical-law-01-legal-families': '2026-08-30T04:10:00+08:00',
  'theoretical-law-01-legal-modernization': '2026-08-30T04:40:00+08:00',
  'theoretical-law-01-law-and-morality': '2026-08-30T05:10:00+08:00',
  'theoretical-law-01-law-and-human-rights': '2026-08-30T05:40:00+08:00',
  'theoretical-law-01-legislation-law': '2026-08-30T06:10:00+08:00',
  'theoretical-law-01-features-of-constitution': '2026-08-30T06:40:00+08:00',
  'theoretical-law-01-creation-of-constitution': '2026-08-30T07:10:00+08:00',
  'theoretical-law-01-constitution-classification': '2026-08-30T07:40:00+08:00',
  'commercial-economic-law-01-profit-reserve-granary': '2026-08-30T22:20:00+08:00',
  'commercial-economic-law-01-promoter-liability-ropewalk': '2026-08-30T23:10:00+08:00',
  'commercial-economic-law-01-shareholder-register-pigeonhole': '2026-08-30T23:50:00+08:00',
  'commercial-economic-law-01-nominee-impersonation-masks': '2026-08-31T00:30:00+08:00',
  'commercial-economic-law-01-contribution-defect-audit': '2026-08-31T02:10:00+08:00',
  'commercial-economic-law-01-company-guaranty-seal-desk': '2026-08-31T03:00:00+08:00',
  'commercial-economic-law-01-capital-regime-vote-hall': '2026-08-31T01:20:00+08:00',
  ...COMMERCIAL_LAW_DEMO_ADDED_AT,
};

export const SORTED_STYLE_DEMOS = [...STYLE_DEMOS].sort((a, b) => DEMO_ADDED_AT[b.id].localeCompare(DEMO_ADDED_AT[a.id]));

export const demoById = (id: string) => STYLE_DEMOS.find((demo) => demo.id === id);

import {COMMERCIAL_LAW_DEMO_ADDED_AT, COMMERCIAL_LAW_STYLE_DEMOS} from './commercial-law-demo-registry';
