import type {CSSProperties, ReactNode} from 'react';
import {Boxes, ClipboardPenLine, Crosshair, FileInput, Gavel, Landmark, MapPinned, Microscope, Ruler, ScanLine, Search, Users} from 'lucide-react';
import {interpolate, useCurrentFrame} from 'remotion';
import {CLAMP} from '../../../../../shared/remotion-runtime';

const P={paper:'#eef0e8',ink:'#1f2926',grid:'#a9b5aa',teal:'#087f75',lime:'#b7d640',red:'#d9574d',yellow:'#f2c14e',white:'#ffffff'};
const Rise=({children,delay,style}:{children:ReactNode;delay:number;style?:CSSProperties})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+16],[0,1],CLAMP);return <div style={{opacity:p,translate:`0 ${24*(1-p)}px`,...style}}>{children}</div>};
const Blueprint=({code,title,children}:{code:string;title:string;children:ReactNode})=><div style={{position:'absolute',inset:0,overflow:'hidden',backgroundColor:P.paper,color:P.ink,fontFamily: 'var(--inkloom-animation-body)',backgroundImage:`linear-gradient(${P.grid}55 1px,transparent 1px),linear-gradient(90deg,${P.grid}55 1px,transparent 1px)`,backgroundSize:'48px 48px'}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:34,backgroundColor:P.teal}}/><div style={{position:'absolute',left:72,top:54,fontSize:18,fontWeight:900,color:P.teal}}>SITE INSPECTION PLAN / {code}</div><h1 style={{fontFamily: 'var(--inkloom-animation-title)', position:'absolute',left:72,top:92,margin:0,fontSize:56,fontWeight:900}}>{title}</h1><div style={{position:'absolute',left:72,right:72,top:174,height:5,backgroundColor:P.ink}}/>{children}<div style={{position:'absolute',left:72,bottom:26,fontSize:17,fontWeight:800}}>专题十 · 勘验笔录</div></div>;

export const InitiationScene=()=> <Blueprint code="01" title="谁能启动：当事人申请，也可以法院依职权">
  <div data-layout="dual-route-inspection-order" data-visual-anchor="flow-path" data-text-treatments="label-block,thin-underline,stamp" data-visual-grammar="application,authority,convergence,authorization" data-focal-rule="inspection-may-be-initiated-by-party-application-or-court-authority" data-focal-channels="icon,connector,spatial,contrast" style={{position:'absolute',left:72,right:72,top:214,bottom:72}}>
    <Rise delay={4} style={{position:'absolute',left:40,top:72,width:480,height:250,backgroundColor:P.white,border:`5px solid ${P.teal}`,padding:'34px 40px'}}><Users size={66} color={P.teal}/><div style={{marginTop:24,fontSize:38,fontWeight:900}}>当事人申请</div><div style={{marginTop:18,fontSize:25}}>向法院提出勘验请求</div></Rise>
    <div style={{position:'absolute',left:520,top:194,width:300,height:8,backgroundColor:P.teal,rotate:'8deg'}}/><div style={{position:'absolute',left:804,top:220,borderTop:'16px solid transparent',borderBottom:'16px solid transparent',borderLeft:`26px solid ${P.teal}`}}/>
    <Rise delay={24} style={{position:'absolute',left:678,top:250,width:440,height:340,display:'grid',placeItems:'center',backgroundColor:P.ink,color:P.white,textAlign:'center',border:`12px solid ${P.yellow}`}}><ClipboardPenLine size={92} color={P.yellow}/><div style={{fontSize:42,fontWeight:900,marginTop:-70}}>法院决定勘验</div><div style={{fontSize:24,marginTop:-76,color:'#d7ded8'}}>以必要性为判断门槛</div></Rise>
    <div style={{position:'absolute',right:520,top:194,width:300,height:8,backgroundColor:P.red,rotate:'-8deg'}}/><div style={{position:'absolute',right:804,top:220,borderTop:'16px solid transparent',borderBottom:'16px solid transparent',borderRight:`26px solid ${P.red}`}}/>
    <Rise delay={44} style={{position:'absolute',right:40,top:72,width:480,height:250,backgroundColor:P.red,color:P.white,padding:'34px 40px'}}><Landmark size={66}/><div style={{marginTop:24,fontSize:38,fontWeight:900}}>法院依职权</div><div style={{marginTop:18,fontSize:25}}>认为有必要即可启动</div></Rise>
    <Rise delay={64} style={{position:'absolute',left:560,bottom:0,width:680,height:76,backgroundColor:P.lime,color:P.ink,display:'grid',placeItems:'center',fontSize:30,fontWeight:900}}>两条启动路线，落到同一法院勘验决定</Rise>
  </div>
</Blueprint>;

export const ScopeScene=()=> <Blueprint code="02" title="勘验什么：物证，或者案件现场">
  <div data-layout="object-and-site-survey-map" data-visual-anchor="comparison-axis" data-text-treatments="label-block,soft-highlight,thin-underline" data-visual-grammar="object-scope,site-scope,observation,recording" data-focal-rule="inspection-targets-tangible-evidence-or-the-relevant-site" data-focal-channels="icon,enclosure,spatial,connector" style={{position:'absolute',left:72,right:72,top:214,bottom:72}}>
    <Rise delay={4} style={{position:'absolute',left:30,top:30,width:740,height:580,backgroundColor:P.ink,color:P.white,padding:'42px 48px'}}><Boxes size={82} color={P.lime}/><div style={{marginTop:28,fontSize:44,fontWeight:900}}>物证</div><div style={{marginTop:26,fontSize:28,lineHeight:1.5}}>对物品本体进行观察、测量<br/>固定颜色、大小、损坏与存在状态</div><div style={{position:'absolute',left:80,right:80,bottom:62,height:150,border:`5px solid ${P.lime}`,display:'grid',placeItems:'center'}}><Ruler size={82} color={P.lime}/></div></Rise>
    <div style={{position:'absolute',left:834,top:0,bottom:0,width:6,backgroundColor:P.teal}}/><div style={{position:'absolute',left:810,top:278,width:54,height:54,borderRadius:'50%',backgroundColor:P.yellow,border:`7px solid ${P.ink}`}}/>
    <Rise delay={30} style={{position:'absolute',right:30,top:30,width:820,height:580,backgroundColor:P.white,border:`6px solid ${P.teal}`,padding:'42px 48px'}}><MapPinned size={82} color={P.teal}/><div style={{marginTop:28,fontSize:44,fontWeight:900}}>现场</div><div style={{marginTop:26,fontSize:28,lineHeight:1.5}}>进入与案件有关的空间<br/>定位痕迹、距离、方位与环境关系</div><div style={{position:'absolute',left:100,right:100,bottom:54,height:170,backgroundColor:'#dbe6db',display:'grid',placeItems:'center'}}><Crosshair size={102} color={P.red}/></div></Rise>
    <Rise delay={58} style={{position:'absolute',left:660,bottom:2,width:510,height:84,backgroundColor:P.yellow,display:'flex',alignItems:'center',justifyContent:'center',gap:18,fontSize:28,fontWeight:900}}><Search size={40}/>观察结果写入勘验笔录</Rise>
  </div>
</Blueprint>;

export const ExpertParticipationScene=()=> <Blueprint code="03" title="专业问题升级：可让鉴定人参加，必要时当场鉴定">
  <div data-layout="inspection-to-appraisal-escalation" data-visual-anchor="timeline-gate" data-text-treatments="label-block,stamp,soft-highlight" data-visual-grammar="inspection,participation,necessity,escalation" data-focal-rule="the-court-may-require-appraiser-participation-and-necessary-on-site-appraisal" data-focal-channels="icon,connector,contrast,enclosure" style={{position:'absolute',left:72,right:72,top:214,bottom:72}}>
    <Rise delay={4} style={{position:'absolute',left:40,top:170,width:420,height:300,backgroundColor:P.teal,color:P.white,display:'grid',placeItems:'center',textAlign:'center'}}><ScanLine size={88}/><div style={{fontSize:38,fontWeight:900,marginTop:-70}}>法院勘验</div></Rise>
    <div style={{position:'absolute',left:460,top:316,width:220,height:8,backgroundColor:P.ink}}/><div style={{position:'absolute',left:664,top:303,borderTop:'17px solid transparent',borderBottom:'17px solid transparent',borderLeft:`26px solid ${P.ink}`}}/>
    <Rise delay={26} style={{position:'absolute',left:690,top:90,width:460,height:460,backgroundColor:P.white,border:`7px solid ${P.yellow}`,padding:'42px 46px'}}><Microscope size={86} color={P.teal}/><div style={{marginTop:28,fontSize:39,fontWeight:900}}>鉴定人参与勘验</div><div style={{marginTop:30,fontSize:27,lineHeight:1.5}}>法院可以要求<br/>不是自动参加</div><div style={{position:'absolute',left:46,right:46,bottom:42,padding:'16px',backgroundColor:P.yellow,fontSize:25,fontWeight:900,textAlign:'center'}}>提供专业观察能力</div></Rise>
    <div style={{position:'absolute',left:1150,top:316,width:220,height:8,backgroundColor:P.red}}/><div style={{position:'absolute',left:1354,top:303,borderTop:'17px solid transparent',borderBottom:'17px solid transparent',borderLeft:`26px solid ${P.red}`}}/>
    <Rise delay={52} style={{position:'absolute',right:40,top:170,width:380,height:300,backgroundColor:P.red,color:P.white,display:'grid',placeItems:'center',textAlign:'center'}}><FileInput size={82}/><div style={{fontSize:34,fontWeight:900,marginTop:-64}}>必要时<br/>勘验中进行鉴定</div></Rise>
    <Rise delay={72} style={{position:'absolute',left:500,bottom:0,width:800,height:78,backgroundColor:P.ink,color:P.white,display:'grid',placeItems:'center',fontSize:29,fontWeight:900}}>“可以参与”与“必要时鉴定”是两级授权</Rise>
  </div>
</Blueprint>;
