import type {CSSProperties,ReactNode} from 'react';
import {ArrowDownToLine,Ban,Clock3,FilePenLine,FileX2,Gavel,GitFork,HeartOff,Landmark,Layers3,Merge,PauseCircle,RotateCcw,ShieldAlert,ShieldCheck,UserRound,UserRoundX,UsersRound} from 'lucide-react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';
import {CLAMP,createMotionPrimitives,TimelineSequence} from '../../../../shared/remotion-runtime';
import {SCENES,toSourceFrame} from './storyboard';

const C={paper:'#f4f1ea',ink:'#161719',magenta:'#c23b79',magentaSoft:'#f3d9e6',teal:'#168579',tealSoft:'#d9efeb',yellow:'#edbd3b',yellowSoft:'#f8edc9',red:'#c64740',gray:'#6d7075',white:'#fffefa'};
const PLAYER_CONTROL_SAFE_BOTTOM = 160;
const {Enter,StaggerEnter,MaskedReveal}=createMotionPrimitives(toSourceFrame);
const Shell=({code,title,children}:{code:string;title:string;children:ReactNode})=><AbsoluteFill data-player-control-safe-bottom={PLAYER_CONTROL_SAFE_BOTTOM} style={{backgroundColor:C.paper,color:C.ink,overflow:'hidden'}}><div style={{position:'absolute',left:42,top:36,bottom: PLAYER_CONTROL_SAFE_BOTTOM,width:7,backgroundColor:C.magenta}}/><div style={{position:'absolute',left:72,top:44,fontSize:20,fontWeight:900,color:C.magenta}}>JUDGMENT LAYERS / {code}</div><MaskedReveal delay={0} style={{position:'absolute',left:72,top:84,fontSize:56,fontWeight:950}}>{title}</MaskedReveal><div style={{position:'absolute',left:72,right:72,top:166,height:4,backgroundColor:C.ink}}/><div style={{position:'absolute',left:72,right:72,top:190,bottom: PLAYER_CONTROL_SAFE_BOTTOM}}>{children}</div></AbsoluteFill>;
const Layer=({children,color=C.ink,style}:{children:ReactNode;color?:string;style?:CSSProperties})=><div style={{backgroundColor:'rgba(255,254,250,.93)',border:`4px solid ${color}`,boxShadow:`12px 12px 0 ${color}55`,padding:'20px 24px',...style}}>{children}</div>;
const Arrow=({x,y,w,p,color=C.teal}:{x:number;y:number;w:number;p:number;color?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:8,backgroundColor:'#c9c9c6'}}><div style={{width:'100%',height:'100%',backgroundColor:color,scale:`${p} 1`,transformOrigin:'left'}}/><span style={{position:'absolute',right:-2,top:-9,borderTop:'13px solid transparent',borderBottom:'13px solid transparent',borderLeft:`21px solid ${color}`}}/></div>;

export const StandingAndSixMonthClockScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[30,125],[0,1],CLAMP);const tests=[['身份','本应作为有独三 / 无独三'],['缺席','因不能归责于本人事由未参加'],['文书','生效判决、裁定、调解书有错误'],['损害','错误内容损害其民事权益']];return <Shell code="19.1" title="六个月之前，先把第三人的资格层层对齐"><div data-layout="six-layer-standing-stack-feeds-six-month-clock-and-origin-court" data-visual-anchor="timeline-gate" data-visual-grammar="third-party-status,non-attributable-absence,effective-document-error,rights-harm,knowledge-clock,origin-court" data-text-treatments="soft-highlight,thin-underline,stamp" data-focal-rule="all-standing-layers-plus-six-month-clock-and-origin-court-are-required" data-focal-channels="enclosure,connector,locator" style={{position:'absolute',inset:0}}>
  <StaggerEnter baseDelay={8} step={18} style={{position:'absolute',left:10,top:45,width:790,display:'grid',gridTemplateColumns:'1fr 1fr',gap:22}}>{tests.map(([a,b],i)=><Layer key={a} color={i<2?C.magenta:C.teal} style={{height:205,translate:`${i%2?18:0}px ${i>1?-5:0}px`}}><div style={{fontSize:22,fontWeight:900,color:i<2?C.magenta:C.teal}}>LAYER 0{i+1} · {a}</div><div style={{fontSize:28,fontWeight:950,lineHeight:1.4,marginTop:18}}>{b}</div></Layer>)}</StaggerEnter>
  <Arrow x={830} y={285} w={175} p={p}/><Enter delay={86} style={{position:'absolute',left:1020,top:95}}><div style={{width:330,height:330,borderRadius:'50%',border:`18px solid ${C.yellow}`,display:'grid',placeItems:'center',textAlign:'center'}}><Clock3 size={70} color={C.magenta}/><div data-final-knowledge="six-month-from-knowledge" style={{fontSize:39,fontWeight:950}}>6个月内</div><div style={{fontSize:23}}>自知道或应当知道<br/>权益受损之日起</div></div></Enter>
  <Arrow x={1360} y={285} w={120} p={p} color={C.magenta}/><Enter delay={118} style={{position:'absolute',right:0,top:115,width:295}}><Layer color={C.magenta} style={{height:290,textAlign:'center'}}><Landmark size={64} color={C.magenta}/><div data-final-knowledge="court-that-made-document" style={{fontSize:29,fontWeight:950,marginTop:18}}>向作出生效文书的法院起诉</div><div style={{fontSize:23,marginTop:22}}>请求撤销 / 改变</div></Layer></Enter>
  <div data-final-knowledge="independent-or-nonindependent-third-party" style={{position:'absolute',left:10,top:515,fontSize:22}}>主体：有独三或无独三</div><div data-final-knowledge="absence-not-attributable" style={{position:'absolute',left:300,top:515,fontSize:22}}>未参诉原因不可归责于本人</div><div data-final-knowledge="effective-judgment-order-mediation-error" style={{position:'absolute',left:10,top:560,fontSize:22}}>对象：生效判决 / 裁定 / 调解书错误</div><div data-final-knowledge="civil-rights-harmed" style={{position:'absolute',left:455,top:560,fontSize:22}}>效果：民事权益受损</div><div data-final-knowledge="formation-action" style={{position:'absolute',left:1020,top:490,width:625,padding:'16px',backgroundColor:C.ink,color:C.white,fontSize:25,fontWeight:900}}>性质：通过撤销、改变既有权利义务关系的形成之诉（变更之诉）</div>
 </div></Shell>};

export const NonacceptanceBoundariesScene=()=>{const items=[['非讼程序','特别 / 督促 / 公示催告 / 破产等',Layers3],['婚姻身份内容','无效、撤销或解除婚姻关系的身份部分',HeartOff],['未登记权利人','人数不确定代表人诉讼',UsersRound],['公益受害人','对公益诉讼生效裁判',UserRoundX]];return <Shell code="19.2" title="四个受理缺口：不是所有错误都能用三撤修复"><div data-layout="judgment-silhouette-with-four-cutout-exclusion-zones-and-alternative-routes" data-visual-anchor="boundary" data-visual-grammar="four-exclusions,identity-scope,alternative-remedies" data-text-treatments="external-negation,label-block,thin-underline" data-focal-rule="four-categories-are-excluded-but-some-retain-separate-routes" data-focal-channels="contrast,enclosure,connector" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:40,right:40,top:45,height:500,border:`5px solid ${C.ink}`,backgroundColor:C.white}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:235,backgroundColor:C.ink,color:C.white,display:'grid',placeItems:'center',textAlign:'center'}}><Ban size={82} color={C.yellow}/><div style={{fontSize:39,fontWeight:950}}>不予受理</div></div><StaggerEnter baseDelay={12} step={20} style={{position:'absolute',left:275,top:30,display:'grid',gridTemplateColumns:'1fr 1fr',gap:25,width:1355}}>{items.map(([a,b,Icon],i)=>{const I=Icon as typeof Ban;return <div key={String(a)} style={{height:200,padding:'22px 26px',backgroundColor:i%2?C.magentaSoft:C.yellowSoft,borderLeft:`10px solid ${i%2?C.magenta:C.yellow}`}}><I size={45}/><b style={{fontSize:30,marginLeft:15}}>{a}</b><div style={{fontSize:23,lineHeight:1.4,marginTop:16}}>{b}</div></div>})}</StaggerEnter></div>
  <div data-final-knowledge="noncontentious-proceedings-excluded" style={{position:'absolute',left:40,top:575,fontSize:22}}>非讼程序不以解决纠纷为本质，不能走三撤</div><div data-final-knowledge="marriage-status-content-excluded" style={{position:'absolute',left:485,top:575,fontSize:22}}>婚姻身份部分须保护再婚稳定</div><div data-final-knowledge="unregistered-represented-rightsholder-excluded" style={{position:'absolute',left:850,top:575,fontSize:22}}>未登记权利人可另行起诉</div><div data-final-knowledge="public-interest-victim-excluded" style={{position:'absolute',left:1260,top:575,fontSize:22}}>公益受害人可提普通民诉</div><div data-final-knowledge="property-content-remains-possible" style={{position:'absolute',left:420,top:630,width:530,padding:'13px',borderTop:`5px solid ${C.teal}`,fontSize:23,fontWeight:900}}>婚姻文书中的财产分割等非身份内容，仍可能三撤</div><div data-final-knowledge="separate-action-alternatives" style={{position:'absolute',left:1010,top:630,width:560,padding:'13px',borderTop:`5px solid ${C.magenta}`,fontSize:23,fontWeight:900}}>代表人诉讼未登记者、公益受害人：以另行起诉维护自身权益</div>
 </div></Shell>};

export const PartyPositionsAndExecutionScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[24,116],[0,1],CLAMP);return <Shell code="19.3" title="这是一个新诉：角色重排，执行另设两道刹车"><div data-layout="new-action-stage-with-role-reassignment-and-two-execution-brakes" data-visual-anchor="role-pair" data-visual-grammar="new-action,role-reassignment,collegiate-hearing,two-execution-brakes" data-text-treatments="label-block,stamp,soft-highlight" data-focal-rule="new-action-reassigns-parties-and-has-two-distinct-stay-routes" data-focal-channels="icon,connector,contrast" style={{position:'absolute',inset:0}}>
  <Enter delay={6} style={{position:'absolute',left:15,top:170}}><Layer color={C.magenta} style={{width:300,height:240,textAlign:'center'}}><UserRound size={70} color={C.magenta}/><div data-final-knowledge="third-party-as-plaintiff" style={{fontSize:34,fontWeight:950,marginTop:18}}>起诉第三人<br/>= 原告</div></Layer></Enter><Arrow x={335} y={290} w={120} p={p} color={C.magenta}/>
  <Enter delay={50} style={{position:'absolute',left:470,top:55,width:610}}><Layer color={C.ink} style={{height:450}}><UsersRound size={62}/><div style={{fontSize:36,fontWeight:950,marginTop:15}}>原审参与者重新列位</div><div data-final-knowledge="original-plaintiff-defendant-independent-third-as-defendants" style={{fontSize:24,lineHeight:1.45,marginTop:22,padding:16,backgroundColor:C.magentaSoft}}>原审原告、被告、有独三 → 被告</div><div data-final-knowledge="liable-nonindependent-third-as-defendant" style={{fontSize:24,lineHeight:1.45,marginTop:15,padding:16,backgroundColor:C.yellowSoft}}>原审承担责任的无独三 → 被告</div><div data-final-knowledge="nonliable-nonindependent-third-as-third-party" style={{fontSize:24,lineHeight:1.45,marginTop:15,padding:16,backgroundColor:C.tealSoft}}>原审未承担责任的无独三 → 第三人</div></Layer></Enter>
  <div data-final-knowledge="collegiate-open-hearing-no-summary" style={{position:'absolute',left:470,top:545,width:610,padding:'17px',border:`4px solid ${C.ink}`,fontSize:25,fontWeight:900}}><Gavel size={36} style={{verticalAlign:'middle',marginRight:12}}/>合议庭开庭审理；不得适用简易程序</div>
  <div style={{position:'absolute',right:0,top:35,width:560}}><div style={{fontSize:29,fontWeight:950,color:C.teal}}>原文书执行中的两道刹车</div><StaggerEnter baseDelay={78} step={24} style={{display:'grid',gap:30,marginTop:24}}><Layer color={C.yellow} style={{height:220}}><PauseCircle size={55} color={C.yellow}/><div data-final-knowledge="security-request-may-stay" style={{fontSize:28,fontWeight:950,marginTop:14}}>提供担保 + 请求</div><div style={{fontSize:24,marginTop:16}}>法院可以准许中止执行</div></Layer><Layer color={C.teal} style={{height:220}}><ShieldCheck size={55} color={C.teal}/><div data-final-knowledge="execution-objection-upheld-must-stay" style={{fontSize:28,fontWeight:950,marginTop:14}}>案外人执行标的异议成立</div><div style={{fontSize:24,marginTop:16}}>执行法院裁定中止执行</div></Layer></StaggerEnter></div>
 </div></Shell>};

export const JudgmentThreeWayScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[28,108],[0,1],CLAMP);return <Shell code="19.4" title="裁判先问原判错没错，再问第三人的权利成不成立"><div data-layout="two-question-judgment-test-splits-into-change-revoke-and-reject-slices" data-visual-anchor="flow-path" data-visual-grammar="original-error-test,own-right-test,three-results,unaffected-layer" data-text-treatments="stamp,thin-underline,external-negation" data-focal-rule="two-tests-produce-change-revoke-or-reject" data-focal-channels="connector,contrast,motion" style={{position:'absolute',inset:0}}>
  <Enter delay={5} style={{position:'absolute',left:20,top:180}}><Layer color={C.ink} style={{width:330,height:250}}><GitFork size={62}/><div style={{fontSize:34,fontWeight:950,marginTop:20}}>两问测试</div><div style={{fontSize:25,lineHeight:1.5,marginTop:18}}>① 原文书是否错误？<br/>② 第三人权利主张是否成立？</div></Layer></Enter><Arrow x={370} y={300} w={170} p={p}/>
  <StaggerEnter baseDelay={50} step={24} style={{position:'absolute',left:565,top:65,display:'flex',gap:30}}><Layer color={C.teal} style={{width:365,height:390}}><FilePenLine size={60} color={C.teal}/><div data-final-knowledge="error-and-own-right-change" style={{fontSize:31,fontWeight:950,marginTop:20}}>原判错误<br/>+ 自身权利成立</div><div style={{fontSize:26,marginTop:30,padding:15,backgroundColor:C.teal,color:C.white}}>改变错误部分</div></Layer><Layer color={C.magenta} style={{width:365,height:390}}><FileX2 size={60} color={C.magenta}/><div data-final-knowledge="error-without-own-right-revoke" style={{fontSize:31,fontWeight:950,marginTop:20}}>原判错误<br/>但权利不成立 / 未提出</div><div style={{fontSize:26,marginTop:30,padding:15,backgroundColor:C.magenta,color:C.white}}>撤销错误部分</div></Layer><Layer color={C.red} style={{width:365,height:390}}><Ban size={60} color={C.red}/><div data-final-knowledge="request-fails-reject" style={{fontSize:31,fontWeight:950,marginTop:20}}>撤销请求<br/>不成立</div><div style={{fontSize:26,marginTop:72,padding:15,backgroundColor:C.red,color:C.white}}>驳回诉讼请求</div></Layer></StaggerEnter>
  <div data-final-knowledge="unaffected-parts-remain" style={{position:'absolute',left:565,top:510,width:1160,padding:'19px 24px',backgroundColor:C.yellowSoft,borderLeft:`12px solid ${C.yellow}`,fontSize:26,fontWeight:900}}>原判决、裁定、调解书中未被改变或撤销的部分，继续有效</div><div data-final-knowledge="judgment-appealable" style={{position:'absolute',left:20,top:510,width:330,padding:'18px',borderTop:`5px solid ${C.magenta}`,fontSize:25,fontWeight:900}}>对三撤之诉判决不服：可以上诉</div>
 </div></Shell>};

export const RetrialConvergenceScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[22,120],[0,1],CLAMP);return <Shell code="19.5" title="三撤遇上再审：原则合流，恶意串通时反向优先"><div data-layout="revocation-route-merges-into-retrial-with-malicious-collusion-bypass-and-instance-protection" data-visual-anchor="flow-path" data-visual-grammar="retrial-priority,malicious-collusion-exception,first-instance-merge,second-instance-remand" data-text-treatments="label-block,external-negation,stamp" data-focal-rule="retrial-priority-yields-only-to-malicious-collusion-and-instance-rights-are-protected" data-focal-channels="connector,enclosure,contrast" style={{position:'absolute',inset:0}}>
  <Enter delay={5} style={{position:'absolute',left:10,top:90}}><Layer color={C.magenta} style={{width:320,height:205}}><FilePenLine size={55}/><div style={{fontSize:32,fontWeight:950,marginTop:16}}>三撤正在审理</div></Layer></Enter><Enter delay={20} style={{position:'absolute',left:10,top:360}}><Layer color={C.teal} style={{width:320,height:205}}><RotateCcw size={55}/><div style={{fontSize:32,fontWeight:950,marginTop:16}}>原案裁定再审</div></Layer></Enter>
  <Arrow x={350} y={255} w={225} p={p}/><Arrow x={350} y={465} w={225} p={p}/><Enter delay={62} style={{position:'absolute',left:600,top:180}}><div style={{width:390,height:300,backgroundColor:C.ink,color:C.white,display:'grid',placeItems:'center',textAlign:'center'}}><Merge size={75} color={C.yellow}/><div data-final-knowledge="retrial-priority-merge" style={{fontSize:35,fontWeight:950}}>原则：再审优先<br/>第三人诉请并入再审</div></div></Enter>
  <div data-final-knowledge="malicious-collusion-revocation-first-and-retrial-stayed" style={{position:'absolute',left:600,top:525,width:390,padding:'18px',backgroundColor:C.magentaSoft,border:`4px solid ${C.magenta}`,fontSize:23,fontWeight:900}}><ShieldAlert size={35} style={{verticalAlign:'middle'}}/> 证据证明原审当事人恶意串通：先审三撤，裁定中止再审</div>
  <StaggerEnter baseDelay={92} step={24} style={{position:'absolute',right:0,top:75,display:'grid',gap:35}}><Layer color={C.teal} style={{width:620,height:225}}><ArrowDownToLine size={55} color={C.teal}/><div data-final-knowledge="first-instance-retrial-joins-and-appealable" style={{fontSize:29,fontWeight:950,marginTop:14}}>再审按一审程序</div><div style={{fontSize:24,marginTop:15}}>直接并入审理；所作判决可以上诉</div></Layer><Layer color={C.red} style={{width:620,height:260}}><RotateCcw size={55} color={C.red}/><div data-final-knowledge="second-instance-retrial-mediate-or-remand" style={{fontSize:29,fontWeight:950,marginTop:14}}>再审按二审程序</div><div style={{fontSize:24,marginTop:15}}>可以调解；调解不成，撤销原文书并发回一审重审</div><div data-final-knowledge="third-party-listed-on-remand" style={{fontSize:23,marginTop:14,color:C.red,fontWeight:900}}>重审时应当列明第三人</div></Layer></StaggerEnter>
 </div></Shell>};

export const ThirdPartyRevocationRemedyMap=()=> <AbsoluteFill><TimelineSequence name="01-standing-and-six-month-clock" {...SCENES.standingAndSixMonthClock}><StandingAndSixMonthClockScene/></TimelineSequence><TimelineSequence name="02-nonacceptance-boundaries" {...SCENES.nonacceptanceBoundaries}><NonacceptanceBoundariesScene/></TimelineSequence><TimelineSequence name="03-party-positions-and-execution" {...SCENES.partyPositionsAndExecution}><PartyPositionsAndExecutionScene/></TimelineSequence><TimelineSequence name="04-judgment-three-way" {...SCENES.judgmentThreeWay}><JudgmentThreeWayScene/></TimelineSequence><TimelineSequence name="05-retrial-convergence" {...SCENES.retrialConvergence}><RetrialConvergenceScene/></TimelineSequence></AbsoluteFill>;
