import type {CSSProperties,ReactNode} from 'react';
import {BadgeCheck,Ban,FilePenLine,FileUp,Focus,Gavel,GitFork,Handshake,PenLine,RotateCcw,ScanSearch,SearchCheck,ShieldAlert,ShieldX,Timer,Undo2,UserRoundCheck,UserRoundMinus,UsersRound} from 'lucide-react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';
import {CLAMP,createMotionPrimitives,TimelineSequence} from '../../../../shared/remotion-runtime';
import {SCENES,toSourceFrame} from './storyboard';

const C={paper:'#f3f2ed',ink:'#17191c',saffron:'#e4aa25',saffronSoft:'#f6e8bb',teal:'#138178',tealSoft:'#d7ece8',red:'#c9433c',redSoft:'#f4dbd7',blue:'#3568a6',blueSoft:'#dce7f3',white:'#fffefa',gray:'#6a6e72'};
const PLAYER_CONTROL_SAFE_BOTTOM = 160;
const {Enter,StaggerEnter,MaskedReveal}=createMotionPrimitives(toSourceFrame);
const Shell=({code,title,children}:{code:string;title:string;children:ReactNode})=><AbsoluteFill data-player-control-safe-bottom={PLAYER_CONTROL_SAFE_BOTTOM} style={{backgroundColor:C.paper,color:C.ink,overflow:'hidden'}}><div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(rgba(23,25,28,.055) 1px,transparent 1px)',backgroundSize:'100% 46px'}}/><div style={{position:'absolute',left:68,top:42,width:180,height:36,backgroundColor:C.saffron}}/><div style={{position:'absolute',left:78,top:47,fontSize:19,fontWeight:950}}>APPELLATE / {code}</div><MaskedReveal delay={0} style={{position:'absolute',left:68,top:94,fontSize:57,fontWeight:950}}>{title}</MaskedReveal><div style={{position:'absolute',left:68,right:68,top:174,height:5,backgroundColor:C.ink}}/><div style={{position:'absolute',left:68,right:68,top:192,bottom: PLAYER_CONTROL_SAFE_BOTTOM}}>{children}</div></AbsoluteFill>;
const Column=({children,color=C.ink,style}:{children:ReactNode;color?:string;style?:CSSProperties})=><div style={{backgroundColor:C.white,borderLeft:`10px solid ${color}`,borderTop:`3px solid ${C.ink}`,padding:'21px 24px',...style}}>{children}</div>;
const Beam=({x,y,w,p,color=C.saffron}:{x:number;y:number;w:number;p:number;color?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:9,backgroundColor:'#c9c9c7'}}><div style={{height:'100%',backgroundColor:color,scale:`${p} 1`,transformOrigin:'left'}}/></div>;

export const AppealEntryScene=()=>{const sections=[['谁能上诉',UsersRound,'原告、被告、有独三；判决承担义务的无独三'],['上诉对象',FileUp,'一审判决 + 不予受理、驳回起诉、管辖权异议三类裁定'],['上诉期间',Timer,'判决 15 日 / 裁定 10 日，自送达日起算'],['法定形式',PenLine,'必须提交书面上诉状；口头上诉无效']];return <Shell code="20.1" title="上诉入口由主体、对象、期间、形式共同锁定"><div data-layout="four-part-written-appeal-gate-with-positive-and-finality-columns" data-visual-anchor="boundary" data-visual-grammar="qualified-parties,appealable-documents,deadlines,written-form" data-text-treatments="label-block,thin-underline,external-negation" data-focal-rule="appeal-exists-only-when-all-four-entry-conditions-are-met" data-focal-channels="icon,enclosure,contrast" style={{position:'absolute',inset:0}}>
  <StaggerEnter baseDelay={6} step={20} style={{position:'absolute',left:0,top:35,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,width:1080}}>{sections.map(([title,Icon,body],i)=>{const I=Icon as typeof UsersRound;return <Column key={String(title)} color={[C.blue,C.teal,C.saffron,C.red][i]} style={{height:230}}><I size={52} color={[C.blue,C.teal,C.saffron,C.red][i]}/><b style={{fontSize:31,marginLeft:16}}>{title}</b><div style={{fontSize:24,lineHeight:1.45,marginTop:20}}>{body}</div></Column>})}</StaggerEnter>
  <Enter delay={96} style={{position:'absolute',right:0,top:35,width:560}}><Column color={C.red} style={{height:500}}><Ban size={56} color={C.red}/><div style={{fontSize:34,fontWeight:950,marginTop:15}}>一审终审：不能上诉</div><div data-final-knowledge="five-finality-categories" style={{fontSize:23,lineHeight:1.55,marginTop:22}}>① 最高法院一审判决、裁定<br/>② 调解书<br/>③ 一般裁定（除三类可上诉裁定）<br/>④ 特别 / 督促 / 公示催告程序<br/>⑤ 小额诉讼判决、裁定</div><div data-final-knowledge="agent-needs-special-authorization" style={{marginTop:22,padding:'13px',backgroundColor:C.redSoft,fontSize:23,fontWeight:900}}>委托代理人代为上诉：须特别授权</div></Column></Enter>
  <div data-final-knowledge="plaintiff-defendant-independent-third" style={{position:'absolute',left:0,top:535,fontSize:22}}>原告、被告、有独三均有上诉权</div><div data-final-knowledge="liable-nonindependent-third-only" style={{position:'absolute',left:385,top:535,fontSize:22}}>无独三只在判决承担义务时有上诉权</div><div data-final-knowledge="judgment-and-three-orders" style={{position:'absolute',left:0,top:580,fontSize:22}}>对象：一审判决 + 三类裁定</div><div data-final-knowledge="fifteen-and-ten-days-from-service" style={{position:'absolute',left:385,top:580,fontSize:22}}>判决15日 / 裁定10日，自送达日起算</div><div data-final-knowledge="written-appeal-only" style={{position:'absolute',left:760,top:580,fontSize:22,fontWeight:900,color:C.red}}>只有书面上诉有效</div>
 </div></Shell>};

export const PartyPositionImpactTestScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[24,112],[0,1],CLAMP);return <Shell code="20.2" title="被上诉人不是看原审称谓，而是看改判后谁受损"><div data-layout="appeal-request-overlay-recalculates-loss-to-assign-respondents" data-visual-anchor="comparison-axis" data-visual-grammar="appellant-source,hypothetical-success,loss-detection,role-assignment" data-text-treatments="soft-highlight,thin-underline,label-block" data-focal-rule="hypothetical-success-identifies-the-losing-respondent" data-focal-channels="connector,motion,contrast" style={{position:'absolute',inset:0}}>
  <Enter delay={5} style={{position:'absolute',left:0,top:150}}><Column color={C.blue} style={{width:330,height:280,textAlign:'center'}}><UserRoundCheck size={68} color={C.blue}/><div data-final-knowledge="who-appeals-is-appellant" style={{fontSize:35,fontWeight:950,marginTop:22}}>谁提上诉<br/>谁是上诉人</div></Column></Enter><Beam x={350} y={290} w={200} p={p} color={C.blue}/>
  <Enter delay={48} style={{position:'absolute',left:570,top:75}}><div style={{width:470,height:430,border:`7px solid ${C.saffron}`,backgroundColor:C.saffronSoft,display:'grid',placeItems:'center',textAlign:'center',padding:45}}><ScanSearch size={80}/><div data-final-knowledge="successful-request-loss-test" style={{fontSize:38,fontWeight:950}}>假设上诉请求<br/>全部成立</div><div style={{fontSize:26,lineHeight:1.45}}>与一审判决相比<br/>谁权利减少 / 义务增加？</div></div></Enter><Beam x={1060} y={290} w={185} p={p}/>
  <StaggerEnter baseDelay={90} step={22} style={{position:'absolute',right:0,top:65,display:'grid',gap:30}}><Column color={C.red} style={{width:500,height:215}}><UserRoundMinus size={56} color={C.red}/><div data-final-knowledge="affected-loser-is-respondent" style={{fontSize:31,fontWeight:950,marginTop:14}}>会受损的人 → 被上诉人</div><div style={{fontSize:23,marginTop:14}}>权利减少或义务增加都算</div></Column><Column color={C.teal} style={{width:500,height:215}}><UsersRound size={56} color={C.teal}/><div data-final-knowledge="unaffected-keeps-original-role" style={{fontSize:31,fontWeight:950,marginTop:14}}>不受损的人 → 按原审地位列明</div><div style={{fontSize:23,marginTop:14}}>不因共同诉讼而自动成为被上诉人</div></Column></StaggerEnter>
  <div data-final-knowledge="all-appeal-all-appellants-no-respondent" style={{position:'absolute',left:430,top:555,width:900,padding:'19px',backgroundColor:C.ink,color:C.white,textAlign:'center',fontSize:27,fontWeight:950}}>所有当事人都上诉：都是上诉人，没有被上诉人</div>
 </div></Shell>};

export const RequestScopeScene=()=>{const frame=toSourceFrame(useCurrentFrame());const crop=interpolate(frame,[28,105],[0,1],CLAMP);return <Shell code="20.3" title="二审用两道裁切线：上诉请求 + 一审范围"><div data-layout="appeal-beam-crops-first-instance-record-with-public-interest-exception-and-hearing-mode" data-visual-anchor="boundary" data-visual-grammar="request-limit,mandatory-exception,first-instance-limit,hearing-rule" data-text-treatments="thin-underline,external-negation,stamp" data-focal-rule="review-is-cropped-by-request-and-first-instance-boundaries" data-focal-channels="locator,enclosure,contrast" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:40,top:75,width:1020,height:420,backgroundColor:C.white,border:`4px solid ${C.ink}`,overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:260,backgroundColor:C.gray,opacity:.2}}/><div style={{position:'absolute',left:260,top:0,bottom:0,width:560,backgroundColor:C.saffron,opacity:.26*crop}}/><div style={{position:'absolute',right:0,top:0,bottom:0,width:200,backgroundColor:C.gray,opacity:.2}}/><Focus size={70} color={C.saffron} style={{position:'absolute',left:505,top:100}}/><div data-final-knowledge="review-around-appeal-request" style={{position:'absolute',left:350,top:210,width:430,textAlign:'center',fontSize:35,fontWeight:950}}>只围绕上诉请求审理</div><div data-final-knowledge="unrequested-not-reviewed" style={{position:'absolute',left:35,top:305,fontSize:24,color:C.gray}}>未请求部分：原则不审</div><div data-final-knowledge="within-first-instance-claims-and-trial" style={{position:'absolute',right:25,top:305,width:260,fontSize:24,textAlign:'right',color:C.gray}}>也不得越出一审诉请与审理范围</div></div>
  <Enter delay={75} style={{position:'absolute',left:40,top:535,width:1020}}><div data-final-knowledge="prohibition-public-third-interest-exception" style={{padding:'18px 24px',backgroundColor:C.redSoft,borderLeft:`12px solid ${C.red}`,fontSize:25,fontWeight:900}}><ShieldAlert size={38} style={{verticalAlign:'middle',marginRight:12}}/>例外：一审违反禁止性规定，或损害国家、公共、他人利益，二审依职权审查</div></Enter>
  <div style={{position:'absolute',right:0,top:55,width:600}}><Column color={C.teal} style={{height:245}}><Gavel size={56} color={C.teal}/><div data-final-knowledge="hearing-principle" style={{fontSize:31,fontWeight:950,marginTop:15}}>原则：开庭审理</div><div data-final-knowledge="no-new-fact-evidence-reason-may-skip" style={{fontSize:23,lineHeight:1.45,marginTop:18}}>经阅卷、调查、询问；没有新事实、证据、理由且认为无需开庭 → 可以不开庭</div></Column><Column color={C.blue} style={{height:270,marginTop:30}}><UsersRound size={56} color={C.blue}/><div data-final-knowledge="collegiate-principle-and-limited-single-judge" style={{fontSize:30,fontWeight:950,marginTop:14}}>原则：审判员合议庭</div><div style={{fontSize:23,lineHeight:1.42,marginTop:15}}>中院 + 一审简易结案或裁定上诉 + 事实权义清楚 + 双方同意 → 可审判员一人独任</div></Column></div>
 </div></Shell>};

export const NewMattersRoutingScene=()=>{const branches=[['一审已提但漏判','调解不成 → 发回重审',C.red],['必须参加者 / 有独三遗漏','调解不成 → 发回重审',C.red],['一审不准离婚，二审认为应离','调解不成 → 发回；双方同意可一并裁判',C.saffron],['二审新增独立请求 / 反诉','调解不成 → 告知另诉；双方同意可一并裁判',C.teal]];return <Shell code="20.4" title="新事项先进入调解路由器，再看是一审过错还是新增请求"><div data-layout="four-new-matter-feeds-enter-mediation-router-and-produce-remand-or-new-suit" data-visual-anchor="flow-path" data-visual-grammar="omitted-claim,omitted-party,divorce-package,new-claim-counterclaim,mediation-router" data-text-treatments="label-block,stamp,soft-highlight" data-focal-rule="mediation-failure-remands-first-instance-errors-but-separates-new-second-instance-claims" data-focal-channels="connector,contrast,icon" style={{position:'absolute',inset:0}}>
  <StaggerEnter baseDelay={5} step={17} style={{position:'absolute',left:0,top:25,display:'grid',gap:18}}>{branches.map(([a,b,color],i)=><Column key={String(a)} color={String(color)} style={{width:520,height:137}}><div style={{fontSize:18,fontWeight:900,color:String(color)}}>INPUT 0{i+1}</div><div style={{fontSize:26,fontWeight:950,marginTop:7}}>{a}</div></Column>)}</StaggerEnter>
  <Enter delay={72} style={{position:'absolute',left:650,top:165}}><div style={{width:380,height:330,borderRadius:'50%',backgroundColor:C.saffron,display:'grid',placeItems:'center',textAlign:'center'}}><Handshake size={78}/><div style={{fontSize:40,fontWeight:950}}>先行调解</div><div style={{fontSize:23}}>保障两审终审与处分权</div></div></Enter>
  <StaggerEnter baseDelay={98} step={22} style={{position:'absolute',right:0,top:65,display:'grid',gap:30}}><Column color={C.red} style={{width:570,height:235}}><RotateCcw size={55} color={C.red}/><div style={{fontSize:30,fontWeight:950,marginTop:14}}>一审有遗漏 / 判断错误</div><div style={{fontSize:25,marginTop:20}}>调解不成：撤销原判，发回重审</div></Column><Column color={C.teal} style={{width:570,height:255}}><GitFork size={55} color={C.teal}/><div style={{fontSize:30,fontWeight:950,marginTop:14}}>二审新请求 / 反诉</div><div style={{fontSize:25,marginTop:20}}>调解不成：告知另行起诉</div><div style={{fontSize:22,marginTop:14}}>双方同意时，可由二审一并裁判</div></Column></StaggerEnter>
  <div data-final-knowledge="omitted-claim-mediate-then-remand" style={{position:'absolute',left:0,top:590,fontSize:22}}>漏判诉请 → 调解 / 发回</div><div data-final-knowledge="omitted-necessary-party-mediate-then-remand" style={{position:'absolute',left:300,top:590,fontSize:22}}>遗漏必要当事人 / 有独三 → 调解 / 发回</div><div data-final-knowledge="divorce-package-mediate-then-remand-or-consensual-judgment" style={{position:'absolute',left:735,top:590,fontSize:22}}>应判离婚的财产、子女问题 → 调解 / 发回；同意可一并裁判</div><div data-final-knowledge="new-claim-counterclaim-mediate-then-separate-suit-or-consensual-judgment" style={{position:'absolute',left:735,top:635,fontSize:22}}>新增请求、反诉 → 调解 / 另诉；同意可一并裁判</div>
 </div></Shell>};

export const AdjudicationSwitchboardScene=()=>{const rows=[['事实清楚 + 法律正确','驳回上诉，维持原判决 / 裁定',BadgeCheck,C.teal],['事实或法律错误','改判、撤销、变更',FilePenLine,C.blue],['基本事实不清','发回重审；或查清后改判',SearchCheck,C.saffron],['严重违反法定程序','撤销原判，发回重审',ShieldX,C.red]];return <Shell code="20.5" title="二审裁判不是一律发回：先辨错误类型"><div data-layout="four-error-signals-fan-into-maintain-correct-remand-or-correct-after-fact-finding" data-visual-anchor="flow-path" data-visual-grammar="correct,fact-or-law-error,basic-facts-unclear,serious-procedure-error,filing-condition" data-text-treatments="stamp,label-block,external-negation" data-focal-rule="each-error-type-has-its-own-appellate-disposition" data-focal-channels="connector,contrast,icon" style={{position:'absolute',inset:0}}>
  <StaggerEnter baseDelay={5} step={20} style={{position:'absolute',left:0,top:30,display:'grid',gridTemplateColumns:'1fr 1fr',gap:25,width:1180}}>{rows.map(([a,b,Icon,color])=>{const I=Icon as typeof BadgeCheck;return <Column key={String(a)} color={String(color)} style={{height:245}}><I size={55} color={String(color)}/><div style={{fontSize:30,fontWeight:950,marginTop:13}}>{a}</div><div style={{fontSize:25,lineHeight:1.4,marginTop:18}}>{b}</div></Column>})}</StaggerEnter>
  <div data-final-knowledge="correct-dismiss-appeal-maintain" style={{position:'absolute',left:0,top:555,fontSize:22}}>正确 → 驳回上诉、维持</div><div data-final-knowledge="fact-or-law-error-change-revoke-vary" style={{position:'absolute',left:290,top:555,fontSize:22}}>事实 / 法律错误 → 改、撤、变</div><div data-final-knowledge="basic-facts-unclear-remand-or-find-and-change" style={{position:'absolute',left:650,top:555,fontSize:22}}>基本事实不清 → 发回或查清改判</div><div data-final-knowledge="serious-procedure-error-must-remand" style={{position:'absolute',left:1030,top:555,fontSize:22}}>严重程序违法 → 必须发回</div>
  <Enter delay={104} style={{position:'absolute',right:0,top:30,width:500}}><Column color={C.red} style={{height:510}}><Ban size={55} color={C.red}/><div data-final-knowledge="filing-condition-failure-revoke-and-dismiss-action" style={{fontSize:29,fontWeight:950,marginTop:15}}>二审发现不符合起诉条件</div><div style={{fontSize:24,marginTop:15}}>撤销原判，驳回起诉</div><div style={{height:3,backgroundColor:C.ink,margin:'26px 0'}}/><div data-final-knowledge="wrong-nonacceptance-direct-acceptance" style={{fontSize:24,lineHeight:1.45}}>一审不予受理错误 → 撤销并指令受理</div><div data-final-knowledge="wrong-dismiss-action-direct-trial" style={{fontSize:24,lineHeight:1.45,marginTop:25}}>一审驳回起诉错误 → 撤销并指令审理</div></Column></Enter>
 </div></Shell>};

export const RemandAndExitEffectsScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[20,118],[0,1],CLAMP);return <Shell code="20.6" title="发回只用一次；调解、撤诉、撤回上诉改变原判效力"><div data-layout="one-use-remand-loop-beside-mediation-withdraw-action-and-withdraw-appeal-effect-tracks" data-visual-anchor="flow-path" data-visual-grammar="remand-effects,one-use-lock,mediation-effect,withdraw-action-effect,withdraw-appeal-effect" data-text-treatments="stamp,external-negation,thin-underline" data-focal-rule="remand-is-single-use-and-each-exit-has-a-different-effect-on-first-judgment" data-focal-channels="connector,motion,contrast" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:0,top:25,width:830,height:565,border:`5px solid ${C.red}`,padding:'28px 32px'}}><RotateCcw size={70} color={C.red}/><div style={{fontSize:37,fontWeight:950,marginTop:15}}>发回重审：一次性回路</div><div style={{position:'absolute',left:85,top:190,width:620,height:12,backgroundColor:'#ccc'}}><div style={{height:'100%',backgroundColor:C.red,width:`${p*100}%`}}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginTop:95}}><div data-final-knowledge="new-collegiate-bench-no-single-judge" style={{padding:17,backgroundColor:C.redSoft,fontSize:23}}>另行组成合议庭<br/>不得独任；原审人员回避</div><div data-final-knowledge="first-instance-retrial-and-new-appeal" style={{padding:17,backgroundColor:C.saffronSoft,fontSize:23}}>按一审程序重审<br/>新判决仍可上诉</div><div data-final-knowledge="redecide-facts-new-judgment" style={{padding:17,backgroundColor:C.blueSoft,fontSize:23}}>重新认定事实、适用法律<br/>作出新判决</div><div data-final-knowledge="prior-procedural-acts-bind" style={{padding:17,backgroundColor:C.tealSoft,fontSize:23}}>原审诉讼行为仍有效<br/>约束当事人与法院</div></div><div data-final-knowledge="remand-only-once" style={{marginTop:24,padding:'14px',backgroundColor:C.ink,color:C.white,textAlign:'center',fontSize:28,fontWeight:950}}>再次上诉：二审不得再次发回重审</div></div>
  <StaggerEnter baseDelay={62} step={22} style={{position:'absolute',right:0,top:25,display:'grid',gap:22}}><Column color={C.teal} style={{width:790,height:170}}><Handshake size={44} color={C.teal}/><div data-final-knowledge="second-instance-mediation-order-revokes-original" style={{fontSize:27,fontWeight:950,marginTop:10}}>二审调解：必须制作调解书</div><div style={{fontSize:23,marginTop:8}}>调解书送达后，原判决视为撤销</div></Column><Column color={C.red} style={{width:790,height:210}}><Undo2 size={44} color={C.red}/><div data-final-knowledge="withdraw-action-consent-public-interest-and-original-revoked-no-refiling" style={{fontSize:27,fontWeight:950,marginTop:10}}>原审原告撤回起诉</div><div style={{fontSize:22,lineHeight:1.4,marginTop:8}}>其他当事人同意 + 不损害国家、公共、他人利益；准许时一并撤销一审裁判；此后不得重复起诉</div></Column><Column color={C.saffron} style={{width:790,height:175}}><Undo2 size={44} color={C.saffron}/><div data-final-knowledge="withdraw-appeal-before-judgment-original-effective" style={{fontSize:27,fontWeight:950,marginTop:10}}>判决宣告前撤回上诉</div><div style={{fontSize:22,lineHeight:1.4,marginTop:8}}>法院裁定是否准许；准许裁定作出之日，一审判决生效</div></Column></StaggerEnter>
 </div></Shell>};

export const AppealReviewDecisionMap=()=> <AbsoluteFill><TimelineSequence name="01-appeal-entry" {...SCENES.appealEntry}><AppealEntryScene/></TimelineSequence><TimelineSequence name="02-party-position-impact-test" {...SCENES.partyPositionImpactTest}><PartyPositionImpactTestScene/></TimelineSequence><TimelineSequence name="03-request-scope" {...SCENES.requestScope}><RequestScopeScene/></TimelineSequence><TimelineSequence name="04-new-matters-routing" {...SCENES.newMattersRouting}><NewMattersRoutingScene/></TimelineSequence><TimelineSequence name="05-adjudication-switchboard" {...SCENES.adjudicationSwitchboard}><AdjudicationSwitchboardScene/></TimelineSequence><TimelineSequence name="06-remand-and-exit-effects" {...SCENES.remandAndExitEffects}><RemandAndExitEffectsScene/></TimelineSequence></AbsoluteFill>;
