import type {CSSProperties,ReactNode} from 'react';
import {ArrowUpRight,Ban,FileX2,Handshake,Landmark,Leaf,Megaphone,ShieldCheck,ShoppingBasket,UserPlus,UserRound,UsersRound} from 'lucide-react';
import {AbsoluteFill,interpolate,useCurrentFrame} from 'remotion';
import {CLAMP,createMotionPrimitives,TimelineSequence} from '../../../../shared/remotion-runtime';
import {SCENES,toSourceFrame} from './storyboard';

const C={ivory:'#f6f2e8',ink:'#1b2524',green:'#16805d',greenSoft:'#d7eee3',blue:'#2765ad',blueSoft:'#dce8f6',coral:'#e25c4c',coralSoft:'#f8dfda',yellow:'#edbd3e',white:'#fffefa',gray:'#687270'};
const PLAYER_CONTROL_SAFE_BOTTOM = 160;
const {Enter,StaggerEnter,MaskedReveal}=createMotionPrimitives(toSourceFrame);
const Shell=({code,title,children}:{code:string;title:string;children:ReactNode})=><AbsoluteFill data-player-control-safe-bottom={PLAYER_CONTROL_SAFE_BOTTOM} style={{backgroundColor:C.ivory,color:C.ink,overflow:'hidden'}}><div style={{position:'absolute',inset:0,backgroundImage:'radial-gradient(circle at 50% 53%,rgba(22,128,93,.08) 0 210px,transparent 212px)'}}/><div style={{position:'absolute',left:70,top:45,fontSize:22,fontWeight:900,color:C.green,borderBottom:`4px solid ${C.green}`,paddingBottom:8}}>CIVIC NOTICE / {code}</div><MaskedReveal delay={0} style={{position:'absolute',left:70,top:90,fontSize:56,fontWeight:950}}>{title}</MaskedReveal><div style={{position:'absolute',left:70,right:70,top:170,height:3,backgroundColor:C.ink}}/><div style={{position:'absolute',left:70,right:70,top:190,bottom: PLAYER_CONTROL_SAFE_BOTTOM}}>{children}</div></AbsoluteFill>;
const Notice=({children,color=C.green,style}:{children:ReactNode;color?:string;style?:CSSProperties})=><div style={{backgroundColor:C.white,borderTop:`12px solid ${color}`,padding:'22px 25px',boxShadow:'0 5px 0 rgba(27,37,36,.16)',...style}}>{children}</div>;
const Link=({x,y,w,p,color=C.green}:{x:number;y:number;w:number;p:number;color?:string})=><div style={{position:'absolute',left:x,top:y,width:w,height:7,backgroundColor:'rgba(27,37,36,.16)',rotate:y<250?'-4deg':'4deg'}}><div style={{height:'100%',backgroundColor:color,scale:`${p} 1`,transformOrigin:'left'}}/></div>;

export const PublicInterestEntryScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[24,104],[0,1],CLAMP);return <Shell code="18.1" title="公共利益受损：谁能起诉，案件落到哪家法院？"><div data-layout="qualified-actor-orbit-feeds-four-condition-commons-and-jurisdiction-pins" data-visual-anchor="boundary" data-visual-grammar="qualified-actors,four-entry-conditions,jurisdiction,ten-day-notice" data-text-treatments="label-block,thin-underline,stamp" data-focal-rule="statutory-actors-pass-four-conditions-into-intermediate-court-jurisdiction" data-focal-channels="icon,enclosure,locator" style={{position:'absolute',inset:0}}>
  <StaggerEnter baseDelay={8} step={18} style={{position:'absolute',left:0,top:65,display:'grid',gap:25}}><Notice color={C.green} style={{width:365,height:195}}><Leaf size={52} color={C.green}/><div style={{fontSize:30,fontWeight:950,marginTop:13}}>环境公益组织</div><div style={{fontSize:23,marginTop:9}}>市级以上民政登记 · 环保5年以上 · 无违法记录</div></Notice><Notice color={C.blue} style={{width:365,height:175}}><ShoppingBasket size={52} color={C.blue}/><div style={{fontSize:30,fontWeight:950,marginTop:13}}>省级以上消协</div><div style={{fontSize:23,marginTop:9}}>以及中国消费者协会</div></Notice></StaggerEnter>
  <Link x={390} y={260} w={225} p={p}/><Enter delay={52} style={{position:'absolute',left:630,top:95}}><div style={{width:470,height:405,borderRadius:'50%',backgroundColor:C.green,color:C.white,display:'grid',placeItems:'center',padding:62,textAlign:'center'}}><UsersRound size={70}/><div style={{fontSize:39,fontWeight:950}}>公益诉讼入口</div><div data-final-knowledge="four-filing-conditions" style={{fontSize:24,lineHeight:1.48}}>明确被告<br/>具体诉请<br/>公共利益受损初步证据<br/>民诉受理范围 + 管辖</div></div></Enter>
  <Link x={1090} y={260} w={190} p={p} color={C.blue}/><Enter delay={94} style={{position:'absolute',right:0,top:55,width:475}}><Notice color={C.blue} style={{height:485}}><Landmark size={60} color={C.blue}/><div style={{fontSize:34,fontWeight:950,marginTop:16}}>侵权行为地 / 被告住所地</div><div data-final-knowledge="intermediate-court-jurisdiction" style={{marginTop:18,padding:'12px 15px',backgroundColor:C.blue,color:C.white,fontSize:27,fontWeight:950}}>中级法院管辖</div><div data-final-knowledge="first-filed-rule" style={{fontSize:24,lineHeight:1.45,marginTop:22}}>同一侵权行为多地起诉：最先立案法院管辖；必要时共同上级法院指定</div><div data-final-knowledge="ten-day-administrative-notice" style={{fontSize:24,lineHeight:1.4,marginTop:22,borderLeft:`8px solid ${C.coral}`,paddingLeft:15}}>受理后 10 日内<br/>书面告知行政主管部门</div></Notice></Enter>
  <div data-final-knowledge="statutory-organizations" style={{position:'absolute',left:0,top:495,width:365,fontSize:24,fontWeight:900}}>起诉主体只能是法律规定的机关、有关组织</div>
 </div></Shell>};

export const CoPlaintiffAndPrivateClaimsScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[30,105],[0,1],CLAMP);return <Shell code="18.2" title="同一侵权行为：公益合流，私益并行"><div data-layout="public-commons-with-pre-hearing-join-and-parallel-private-claim-lane" data-visual-anchor="role-pair" data-visual-grammar="join-before-hearing,common-plaintiff,post-judgment-bar,private-parallel-lane,counterclaim-bar" data-text-treatments="soft-highlight,external-negation,label-block" data-focal-rule="qualified-public-actors-join-before-hearing-while-victims-sue-separately" data-focal-channels="connector,contrast,icon" style={{position:'absolute',inset:0}}>
  <Enter delay={6} style={{position:'absolute',left:20,top:170}}><Notice color={C.blue} style={{width:335,height:225}}><UserPlus size={58} color={C.blue}/><div style={{fontSize:31,fontWeight:950,marginTop:16}}>其他适格机关 / 组织</div><div style={{fontSize:24,marginTop:18}}>开庭前申请参加</div></Notice></Enter><Link x={370} y={285} w={235} p={p} color={C.blue}/>
  <Enter delay={58} style={{position:'absolute',left:620,top:115}}><div style={{width:455,height:350,borderRadius:'50%',border:`12px solid ${C.green}`,backgroundColor:C.greenSoft,display:'grid',placeItems:'center',textAlign:'center'}}><UsersRound size={76} color={C.green}/><div data-final-knowledge="approved-as-common-plaintiff" style={{fontSize:38,fontWeight:950}}>法院准许<br/>列为共同原告</div></div></Enter>
  <div data-final-knowledge="eligible-organizations-join-before-hearing" style={{position:'absolute',left:20,top:435,width:500,fontSize:24,fontWeight:900,color:C.blue}}>公开合流窗口只开到“开庭前”</div>
  <div data-final-knowledge="same-public-suit-bar-after-judgment" style={{position:'absolute',left:510,top:505,width:620,padding:'18px 22px',backgroundColor:C.coralSoft,borderLeft:`10px solid ${C.coral}`,fontSize:24,fontWeight:900}}><Ban size={34} style={{verticalAlign:'middle',marginRight:12}}/>裁判生效后，其他适格主体不得就同一侵权行为再提公益诉讼</div>
  <div style={{position:'absolute',right:0,top:40,width:565,height:520,borderLeft:`7px dashed ${C.yellow}`,paddingLeft:35}}><div style={{fontSize:25,fontWeight:950,color:C.coral}}>另一条不被公益诉讼吞并的轨道</div><Enter delay={82}><Notice color={C.yellow} style={{height:225,marginTop:28}}><UserRound size={58}/><div style={{fontSize:34,fontWeight:950,marginTop:16}}>同一行为的受害人</div><div data-final-knowledge="victim-private-suit-unaffected" style={{fontSize:25,marginTop:20}}>可以另行提起普通民事诉讼</div></Notice></Enter><div data-final-knowledge="victim-no-third-party-revocation" style={{marginTop:22,fontSize:24}}>因此不能对公益裁判提第三人撤销之诉</div><div data-final-knowledge="counterclaim-not-accepted" style={{marginTop:24,padding:'15px',border:`4px solid ${C.coral}`,fontSize:24,fontWeight:900}}><Ban size={32} style={{verticalAlign:'middle'}}/> 公益诉讼中，被告反诉不予受理</div></div>
 </div></Shell>};

export const SettlementPublicReviewScene=()=>{const frame=toSourceFrame(useCurrentFrame());const ring=interpolate(frame,[35,110],[0,360],CLAMP);return <Shell code="18.3" title="公益和解先向社会公开，再由法院审查"><div data-layout="agreement-sheet-crosses-thirty-day-public-notice-ring-and-interest-review-fork" data-visual-anchor="timeline-gate" data-visual-grammar="agreement,thirty-day-publication,public-interest-review,two-results" data-text-treatments="thin-underline,stamp,external-negation" data-focal-rule="agreement-needs-thirty-day-publication-and-public-interest-review" data-focal-channels="motion,enclosure,contrast" style={{position:'absolute',inset:0}}>
  <Enter delay={6} style={{position:'absolute',left:5,top:170}}><Notice color={C.blue} style={{width:330,height:260}}><Handshake size={64} color={C.blue}/><div data-stateful-source="agreement-sheet" style={{fontSize:35,fontWeight:950,marginTop:20}}>和解 / 调解协议</div><div data-final-knowledge="settlement-and-mediation-allowed" style={{fontSize:24,marginTop:22}}>公益诉讼允许和解、调解</div></Notice></Enter>
  <div style={{position:'absolute',left:475,top:65,width:440,height:440,borderRadius:'50%',border:`15px solid ${C.yellow}`,display:'grid',placeItems:'center',textAlign:'center',rotate:`${ring}deg`}}><Megaphone size={75} color={C.coral} style={{rotate:`-${ring}deg`}}/><div style={{rotate:`-${ring}deg`}}><div data-final-knowledge="publication-at-least-thirty-days" style={{fontSize:42,fontWeight:950}}>公告 ≥ 30日</div><div style={{fontSize:24,marginTop:14}}>接受社会检视</div></div></div>
  <div data-stateful-terminal="agreement-sheet" style={{position:'absolute',left:900,top:245,width:180,padding:'18px',border:`4px solid ${C.yellow}`,fontSize:23,fontWeight:900,textAlign:'center'}}>公告后的协议</div>
  <StaggerEnter baseDelay={98} step={20} style={{position:'absolute',right:0,top:45,display:'grid',gap:25}}><Notice color={C.green} style={{width:550,height:205}}><ShieldCheck size={52} color={C.green}/><div data-final-knowledge="lawful-public-interest-mediation-order" style={{fontSize:29,fontWeight:950,marginTop:12}}>不违反社会公共利益</div><div style={{fontSize:24,marginTop:15}}>应当出具调解书</div></Notice><Notice color={C.coral} style={{width:550,height:240}}><FileX2 size={52} color={C.coral}/><div data-final-knowledge="harmful-agreement-no-order-and-continue" style={{fontSize:29,fontWeight:950,marginTop:12}}>违反社会公共利益</div><div style={{fontSize:24,marginTop:15}}>不出具调解书；继续审理并裁判</div><div data-final-knowledge="no-withdrawal-merely-for-settlement" style={{fontSize:23,marginTop:16,color:C.coral,fontWeight:900}}>不得仅以达成和解为由撤诉</div></Notice></StaggerEnter>
 </div></Shell>};

export const ProcuratorateSupplementarityScene=()=>{const frame=toSourceFrame(useCurrentFrame());const p=interpolate(frame,[22,130],[0,1],CLAMP);const steps=[['补充性入口','无法定机关组织，或其不提起诉讼'],['诉前 30 日','依法公告；英烈案件也可直接征询近亲属'],['提起诉讼','市级检察院作为公益诉讼起诉人'],['进入法院','被告住所地 / 侵权行为地中级法院']];return <Shell code="18.4" title="检察机关站在补位位置：先让法定主体选择"><div data-layout="eligible-actor-vacancy-gate-precedes-thirty-day-prosecutorial-notice-and-court-route" data-visual-anchor="flow-path" data-visual-grammar="supplementary-trigger,pre-suit-notice,hero-relative-option,prosecutor-and-court,appeal" data-text-treatments="label-block,thin-underline,stamp" data-focal-rule="procuratorate-may-sue-only-after-qualified-private-actors-do-not" data-focal-channels="connector,icon,motion" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:80,right:120,top:286,height:10,backgroundColor:'rgba(27,37,36,.18)'}}><div style={{height:'100%',backgroundColor:C.green,width:`${p*100}%`}}/></div>
  {steps.map(([title,detail],i)=><Enter key={title} delay={10+i*28} style={{position:'absolute',left:20+i*430,top:i%2?330:75,width:370}}><Notice color={[C.coral,C.yellow,C.green,C.blue][i]} style={{height:210}}><div style={{fontSize:22,fontWeight:900,color:[C.coral,C.yellow,C.green,C.blue][i]}}>0{i+1}</div><div style={{fontSize:31,fontWeight:950,marginTop:10}}>{title}</div><div style={{fontSize:23,lineHeight:1.4,marginTop:15}}>{detail}</div></Notice></Enter>)}
  <div data-final-knowledge="no-organization-or-no-suit-trigger" style={{position:'absolute',left:20,top:545,width:370,fontSize:23,fontWeight:900}}>只有“无人起诉”才打开补位门</div><div data-final-knowledge="thirty-day-pre-suit-notice" style={{position:'absolute',left:450,top:565,width:370,fontSize:23,fontWeight:900}}>公告期间固定为 30 日</div><div data-final-knowledge="hero-relative-inquiry-alternative" style={{position:'absolute',left:450,top:610,width:370,fontSize:22}}>英烈姓名、肖像、名誉、荣誉案件：可直接征询近亲属</div><div data-final-knowledge="city-procurator-public-plaintiff" style={{position:'absolute',left:880,top:310,width:370,fontSize:23,fontWeight:900}}>身份是“公益诉讼起诉人”</div><div data-final-knowledge="intermediate-court-jurisdiction" style={{position:'absolute',left:1310,top:545,width:370,fontSize:23,fontWeight:900}}>法院仍是侵权地 / 被告住所地中院</div>
  <div style={{position:'absolute',left:860,top:540,width:400,padding:'18px',borderTop:`5px solid ${C.coral}`}}><ArrowUpRight size={38}/><span data-final-knowledge="appeal-not-protest" style={{fontSize:24,fontWeight:950}}>不服一审：上诉，不是抗诉</span><div data-final-knowledge="original-procurator-attends-second-instance" style={{fontSize:22,marginTop:10}}>二审由原提起公益诉讼的检察院派员；上级检察院也可参加</div></div>
 </div></Shell>};

export const PublicInterestLitigationNetwork=()=> <AbsoluteFill><TimelineSequence name="01-public-interest-entry" {...SCENES.publicInterestEntry}><PublicInterestEntryScene/></TimelineSequence><TimelineSequence name="02-co-plaintiff-and-private-claims" {...SCENES.coPlaintiffAndPrivateClaims}><CoPlaintiffAndPrivateClaimsScene/></TimelineSequence><TimelineSequence name="03-settlement-public-review" {...SCENES.settlementPublicReview}><SettlementPublicReviewScene/></TimelineSequence><TimelineSequence name="04-procuratorate-supplementarity" {...SCENES.procuratorateSupplementarity}><ProcuratorateSupplementarityScene/></TimelineSequence></AbsoluteFill>;
