import React from 'react';
import {AbsoluteFill, Easing, interpolate, useCurrentFrame} from 'remotion';
import {TimelineSequence} from '../../../../shared/remotion-runtime';
import {SCENES} from './storyboard';

const C = {ink:'#171A1F', ivory:'#F4EBD8', paper:'#FFF9EC', copper:'#B76D3B', red:'#C73E3A', blue:'#247BA0', mint:'#54A98C', gold:'#D7A928', ash:'#77756F', white:'#FFFFFF'};
const PLAYER_CONTROL_SAFE_BOTTOM = 160;
const reveal = (f:number, d=0, x=0, y=24) => ({
  opacity: interpolate(f,[d,d+18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),
  translate: `${interpolate(f,[d,d+22],[x,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)})}px ${interpolate(f,[d,d+22],[y,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)})}px`,
});

const Shell=({code,title,children}:{code:string;title:string;children:React.ReactNode})=><AbsoluteFill data-player-control-safe-bottom={PLAYER_CONTROL_SAFE_BOTTOM} className="font-animation-body" style={{background:C.ivory,color:C.ink,overflow:'hidden',backgroundImage:'radial-gradient(circle at 50% 46%,rgba(183,109,59,.10),transparent 38%),linear-gradient(rgba(23,26,31,.055) 1px,transparent 1px),linear-gradient(90deg,rgba(23,26,31,.055) 1px,transparent 1px)',backgroundSize:'auto,56px 56px,56px 56px'}}>
  <div style={{position:'absolute',left:58,right:58,top:34,height:112,borderBottom:`6px solid ${C.ink}`,display:'flex',alignItems:'center',gap:28}}>
    <div style={{width:96,height:74,background:C.red,color:C.white,display:'grid',placeItems:'center',fontSize:25,fontWeight:950,clipPath:'polygon(12% 0,100% 0,88% 100%,0 100%)'}}>{code}</div>
    <h1 className="font-animation-title" style={{fontSize:48,lineHeight:1.08,margin:0}}>{title}</h1>
    <div style={{marginLeft:'auto',fontSize:20,fontWeight:900,letterSpacing:3,color:C.copper}}>PENALTY · VERDICT ARENA</div>
  </div>
  <main style={{position:'absolute',left:58,right:58,top:174,bottom: PLAYER_CONTROL_SAFE_BOTTOM}}>{children}</main>
</AbsoluteFill>;

const Plate=({title,body,color=C.copper,style}:{title:string;body:string;color?:string;style?:React.CSSProperties})=><div style={{background:C.paper,border:`4px solid ${C.ink}`,borderTop:`13px solid ${color}`,padding:'18px 22px',boxShadow:'9px 9px 0 rgba(23,26,31,.13)',...style}}><div style={{fontSize:30,fontWeight:950,color}}>{title}</div><div style={{fontSize:23,lineHeight:1.42,marginTop:9}}>{body}</div></div>;
const Stamp=({children,color=C.red}:{children:React.ReactNode;color?:string})=><span style={{display:'inline-block',border:`4px solid ${color}`,color,padding:'7px 13px',fontSize:23,fontWeight:950,rotate:'-2deg'}}>{children}</span>;
const Arrow=({vertical=false,color=C.red}:{vertical?:boolean;color?:string})=><div style={{fontSize:50,color,fontWeight:950,lineHeight:1}}>{vertical?'↓':'→'}</div>;
const Chip=({children,color=C.blue,invert=false}:{children:React.ReactNode;color?:string;invert?:boolean})=><span style={{display:'inline-flex',alignItems:'center',justifyContent:'center',minHeight:48,padding:'8px 15px',background:invert?color:C.paper,color:invert?C.white:C.ink,border:`3px solid ${color}`,fontSize:22,fontWeight:900,lineHeight:1.25,textAlign:'center'}}>{children}</span>;

export const SanctionDefinitionFilterScene=()=>{const f=useCurrentFrame();return <Shell code="01" title="惩戒过滤器：先认定处罚，再排除相邻行为"><div data-layout="central-verdict-filter-with-four-rejection-chutes" data-visual-anchor="boundary" data-visual-grammar="violation-enters-a-rights-reduction-or-duty-increase-verdict,nonpunitive-administrative-measures-fall-through-four-external-rejection-chutes" data-text-treatments="soft-highlight,external-negation,stamp" data-focal-rule="administrative-penalty-definition-and-exclusions" data-focal-channels="enclosure,contrast,motion" style={{position:'absolute',inset:0}}>
  <div data-final-knowledge="penalty-definition" style={{position:'absolute',left:535,top:36,width:690,height:210,background:C.ink,color:C.white,clipPath:'polygon(8% 0,92% 0,100% 24%,88% 100%,12% 100%,0 24%)',display:'grid',placeItems:'center',textAlign:'center',padding:'24px 60px',...reveal(f,5)}}><div><div style={{fontSize:34,fontWeight:950,color:C.gold}}>行政处罚</div><div style={{fontSize:25,lineHeight:1.5,marginTop:12}}>行政机关对违反行政管理秩序者<br/><u>减损权益</u> 或 <u>增加义务</u> 的惩戒</div></div></div>
  <div style={{position:'absolute',left:860,top:250,width:8,height:110,background:C.red}}/><div style={{position:'absolute',left:847,top:335,borderLeft:'17px solid transparent',borderRight:'17px solid transparent',borderTop:`28px solid ${C.red}`}}/>
  {/* data-final-knowledge="exclusion-fee" data-final-knowledge="exclusion-status" data-final-knowledge="exclusion-correction" data-final-knowledge="exclusion-internal" */}
  {[["超标排污费","非惩戒性征收"],["撤销 / 注销 / 撤回","资格状态处理"],["责令改正","纠正违法状态"],["内部处分","不是对外行政处罚"]].map((x,i)=><div key={x[0]} data-final-knowledge={['exclusion-fee','exclusion-status','exclusion-correction','exclusion-internal'][i]} style={{position:'absolute',left:40+i*430,top:420+(i%2)*55,width:375,minHeight:160,background:C.paper,border:`4px dashed ${C.red}`,padding:20,...reveal(f,24+i*12,0,28)}}><Stamp>排除</Stamp><div style={{fontSize:29,fontWeight:950,marginTop:12}}>{x[0]}</div><div style={{fontSize:22,marginTop:7}}>{x[1]}</div></div>)}
  <div style={{position:'absolute',left:300,right:300,bottom:16,display:'flex',justifyContent:'space-between',fontSize:23,fontWeight:850}}><span data-final-knowledge="territorial-rule">属地原则：外国人、无国籍人、外国组织也适用</span><span data-final-knowledge="criminal-offset" style={{color:C.blue}}>拘留折抵拘役/有期徒刑；罚款折抵罚金</span></div>
 </div></Shell>};

export const FiveSanctionMachinesScene=()=>{const f=useCurrentFrame();const a=[['精神罚','警告 · 通报批评','◉',C.gold],['财产罚','罚款 · 没收非法财物/违法所得','◆',C.copper],['资格罚','暂扣 · 吊销 · 降低资质等级','▥',C.blue],['行为罚','停产停业 · 关闭 · 限制经营/从业','▰',C.red],['人身罚','行政拘留','▣',C.ink]];return <Shell code="02" title="五台惩戒装置：效果不同，法定种类不同"><div data-layout="five-radial-sanction-machines" data-visual-anchor="flow-target" data-visual-grammar="one-illegal-act-fans-into-five-distinct-legal-effect-machines,each-machine-preserves-the-sanction-name-and-its-statutory-examples" data-text-treatments="label-block,soft-highlight,stamp" data-focal-rule="five-categories-of-administrative-penalties" data-focal-channels="connector,icon,spatial" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:725,top:260,width:310,height:190,borderRadius:'50%',background:C.red,color:C.white,display:'grid',placeItems:'center',fontSize:34,fontWeight:950,textAlign:'center'}}>违法行为<br/>进入惩戒场</div>
  {/* data-final-knowledge="machine-mental" data-final-knowledge="machine-property" data-final-knowledge="machine-qualification" data-final-knowledge="machine-conduct" data-final-knowledge="machine-personal" */}
  {a.map((x,i)=>{const pos=[[40,20],[610,0],[1180,20],[250,470],[970,470]][i];return <div key={x[0]} data-final-knowledge={['machine-mental','machine-property','machine-qualification','machine-conduct','machine-personal'][i]} style={{position:'absolute',left:pos[0],top:pos[1],width:i<3?520:540,height:190,background:C.paper,border:`5px solid ${x[3]}`,padding:20,...reveal(f,8+i*13)}}><div style={{display:'flex',alignItems:'center',gap:18}}><span style={{fontSize:55,color:x[3]}}>{x[2]}</span><b style={{fontSize:34,color:x[3]}}>{x[0]}</b></div><div style={{fontSize:23,lineHeight:1.45,marginTop:14}}>{x[1]}</div></div>})}
 </div></Shell>};

export const PowerRoutingSplitScene=()=>{const f=useCurrentFrame();return <Shell code="03" title="处罚权分流：罚没看法定机关，拘留锁定公安"><div data-layout="forked-authority-referee-whistle" data-visual-anchor="document-fork" data-visual-grammar="a-penalty-decision-forks-by-sanction-type,detention-remains-reserved-to-public-security-and-legally-designated-organs" data-text-treatments="thin-underline,external-negation,label-block" data-focal-rule="exclusive-authority-for-detention" data-focal-channels="connector,contrast,locator" style={{position:'absolute',inset:30}}>
  <div data-final-knowledge="authority-source" style={{position:'absolute',left:70,top:220,width:360,height:220,background:C.ink,color:C.white,display:'grid',placeItems:'center',textAlign:'center',fontSize:34,fontWeight:950,...reveal(f,5)}}>处罚决定<br/><span style={{fontSize:23,color:C.gold}}>先看种类</span></div>
  <div style={{position:'absolute',left:430,top:310,width:250,height:12,background:C.copper}}/><div style={{position:'absolute',left:665,top:245,fontSize:120,color:C.copper}}>Y</div>
  <div data-final-knowledge="fine-confiscation-route" style={{position:'absolute',left:790,top:70,width:720,height:230,...reveal(f,25,35,0)}}><Plate title="罚款 / 没收 / 资格与行为罚" body="由法律、法规授权的行政机关依职权实施；其他处罚种类只能由法律、行政法规设定。" color={C.blue} style={{height:'100%'}}/></div>
  <div data-final-knowledge="detention-police-route" style={{position:'absolute',left:790,top:390,width:720,height:230,...reveal(f,42,35,0)}}><Plate title="行政拘留" body="公安机关以及法律规定的其他机关专属；治安管理处罚只处罚自然人。" color={C.red} style={{height:'100%'}}/></div>
  <div style={{position:'absolute',right:30,bottom:0,fontSize:27,fontWeight:950}}><Stamp color={C.copper}>罚没他机关，拘留找公安；程序治安管</Stamp></div>
 </div></Shell>};

export const RulemakingMoldLadderScene=()=>{const f=useCurrentFrame();const floors=[['法律','所有种类',C.ink,760],['行政法规','除限制人身自由',C.copper,650],['地方性法规','再除吊销营业执照、其他种类',C.blue,535],['部门规章','警告、通报批评、一定罚款；国务院定上限',C.gold,420],['地方规章','同上；省人大常委会定罚款上限',C.mint,305]];return <Shell code="04" title="五级铸模权限：规范层级越低，能造的处罚越少"><div data-layout="descending-five-level-sanction-mold-ladder" data-visual-anchor="boundary" data-visual-grammar="each-lower-normative-level-loses-sanction-molding-authority,personal-freedom-and-business-license-boundaries-stop-lower-level-creators" data-text-treatments="label-block,external-negation,thin-underline" data-focal-rule="administrative-penalty-setting-powers" data-focal-channels="spatial,enclosure,contrast" style={{position:'absolute',inset:0}}>
  {/* data-final-knowledge="mold-law" data-final-knowledge="mold-regulation" data-final-knowledge="mold-local-law" data-final-knowledge="mold-ministry-rule" data-final-knowledge="mold-local-rule" */}
  {floors.map((x,i)=><div key={x[0]} data-final-knowledge={['mold-law','mold-regulation','mold-local-law','mold-ministry-rule','mold-local-rule'][i]} style={{position:'absolute',left:80+i*135,top:30+i*125,width:x[3],height:104,background:x[2],color:i===3?C.ink:C.white,padding:'15px 24px',clipPath:'polygon(0 0,96% 0,100% 50%,96% 100%,0 100%)',...reveal(f,8+i*12,-35,0)}}><b style={{fontSize:31}}>{x[0]}</b><div style={{fontSize:22,marginTop:8}}>{x[1]}</div></div>)}
  <div data-final-knowledge="other-types-reservation" style={{position:'absolute',right:55,top:90,width:410,height:430,border:`7px double ${C.red}`,padding:28,background:C.paper}}><div style={{fontSize:31,fontWeight:950,color:C.red}}>两道保留闸</div><div style={{fontSize:25,lineHeight:1.7,marginTop:30}}>限制人身自由<br/>→ <b>只能法律</b><br/><br/>“其他种类处罚”<br/>→ <b>只能法律、行政法规</b></div></div>
 </div></Shell>};

export const SpecificationBenchmarkRailScene=()=>{const f=useCurrentFrame();return <Shell code="05" title="规定权校准轨：只能细化，不得越出上位法"><div data-layout="upper-law-tolerance-rail-with-public-benchmark" data-visual-anchor="comparison-axis" data-visual-grammar="lower-law-details-slide-only-within-upper-law-behavior-type-and-range-rails,public-discretion-benchmarks-mark-consistent-exercise-inside-the-rail" data-text-treatments="thin-underline,soft-highlight,stamp" data-focal-rule="specification-and-discretion-benchmark-limits" data-focal-channels="enclosure,locator,contrast" style={{position:'absolute',inset:30}}>
  <div data-final-knowledge="upper-law-envelope" style={{position:'absolute',left:70,right:70,top:210,height:190,border:`8px solid ${C.ink}`,background:C.paper}}><div style={{position:'absolute',top:-52,left:20,fontSize:31,fontWeight:950}}>上位法允许区间</div><div style={{display:'flex',height:'100%',alignItems:'center',justifyContent:'space-around',fontSize:31,fontWeight:900}}><span>违法行为</span><span>处罚种类</span><span>处罚幅度</span></div></div>
  <div data-final-knowledge="lower-law-slider" style={{position:'absolute',left:250,right:250,top:285,height:44,background:C.copper,...reveal(f,18,-160,0)}}><div style={{position:'absolute',left:'42%',top:-32,width:150,height:108,background:C.red,color:C.white,display:'grid',placeItems:'center',fontSize:27,fontWeight:950}}>下位法<br/>具体规定</div></div>
  <div data-final-knowledge="published-benchmark" style={{position:'absolute',left:180,bottom:30,width:620,height:180,...reveal(f,40)}}><Plate title="裁量基准" body="规范行政处罚裁量权，应当向社会公布。" color={C.blue} style={{height:'100%'}}/></div>
  <div data-final-knowledge="no-expansion" style={{position:'absolute',right:180,bottom:30,width:620,height:180,...reveal(f,52)}}><Plate title="越轨即违法" body="不得新增违法行为、处罚种类或突破上位法幅度。" color={C.red} style={{height:'100%'}}/></div>
 </div></Shell>};

export const SupplementalSettingChamberScene=()=>{const f=useCurrentFrame();const steps=['严格听证 / 论证','书面说明必要性','报制定机关备案'];return <Shell code="06" title="补充设定密室：行政法规、地方性法规须过三重程序"><div data-layout="three-ring-supplemental-setting-chamber" data-visual-anchor="timeline-gate" data-visual-grammar="supplemental-setting-enters-only-through-hearing-justification-and-filing-rings,administrative-and-local-regulations-use-a-narrow-statutorily-supervised-channel" data-text-treatments="stamp,label-block,soft-highlight" data-focal-rule="supplemental-penalty-setting-procedure" data-focal-channels="enclosure,motion,connector" style={{position:'absolute',inset:0}}>
  <div data-final-knowledge="supplement-source" style={{position:'absolute',left:80,top:260,width:300,height:210,background:C.ink,color:C.white,display:'grid',placeItems:'center',textAlign:'center',fontSize:30,fontWeight:950}}>行政法规<br/>地方性法规<br/><span style={{fontSize:21,color:C.gold}}>法定情形下补充设定</span></div>
  {/* data-final-knowledge="supplement-hearing" data-final-knowledge="supplement-explanation" data-final-knowledge="supplement-filing" */}
  {steps.map((s,i)=><React.Fragment key={s}><div data-final-knowledge={['supplement-hearing','supplement-explanation','supplement-filing'][i]} style={{position:'absolute',left:500+i*390,top:210+(i%2)*85,width:300,height:300,borderRadius:'50%',border:`16px double ${[C.copper,C.blue,C.mint][i]}`,background:C.paper,display:'grid',placeItems:'center',textAlign:'center',fontSize:28,fontWeight:950,...reveal(f,18+i*17)}}>{s}</div>{i<2&&<div style={{position:'absolute',left:805+i*390,top:342+(i%2)*65,fontSize:55,color:C.red}}>→</div>}</React.Fragment>)}
  <div data-final-knowledge="supplement-result" style={{position:'absolute',right:30,bottom:10}}><Stamp color={C.mint}>程序完整，方可进入补充设定</Stamp></div>
 </div></Shell>};

export const ImplementationRoleTriangleScene=()=>{const f=useCurrentFrame();return <Shell code="07" title="实施主体三角：自行、授权、委托的责任身份不同"><div data-layout="three-corner-implementation-responsibility-triangle" data-visual-anchor="role-pair" data-visual-grammar="administrative-organ-remains-the-origin-of-penalty-power,authorization-creates-an-independent-subject-while-delegation-keeps-liability-at-the-principal" data-text-treatments="label-block,external-negation,stamp" data-focal-rule="penalty-implementation-subjects" data-focal-channels="connector,contrast,spatial" style={{position:'absolute',inset:20}}>
  <svg style={{position:'absolute',inset:0,width:'100%',height:'100%'}} viewBox="0 0 1740 700"><path d="M870 70 L270 590 L1470 590 Z" fill="none" stroke={C.copper} strokeWidth="10"/><path d="M870 70 L870 590" stroke={C.red} strokeWidth="5" strokeDasharray="18 16"/></svg>
  <div data-final-knowledge="self-implementation" style={{position:'absolute',left:640,top:20,width:460,...reveal(f,5)}}><Plate title="自行实施" body="行政机关在法定职权范围内，以自己名义处罚并自行担责。" color={C.ink}/></div>
  <div data-final-knowledge="authorization-subject" style={{position:'absolute',left:60,bottom:25,width:620,...reveal(f,25)}}><Plate title="授权实施" body="法律、法规授权后，被授权组织取得行政主体资格，以自己名义独立担责。" color={C.mint}/></div>
  <div data-final-knowledge="delegation-helper" style={{position:'absolute',right:60,bottom:25,width:620,...reveal(f,45)}}><Plate title="委托实施" body="受托组织不取得主体资格；后果由委托机关承担，委托书必须向社会公布。" color={C.red}/></div>
 </div></Shell>};

export const JurisdictionArenaMapScene=()=>{const f=useCurrentFrame();return <Shell code="08" title="管辖赛区：发生地、县级起步，下放与集中都有总裁判"><div data-layout="concentric-jurisdiction-arena-with-transfer-boxes" data-visual-anchor="boundary" data-visual-grammar="implementation-and-direct-result-sites-form-the-territorial-arena,county-level-default-jurisdiction-can-shift-only-through-provincial-or-central-authority-decisions" data-text-treatments="soft-highlight,label-block,stamp" data-focal-rule="territorial-level-delegated-and-centralized-jurisdiction" data-focal-channels="enclosure,locator,connector" style={{position:'absolute',inset:0}}>
  <div data-final-knowledge="territorial-sites" style={{position:'absolute',left:520,top:20,width:700,height:650,borderRadius:'50%',border:`10px solid ${C.ink}`,background:`radial-gradient(circle,${C.paper} 0 38%,${C.gold}33 40%,${C.ivory} 41%)`,display:'grid',placeItems:'center',textAlign:'center',...reveal(f,5)}}><div><div style={{fontSize:39,fontWeight:950}}>违法行为发生地</div><div style={{fontSize:27,marginTop:16}}>实施地 ＋ 直接结果发生地</div><div style={{marginTop:55,fontSize:30,fontWeight:950,color:C.red}}>县级以上行政机关</div></div></div>
  <div data-final-knowledge="downward-transfer" style={{position:'absolute',left:20,top:80,width:450,...reveal(f,30,-30,0)}}><Plate title="管辖权下放" body="须省级政府决定；定期评估并向社会公布。" color={C.blue}/></div>
  <div data-final-knowledge="centralized-penalty" style={{position:'absolute',right:20,top:80,width:450,...reveal(f,43,30,0)}}><Plate title="集中处罚权" body="由国务院或者省级政府决定；人身自由处罚仍锁定公安及法律规定机关。" color={C.red}/></div>
  <div data-final-knowledge="jurisdiction-dispute" style={{position:'absolute',left:90,bottom:30,width:380,fontSize:24,fontWeight:850}}>管辖争议：协商不成，报共同上一级指定</div>
 </div></Shell>};

export const OrdinaryProcedureRacetrackScene=()=>{const f=useCurrentFrame();const a=[['立案','发现违法线索'],['调查','原则2名执法人员'],['审核','重大案件法制审核'],['决定','重大复杂集体讨论'],['送达','当场；否则7日']];return <Shell code="09" title="普通程序主跑道：五棒接力，一棒都不能跳"><div data-layout="five-lane-procedure-relay-track" data-visual-anchor="flow-path" data-visual-grammar="a-penalty-case-runs-from-filing-through-investigation-review-decision-and-service,procedural-rights-and-evidence-preservation-occupy-mandatory-checkpoints-on-the-track" data-text-treatments="label-block,thin-underline,soft-highlight" data-focal-rule="ordinary-administrative-penalty-procedure" data-focal-channels="connector,motion,locator" style={{position:'absolute',inset:20}}>
  <div style={{position:'absolute',left:90,right:90,top:305,height:22,background:C.ink}}/>
  {/* data-final-knowledge="stage-filing" data-final-knowledge="stage-investigation" data-final-knowledge="stage-review" data-final-knowledge="stage-decision" data-final-knowledge="stage-service" */}
  {a.map((x,i)=><div key={x[0]} data-final-knowledge={['stage-filing','stage-investigation','stage-review','stage-decision','stage-service'][i]} style={{position:'absolute',left:45+i*340,top:i%2?360:70,width:300,height:220,background:i===3?C.red:C.paper,color:i===3?C.white:C.ink,border:`5px solid ${C.ink}`,padding:20,...reveal(f,8+i*15)}}><div style={{fontSize:20,fontWeight:900}}>0{i+1}</div><div style={{fontSize:34,fontWeight:950,marginTop:8}}>{x[0]}</div><div style={{fontSize:23,lineHeight:1.4,marginTop:14}}>{x[1]}</div></div>)}
  <div data-final-knowledge="rights-checkpoint" style={{position:'absolute',left:40,bottom:5,fontSize:21}}><Stamp color={C.blue}>不出示执法证可拒绝调查；未告知并听取陈述申辩不得处罚</Stamp></div>
  <div data-final-knowledge="general-decision-deadline" style={{position:'absolute',left:690,bottom:5,fontSize:21}}><Stamp color={C.red}>一般案件自立案起90日</Stamp></div>
  <div data-final-knowledge="evidence-preservation-seven-days" style={{position:'absolute',right:30,bottom:5,fontSize:21}}><Stamp color={C.copper}>证据可能灭失/难取：负责人批准，先行登记保存7日</Stamp></div>
 </div></Shell>};

export const LegalReviewLockScene=()=>{const f=useCurrentFrame();const keys=['重大公共利益','直接关系重大权益且经听证','疑难复杂、多重大关系','法律法规规定其他情形'];return <Shell code="10" title="法制审核锁：四把钥匙齐认，未审或未通过不得决定"><div data-layout="four-key-legal-review-lock" data-visual-anchor="flow-target" data-visual-grammar="four-statutory-case-types-activate-the-legal-review-lock,a-failed-or-missing-review-blocks-the-final-penalty-decision" data-text-treatments="stamp,external-negation,label-block" data-focal-rule="mandatory-legal-review-before-major-penalties" data-focal-channels="icon,enclosure,contrast" style={{position:'absolute',inset:20}}>
  <div data-final-knowledge="review-lock" style={{position:'absolute',left:680,top:170,width:380,height:360,borderRadius:'50% 50% 18% 18%',background:C.ink,color:C.white,display:'grid',placeItems:'center',textAlign:'center'}}><div style={{fontSize:90}}>▣</div><div style={{fontSize:32,fontWeight:950}}>法制审核</div><div style={{fontSize:24,color:C.gold}}>未审核 / 未通过<br/>不得作出处罚决定</div></div>
  {/* data-final-knowledge="review-key-0" data-final-knowledge="review-key-1" data-final-knowledge="review-key-2" data-final-knowledge="review-key-3" */}
  {keys.map((x,i)=>{const p=[[40,40],[1240,40],[40,450],[1240,450]][i];return <div key={x} data-final-knowledge={`review-key-${i}`} style={{position:'absolute',left:p[0],top:p[1],width:450,height:150,background:C.paper,borderLeft:`15px solid ${[C.copper,C.blue,C.red,C.mint][i]}`,padding:22,fontSize:27,fontWeight:900,...reveal(f,10+i*13)}}>{x}</div>})}
  <div data-final-knowledge="review-exam" style={{position:'absolute',left:560,bottom:10,width:620,textAlign:'center',fontSize:23}}>初次从事行政处罚决定法制审核人员，应当通过法律职业资格考试</div>
 </div></Shell>};

export const SummaryThresholdScalesScene=()=>{const f=useCurrentFrame();return <Shell code="11" title="简易程序双秤：一般罚与治安罚的当场阈值不同"><div data-layout="paired-summary-procedure-balance-scales" data-visual-anchor="comparison-axis" data-visual-grammar="general-and-public-security-summary-procedures-weigh-different-fine-thresholds,both-scales-also-admit-warning-while-service-remains-a-separate-question" data-text-treatments="soft-highlight,thin-underline,external-negation" data-focal-rule="summary-procedure-thresholds" data-focal-channels="contrast,icon,spatial" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:70,padding:'20px 70px'}}>
  <div data-final-knowledge="general-summary-threshold" style={{position:'relative',height:570,...reveal(f,5)}}><div style={{position:'absolute',left:310,top:40,width:14,height:330,background:C.ink}}/><div style={{position:'absolute',left:90,right:90,top:180,height:12,background:C.copper}}/><div style={{position:'absolute',left:80,top:210,width:250,height:190,background:C.paper,border:`5px solid ${C.blue}`,padding:20,textAlign:'center'}}><b style={{fontSize:31}}>公民</b><div style={{fontSize:37,color:C.blue,fontWeight:950}}>≤ 200元</div></div><div style={{position:'absolute',right:60,top:210,width:260,height:190,background:C.paper,border:`5px solid ${C.blue}`,padding:20,textAlign:'center'}}><b style={{fontSize:31}}>单位</b><div style={{fontSize:37,color:C.blue,fontWeight:950}}>≤ 3000元</div></div><div style={{position:'absolute',left:200,bottom:20,fontSize:29,fontWeight:950}}>一般处罚 ＋ 警告</div></div>
  <div data-final-knowledge="security-summary-threshold" style={{position:'relative',height:570,...reveal(f,28)}}><div style={{position:'absolute',left:310,top:40,width:14,height:330,background:C.ink}}/><div style={{position:'absolute',left:90,right:90,top:180,height:12,background:C.red}}/><div style={{position:'absolute',left:170,top:210,width:330,height:190,background:C.paper,border:`5px solid ${C.red}`,padding:20,textAlign:'center'}}><b style={{fontSize:31}}>治安处罚</b><div style={{fontSize:40,color:C.red,fontWeight:950}}>≤ 500元</div><div style={{fontSize:23}}>或者警告</div></div><div style={{position:'absolute',left:140,bottom:20,fontSize:25,fontWeight:900}}>当场处罚 ≠ 必然当场送达</div></div>
 </div></Shell>};

export const HearingScopeAmphitheaterScene=()=>{const f=useCurrentFrame();return <Shell code="12" title="听证剧场入场券：范围不是一张统一票"><div data-layout="split-tier-hearing-amphitheater" data-visual-anchor="comparison-axis" data-visual-grammar="general-penalty-and-public-security-cases-enter-through-different-hearing-tiers,minor-detention-cases-open-a-special-ticket-only-when-a-minor-may-actually-serve-detention" data-text-treatments="label-block,stamp,soft-highlight" data-focal-rule="hearing-scope-for-general-and-security-penalties" data-focal-channels="contrast,enclosure,locator" style={{position:'absolute',inset:0}}>
  <div style={{position:'absolute',left:760,top:240,width:240,height:180,background:C.ink,color:C.white,clipPath:'polygon(50% 0,100% 35%,82% 100%,18% 100%,0 35%)',display:'grid',placeItems:'center',textAlign:'center',fontSize:34,fontWeight:950}}>听证<br/>主舞台</div>
  <div data-final-knowledge="general-hearing-scope" style={{position:'absolute',left:40,top:40,width:620,height:550,border:`8px solid ${C.blue}`,borderRadius:'52% 52% 0 0',padding:'55px 38px',background:C.paper,...reveal(f,8)}}><div style={{fontSize:34,fontWeight:950,color:C.blue}}>一般行政处罚</div><div style={{display:'flex',flexWrap:'wrap',gap:14,marginTop:28}}><Chip color={C.blue}>较大罚款 / 没收</Chip><Chip color={C.blue}>降级 / 吊证</Chip><Chip color={C.blue}>停产停业 / 关闭</Chip><Chip color={C.blue}>限制从业</Chip><Chip color={C.ink}>其他较重处罚</Chip></div></div>
  <div data-final-knowledge="security-hearing-scope" style={{position:'absolute',right:40,top:40,width:620,height:550,border:`8px solid ${C.red}`,borderRadius:'52% 52% 0 0',padding:'55px 38px',background:C.paper,...reveal(f,28)}}><div style={{fontSize:34,fontWeight:950,color:C.red}}>治安管理处罚</div><div style={{fontSize:29,fontWeight:950,marginTop:25}}>“4 挺 吊”</div><div style={{display:'flex',flexWrap:'wrap',gap:14,marginTop:16}}><Chip color={C.red}>≥ 4000元罚款</Chip><Chip color={C.red}>责令停业整顿</Chip><Chip color={C.red}>吊销许可证件</Chip></div><div style={{marginTop:30,borderTop:`4px solid ${C.red}`,paddingTop:18,fontSize:24}}><b style={{color:C.red}}>未成年人</b> ＋ <u>可能执行拘留</u><br/>告知本人及监护人</div></div>
  <div data-final-knowledge="hearing-request-rule" style={{position:'absolute',left:660,bottom:5,width:440,textAlign:'center'}}><Stamp>告知 ＋ 申请 → 举行</Stamp></div>
 </div></Shell>};

export const HearingProcedureConsoleScene=()=>{const f=useCurrentFrame();const controls=[['5日','当事人申请'],['7日前','机关通知'],['公开','法定例外：国家秘密、商业秘密、个人隐私；未成年人治安听证不公开'],['回避','主持人非本案调查人员'],['1—2名','委托代理人'],['依笔录','据听证笔录作出决定']];return <Shell code="13" title="听证控制台：申请、通知、公开、回避、笔录各自归位"><div data-layout="six-control-hearing-switchboard" data-visual-anchor="flow-path" data-visual-grammar="hearing-controls-activate-in-request-notice-session-and-decision-order,absence-or-withdrawal-terminates-the-hearing-while-costs-remain-with-the-organ" data-text-treatments="label-block,thin-underline,stamp" data-focal-rule="administrative-hearing-procedure" data-focal-channels="connector,locator,motion" style={{position:'absolute',inset:15}}>
  <div style={{position:'absolute',left:80,right:80,top:310,height:16,background:C.ink}}/>
  {/* data-final-knowledge="hearing-control-0" data-final-knowledge="hearing-control-1" data-final-knowledge="hearing-control-2" data-final-knowledge="hearing-control-3" data-final-knowledge="hearing-control-4" data-final-knowledge="hearing-control-5" */}
  {controls.map((x,i)=><div key={x[0]} data-final-knowledge={`hearing-control-${i}`} style={{position:'absolute',left:25+i*285,top:i%2?365:55,width:260,minHeight:205,background:C.paper,border:`4px solid ${[C.red,C.gold,C.blue,C.copper,C.mint,C.ink][i]}`,padding:17,...reveal(f,7+i*11)}}><div style={{fontSize:34,fontWeight:950,color:[C.red,C.gold,C.blue,C.copper,C.mint,C.ink][i]}}>{x[0]}</div><div style={{fontSize:22,lineHeight:1.4,marginTop:10}}>{x[1]}</div></div>)}
  <div data-final-knowledge="hearing-termination" style={{position:'absolute',left:90,bottom:0,fontSize:22}}><Stamp color={C.red}>无正当理由不出席 / 中途退出 → 听证终止</Stamp></div>
  <div data-final-knowledge="hearing-cost" style={{position:'absolute',right:90,bottom:0,fontSize:22}}><Stamp color={C.mint}>听证费用由行政机关承担；无“20日内组织”期限</Stamp></div>
 </div></Shell>};

export const ParticipationRuleScoreboardScene=()=>{const f=useCurrentFrame();return <Shell code="14" title="实施规则记分牌：公开、参与、人数与应急从重同时计分"><div data-layout="asymmetric-four-quadrant-rule-scoreboard" data-visual-anchor="comparison-axis" data-visual-grammar="four-implementation-principles-occupy-independent-score-zones,publicity-and-participation-protect-the-party-while-staffing-and-emergency-rules-govern-enforcement" data-text-treatments="soft-highlight,external-negation,label-block" data-focal-rule="general-rules-for-penalty-implementation" data-focal-channels="contrast,spatial,enclosure" style={{position:'absolute',inset:15}}>
  <div data-final-knowledge="publicity-rule" style={{position:'absolute',left:20,top:20,width:730,height:285,background:C.paper,border:`5px solid ${C.blue}`,padding:25,...reveal(f,5)}}><div style={{fontSize:35,fontWeight:950,color:C.blue}}>公开</div><div style={{display:'flex',flexWrap:'wrap',gap:12,marginTop:22}}><Chip color={C.blue}>机关</Chip><Chip color={C.blue}>依据</Chip><Chip color={C.blue}>程序</Chip><Chip color={C.blue}>救济</Chip><Chip color={C.ink}>有社会影响：决定公开</Chip><Chip color={C.red}>状态变化：3日撤回并说明</Chip></div></div>
  <div data-final-knowledge="participation-rule" style={{position:'absolute',right:20,top:20,width:920,height:205,background:C.paper,borderLeft:`18px solid ${C.mint}`,padding:24,...reveal(f,20)}}><div style={{fontSize:34,fontWeight:950,color:C.mint}}>参与</div><div style={{display:'flex',gap:18,alignItems:'center',marginTop:18}}><Chip color={C.mint} invert>告知</Chip><Arrow color={C.mint}/><Chip color={C.mint} invert>陈述 · 申辩</Chip><Arrow color={C.mint}/><Chip color={C.red}>不得加重</Chip><span style={{fontSize:22}}>明确放弃除外</span></div></div>
  <div data-final-knowledge="staffing-rule" style={{position:'absolute',right:20,top:255,width:920,height:260,background:C.paper,border:`5px solid ${C.copper}`,padding:25,...reveal(f,35)}}><div style={{display:'flex',alignItems:'center',gap:28}}><div style={{fontSize:92,fontWeight:950,color:C.copper}}>2</div><div><div style={{fontSize:34,fontWeight:950}}>调查取证人员</div><div style={{fontSize:24,marginTop:12}}>原则不少于2名 · 具有行政执法资格</div></div></div><div style={{marginTop:25,borderTop:`4px solid ${C.copper}`,paddingTop:16,fontSize:24,fontWeight:900}}>先出示执法证件，再进入调查</div></div>
  <div data-final-knowledge="emergency-rule" style={{position:'absolute',left:20,bottom:20,width:730,height:315,background:C.red,color:C.white,padding:30,clipPath:'polygon(0 0,90% 0,100% 18%,100% 100%,10% 100%,0 82%)',...reveal(f,48)}}><div style={{fontSize:36,fontWeight:950}}>突发事件</div><div style={{fontSize:26,lineHeight:1.6,marginTop:18}}>违反突发事件应对措施<br/>依法 <u>快速</u>、<u>从重</u> 处罚</div></div>
 </div></Shell>};

export const LimitationLiabilityDialScene=()=>{const f=useCurrentFrame();return <Shell code="15" title="追责表盘：时效、责任能力与一事不二罚分三层判断"><div data-layout="concentric-limitation-and-liability-dial" data-visual-anchor="timeline-gate" data-visual-grammar="limitation-periods-occupy-an-outer-time-ring-responsibility-exceptions-an-inner-ring,the-center-enforces-one-act-no-two-fines-and-the-higher-fine-rule" data-text-treatments="soft-highlight,stamp,external-negation" data-focal-rule="limitation-nonpunishment-and-double-fine-rules" data-focal-channels="locator,enclosure,contrast" style={{position:'absolute',inset:0}}>
  <div data-final-knowledge="limitation-rings" style={{position:'absolute',left:500,top:5,width:740,height:670,borderRadius:'50%',border:`18px solid ${C.ink}`,background:`conic-gradient(${C.blue} 0 34%,${C.red} 34% 56%,${C.gold} 56% 78%,${C.mint} 78%)`,display:'grid',placeItems:'center',...reveal(f,5)}}><div style={{width:500,height:430,borderRadius:'50%',background:C.paper,border:`9px solid ${C.ivory}`,display:'grid',placeItems:'center',textAlign:'center',padding:45}}><div><div style={{fontSize:34,fontWeight:950}}>处罚时效</div><div style={{fontSize:28,lineHeight:1.6,marginTop:10}}>一般 <b>2年</b> ｜ 治安 <b>6个月</b><br/>生命健康 / 金融安全且有危害后果 <b>5年</b><br/>连续、继续行为从终了日起算</div></div></div></div>
  <div data-final-knowledge="nonpunishment-capacity" style={{position:'absolute',left:15,top:65,width:430,background:C.paper,borderTop:`12px solid ${C.mint}`,padding:22}}><div style={{fontSize:31,fontWeight:950,color:C.mint}}>责任能力筛选</div><div style={{display:'grid',gap:11,marginTop:18}}><Chip color={C.mint}>＜14：不处罚</Chip><Chip color={C.mint}>14—18：从轻 / 减轻</Chip><Chip color={C.blue}>精神、智力障碍：按辨认控制能力</Chip><Chip color={C.gold}>初次轻微＋及时改正：依法不罚</Chip></div></div>
  <div data-final-knowledge="one-act-one-fine" style={{position:'absolute',right:15,top:65,width:430,background:C.paper,borderTop:`12px solid ${C.red}`,padding:22}}><div style={{fontSize:31,fontWeight:950,color:C.red}}>一事不二罚</div><div style={{fontSize:55,fontWeight:950,textAlign:'center',marginTop:25}}>1 行为</div><div style={{display:'flex',justifyContent:'center',gap:12,marginTop:18}}><Chip color={C.red}>不得两次以上罚款</Chip></div><div style={{borderTop:`4px solid ${C.red}`,paddingTop:15,marginTop:20,fontSize:23,textAlign:'center'}}>多个规范都有罚款 → <b>取高者</b></div></div>
  <div data-final-knowledge="crime-transfer" style={{position:'absolute',left:80,bottom:10,width:420}}><Stamp color={C.copper}>先发现犯罪：直接移送，不先处罚</Stamp></div>
  <div data-final-knowledge="offset-afterward" style={{position:'absolute',right:80,bottom:10,width:470}}><Stamp color={C.blue}>处罚后才发现犯罪：拘留、罚款依法折抵</Stamp></div>
 </div></Shell>};

export const EvidenceMonitoringWallScene=()=>{const f=useCurrentFrame();const types=['书证','物证','视听资料','电子数据','证人证言','当事人陈述','鉴定意见','勘验/现场笔录'];return <Shell code="16" title="证物墙与电子监控：八类证据先入库，设备证据再过三审"><div data-layout="evidence-pinwall-with-monitoring-review-lens" data-visual-anchor="concept-icon" data-visual-grammar="eight-statutory-evidence-types-pin-to-a-common-proof-wall,electronic-monitoring-records-pass-setting-recording-and-content-review-before-use" data-text-treatments="label-block,external-negation,thin-underline" data-focal-rule="administrative-penalty-evidence-system" data-focal-channels="icon,connector,contrast" style={{position:'absolute',inset:10}}>
  <div data-final-knowledge="eight-evidence-types" style={{position:'absolute',left:20,top:20,width:970,height:590,background:C.ink,padding:30,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:18}}>{types.map((x,i)=><div key={x} style={{background:C.paper,borderTop:`10px solid ${[C.gold,C.copper,C.blue,C.mint][i%4]}`,display:'grid',placeItems:'center',textAlign:'center',fontSize:27,fontWeight:900,...reveal(f,5+i*7)}}>{x}</div>)}</div>
  <div data-final-knowledge="monitoring-review" style={{position:'absolute',right:20,top:20,width:650,height:405,borderRadius:'50%',border:`13px solid ${C.blue}`,background:C.paper,padding:'48px 48px',textAlign:'center',...reveal(f,35)}}><div style={{fontSize:62}}>◉</div><div style={{fontSize:30,fontWeight:950}}>电子监控三审</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginTop:20}}><Chip color={C.blue}>设置<br/>法制＋技术审核</Chip><Chip color={C.copper}>场所<br/>合理·标志·公开</Chip><Chip color={C.mint}>记录<br/>内容再审核</Chip></div><div style={{marginTop:18}}><Stamp color={C.red}>不合格 → 不得作证据</Stamp></div></div>
  <div data-final-knowledge="evidence-exclusions" style={{position:'absolute',right:20,bottom:20,width:650,height:160,display:'flex',gap:12,alignItems:'stretch'}}><Chip color={C.red}>非法取得<br/>不得作为根据</Chip><Chip color={C.red}>监控不能替代<br/>查询·陈述·申辩</Chip><Chip color={C.ink}>文字或音像记录归档<br/>并非必须全音像</Chip></div>
 </div></Shell>};

export const PublicSecuritySanctionVaultScene=()=>{const f=useCurrentFrame();return <Shell code="17" title="治安处罚保险库：处罚、收缴、追缴是三只不同抽屉"><div data-layout="three-drawer-public-security-sanction-vault" data-visual-anchor="document-fork" data-visual-grammar="public-security-outcomes-separate-penalties-confiscated-tools-and-recovered-proceeds,foreign-national-exit-measures-attach-only-to-the-penalty-drawer" data-text-treatments="label-block,stamp,thin-underline" data-focal-rule="public-security-penalties-confiscation-and-recovery" data-focal-channels="enclosure,contrast,icon" style={{position:'absolute',inset:20}}>
  <div style={{position:'absolute',left:420,top:0,width:900,height:650,background:C.ink,padding:34}}>
    <div data-final-knowledge="security-penalties" style={{height:170,background:C.paper,borderLeft:`18px solid ${C.red}`,padding:20,...reveal(f,6)}}><div style={{fontSize:31,fontWeight:950,color:C.red}}>处罚抽屉</div><div style={{display:'flex',flexWrap:'wrap',gap:9,marginTop:13}}><Chip color={C.red}>警告</Chip><Chip color={C.red}>罚款</Chip><Chip color={C.red}>拘留</Chip><Chip color={C.red}>吊销公安许可证</Chip><Chip color={C.ink}>外国人：限期出境 / 驱逐</Chip></div></div>
    <div data-final-knowledge="security-confiscation" style={{height:170,background:C.paper,borderLeft:`18px solid ${C.copper}`,padding:20,marginTop:22,...reveal(f,25)}}><div style={{fontSize:31,fontWeight:950,color:C.copper}}>收缴抽屉</div><div style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:15}}><Chip color={C.copper}>违禁品</Chip><Chip color={C.copper}>赌具 · 赌资</Chip><Chip color={C.copper}>本人所有</Chip><Chip color={C.red}>直接用于违法的工具</Chip></div></div>
    <div data-final-knowledge="security-recovery" style={{height:170,background:C.paper,borderLeft:`18px solid ${C.mint}`,padding:20,marginTop:22,...reveal(f,44)}}><div style={{fontSize:31,fontWeight:950,color:C.mint}}>追缴抽屉</div><div style={{display:'flex',alignItems:'center',gap:12,marginTop:20}}><Chip color={C.mint}>违法所得</Chip><Arrow color={C.mint}/><Chip color={C.mint}>先退被侵害人</Chip><span style={{fontSize:22}}>无人可退</span><Arrow color={C.copper}/><Chip color={C.copper}>处理后入国库</Chip></div></div>
  </div>
  <div data-final-knowledge="security-nonpunishment" style={{position:'absolute',left:10,top:35,width:360,background:C.paper,borderTop:`10px solid ${C.blue}`,padding:18}}><div style={{fontSize:29,fontWeight:950,color:C.blue}}>不处罚</div><div style={{display:'flex',flexWrap:'wrap',gap:8,marginTop:12}}><Chip color={C.blue}>＜14</Chip><Chip color={C.blue}>无责任能力</Chip><Chip color={C.blue}>过6个月</Chip><Chip color={C.blue}>正当防卫</Chip></div></div>
  <div data-final-knowledge="security-case-controls" style={{position:'absolute',left:10,bottom:15,width:360,background:C.paper,border:`5px solid ${C.red}`,padding:18}}><div style={{fontSize:28,fontWeight:950,color:C.red}}>治安办案控制</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9,marginTop:12}}><Chip color={C.red}>30+30+30</Chip><Chip color={C.red}>送达2日</Chip><Chip color={C.ink}>仅本人陈述</Chip><Chip color={C.red}>不得处罚</Chip></div></div>
  <div data-final-knowledge="special-law-procedure" style={{position:'absolute',right:10,top:160,width:360,background:C.ink,color:C.white,padding:24,textAlign:'center'}}><div style={{fontSize:30,fontWeight:950,color:C.gold}}>枪爆案件</div><div style={{display:'grid',gap:12,marginTop:20}}><Chip color={C.gold} invert>实体：特别法</Chip><Chip color={C.red} invert>程序：治安法</Chip></div></div>
 </div></Shell>};

export const SummonsInterviewClocksScene=()=>{const f=useCurrentFrame();return <Shell code="18" title="传唤与询问时钟：对象、批准人与时间上限逐格锁定"><div data-layout="dual-clock-summons-interview-control" data-visual-anchor="timeline-gate" data-visual-grammar="summons-authority-and-notice-rules-occupy-the-left-clock,interview-duration-escalates-from-eight-to-twelve-to-twenty-four-hours-on-the-right-clock" data-text-treatments="soft-highlight,label-block,thin-underline" data-focal-rule="public-security-summons-and-interview-rules" data-focal-channels="locator,contrast,motion" style={{position:'absolute',inset:10}}>
  <div data-final-knowledge="summons-rules" style={{position:'absolute',left:30,top:20,width:760,height:590,borderRadius:'50%',border:`15px solid ${C.copper}`,background:C.paper,padding:'70px 70px',...reveal(f,5)}}><div style={{fontSize:39,fontWeight:950}}>传唤</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:13,marginTop:24}}><Chip color={C.copper}>对象<br/>违法行为人</Chip><Chip color={C.copper}>传唤证 / 强制传唤<br/>办案部门负责人批准</Chip><Chip color={C.blue}>现场发现<br/>警察证＋口头传唤</Chip><Chip color={C.blue}>口头传唤<br/>记入笔录</Chip><Chip color={C.red}>告知<br/>原因＋依据</Chip><Chip color={C.mint}>同步<br/>通知家属</Chip></div></div>
  <div data-final-knowledge="interview-hours" style={{position:'absolute',right:30,top:20,width:760,height:590,borderRadius:'50%',border:`15px solid ${C.blue}`,background:`conic-gradient(${C.mint} 0 33%,${C.gold} 33% 66%,${C.red} 66%)`,padding:55,...reveal(f,28)}}><div style={{width:'100%',height:'100%',borderRadius:'50%',background:C.paper,display:'grid',placeItems:'center',textAlign:'center'}}><div><div style={{fontSize:39,fontWeight:950}}>询问查证</div><div style={{fontSize:30,lineHeight:1.8,marginTop:18}}><b style={{color:C.mint}}>8小时</b> 一般<br/><b style={{color:C.gold}}>12小时</b> 人数众多 / 身份不明<br/><b style={{color:C.red}}>24小时</b> 复杂且可能拘留</div></div></div></div>
  <div data-final-knowledge="interview-protections" style={{position:'absolute',left:150,right:150,bottom:0,display:'flex',justifyContent:'center',gap:12}}><Chip color={C.red}>办案场所：全程录像</Chip><Chip color={C.gold}>未成年人：监护人 / 合适成年人</Chip><Chip color={C.blue}>聋哑辅助 · 语言翻译</Chip><Chip color={C.mint}>远程询问与宣读：全程录像</Chip></div>
 </div></Shell>};

export const InspectionSeizureScene=()=>{const f=useCurrentFrame();return <Shell code="19" title="检查、扣押、辨认现场：证件、批准与对象边界各不相同"><div data-layout="three-panel-investigation-crime-scene" data-visual-anchor="comparison-axis" data-visual-grammar="inspection-seizure-and-identification-occupy-distinct-investigation-zones,home-entry-and-property-control-require-stricter-documents-and-approval-than-person-or-object-checks" data-text-treatments="label-block,external-negation,stamp" data-focal-rule="public-security-inspection-seizure-identification" data-focal-channels="contrast,enclosure,icon" style={{display:'grid',gridTemplateColumns:'1.05fr 1.15fr .8fr',gap:26,padding:15}}>
  <div data-final-knowledge="inspection-rules" style={{background:C.paper,border:`6px solid ${C.blue}`,padding:22,...reveal(f,5)}}><div style={{fontSize:52}}>⌂</div><div style={{fontSize:33,fontWeight:950,color:C.blue}}>检查</div><div style={{display:'grid',gap:10,marginTop:15}}><Chip color={C.blue}>一般：2名警察＋证件</Chip><Chip color={C.red}>住所：始终要检查证</Chip><Chip color={C.gold}>紧急场所：警察证＋全程录像</Chip><Chip color={C.mint}>物品 / 人身：不需检查证</Chip><Chip color={C.ink}>女性身体：女性工作人员或医师</Chip></div></div>
  <div data-final-knowledge="seizure-rules" style={{background:C.paper,border:`6px solid ${C.red}`,padding:22,...reveal(f,25)}}><div style={{fontSize:52}}>▤</div><div style={{fontSize:33,fontWeight:950,color:C.red}}>扣押</div><div style={{display:'grid',gap:10,marginTop:15}}><Chip color={C.red}>只扣案件有关证据物品</Chip><Chip color={C.mint}>被侵害人 / 善意第三人财产：原则只登记</Chip><Chip color={C.gold}>需鉴定：例外可扣</Chip><Chip color={C.copper}>负责人批准；紧急 / 价值小可先扣后补</Chip><Chip color={C.red}>当场扣押：全程录像</Chip></div></div>
  <div data-final-knowledge="identification-record" style={{background:C.ink,color:C.white,padding:22,...reveal(f,45)}}><div style={{fontSize:52}}>◎</div><div style={{fontSize:32,fontWeight:950,color:C.gold}}>辨认与采样</div><div style={{display:'grid',gap:10,marginTop:18}}><Chip color={C.gold} invert>辨认：制作笔录</Chip><Chip color={C.blue} invert>调查取证：原则2人</Chip><Chip color={C.copper} invert>采样：办案部门负责人批准</Chip><Chip color={C.mint} invert>被侵害人须同意</Chip><Chip color={C.red} invert>违法行为人无需同意</Chip><Chip color={C.white}>不得重复采集</Chip></div></div>
 </div></Shell>};

export const SingleOfficerCameraWallScene=()=>{const f=useCurrentFrame();const cams=[['办案场所询问','全程录像'],['一人询问/扣押/辨认/调解','全程录像'],['紧急无证场所检查','全程录像'],['当场扣押','全程录像'],['无异议的一人当场处罚','全程录像'],['远程视频询问与宣读','全程录像']];return <Shell code="20" title="六机位监控墙：一人执法与特殊现场必须留下完整影像"><div data-layout="six-feed-synchronous-recording-monitor-wall" data-visual-anchor="concept-icon" data-visual-grammar="six-public-security-procedures-feed-a-synchronous-recording-wall,missing-damaged-or-lost-required-recordings-disable-the-related-evidence" data-text-treatments="label-block,stamp,external-negation" data-focal-rule="mandatory-synchronous-audio-video-recording" data-focal-channels="icon,enclosure,contrast" style={{position:'absolute',inset:10,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gridTemplateRows:'repeat(2,1fr)',gap:22}}>
  {/* data-final-knowledge="camera-0" data-final-knowledge="camera-1" data-final-knowledge="camera-2" data-final-knowledge="camera-3" data-final-knowledge="camera-4" data-final-knowledge="camera-5" */}
  {cams.map((x,i)=><div key={x[0]} data-final-knowledge={`camera-${i}`} style={{background:C.ink,color:C.white,border:`7px solid ${i===1||i===4?C.red:C.blue}`,padding:22,position:'relative',...reveal(f,5+i*9)}}><div style={{position:'absolute',right:18,top:15,width:16,height:16,borderRadius:'50%',background:C.red}}/><div style={{fontSize:22,color:C.gold}}>CAM 0{i+1} · REC</div><div style={{fontSize:31,fontWeight:950,marginTop:32}}>{x[0]}</div><div style={{position:'absolute',left:22,bottom:20,fontSize:24,color:C.mint}}>{x[1]}{i===4?'；24小时内备案':''}</div></div>)}
  <div data-final-knowledge="recording-evidence-consequence" style={{position:'absolute',left:430,right:430,bottom:-5,textAlign:'center'}}><Stamp color={C.red}>依法必须录像却未录像，或资料损毁、丢失：相关证据不得作为处罚根据</Stamp></div>
 </div></Shell>};

export const MediationPrivacyForkScene=()=>{const f=useCurrentFrame();return <Shell code="21" title="调解与隐私分叉：和解能消行政后果，记录仍须封存"><div data-layout="mediation-outcome-river-with-privacy-vault" data-visual-anchor="document-fork" data-visual-grammar="minor-private-dispute-cases-fork-into-success-and-failure-outcomes,record-sealing-and-personal-information-protection-form-a-separate-permanent-vault" data-text-treatments="soft-highlight,stamp,label-block" data-focal-rule="security-mediation-record-sealing-and-information-protection" data-focal-channels="connector,enclosure,contrast" style={{position:'absolute',inset:15}}>
  <div data-final-knowledge="mediation-entry" style={{position:'absolute',left:30,top:230,width:390,height:220,background:C.copper,color:C.white,padding:28,clipPath:'polygon(0 0,88% 0,100% 50%,88% 100%,0 100%)',...reveal(f,5)}}><div style={{fontSize:33,fontWeight:950}}>调解入口</div><div style={{display:'grid',gap:10,marginTop:16}}><Chip color={C.white}>民间纠纷</Chip><Chip color={C.white}>打架 / 损财等</Chip><Chip color={C.gold} invert>情节较轻</Chip></div></div>
  <div data-final-knowledge="mediation-success" style={{position:'absolute',left:560,top:40,width:560,height:270,background:C.paper,border:`6px solid ${C.mint}`,padding:22,...reveal(f,25)}}><div style={{fontSize:32,fontWeight:950,color:C.mint}}>达成并履行</div><div style={{display:'flex',alignItems:'center',gap:10,marginTop:18}}><Chip color={C.mint}>行政：不处罚</Chip><Chip color={C.blue}>民事：按协议</Chip></div><div style={{marginTop:18,borderTop:`4px solid ${C.mint}`,paddingTop:15,fontSize:22}}>处理决定前：自行和解 / 人民调解 → 履行 → 书面申请 → 公安认可</div></div>
  <div data-final-knowledge="mediation-failure" style={{position:'absolute',left:560,bottom:35,width:560,height:230,background:C.paper,border:`6px solid ${C.red}`,padding:22,...reveal(f,42)}}><div style={{fontSize:32,fontWeight:950,color:C.red}}>未达成 / 不履行</div><div style={{display:'flex',alignItems:'center',gap:10,marginTop:25}}><Chip color={C.red}>行政：依法处理</Chip><Arrow/><Chip color={C.blue}>民事：告知起诉</Chip></div></div>
  <div data-final-knowledge="privacy-vault" style={{position:'absolute',right:25,top:80,width:500,height:500,background:C.ink,color:C.white,borderRadius:'45% 45% 8% 8%',padding:'58px 42px',textAlign:'center',...reveal(f,55)}}><div style={{fontSize:62}}>▣</div><div style={{fontSize:31,fontWeight:950,color:C.gold}}>记录与信息保险库</div><div style={{display:'grid',gap:12,marginTop:24}}><Chip color={C.gold} invert>治安违法记录：封存</Chip><Chip color={C.blue} invert>法定查询：例外＋保密</Chip><Chip color={C.red} invert>个人信息 / 样本：限办案用途</Chip><Chip color={C.red}>不得出售或提供</Chip></div></div>
 </div></Shell>};

export const FineExecutionSettlementChainScene=()=>{const f=useCurrentFrame();return <Shell code="22" title="罚款结算链：决定、收缴、归库分离，逾期再进入强制端"><div data-layout="fine-payment-treasury-and-enforcement-chain" data-visual-anchor="flow-path" data-visual-grammar="the-deciding-organ-hands-payment-to-bank-or-electronic-collection-before-treasury-deposit,nonpayment-splits-into-a-three-percent-surcharge-and-direct-or-court-enforcement" data-text-treatments="label-block,thin-underline,stamp" data-focal-rule="fine-execution-and-enforcement" data-focal-channels="connector,motion,contrast" style={{position:'absolute',inset:15}}>
  <div style={{display:'flex',alignItems:'center',gap:24,marginTop:70}}>
    <div data-final-knowledge="fine-decision" style={{width:340,...reveal(f,5)}}><Plate title="行政机关" body="作出处罚决定；罚没收入不得与机关或人员考核考评挂钩。" color={C.red}/></div><Arrow/>
    <div data-final-knowledge="fine-payment" style={{width:390,...reveal(f,22)}}><Plate title="15日缴款" body="到指定银行或通过电子支付系统缴纳；决定者与收缴者分离。" color={C.blue}/></div><Arrow/>
    <div data-final-knowledge="treasury-deposit" style={{width:340,...reveal(f,39)}}><Plate title="国库" body="任何机关、个人不得截留、私分；财政部门不得返还处罚机关。" color={C.mint}/></div>
  </div>
  <div data-final-knowledge="hardship-installment" style={{position:'absolute',left:60,bottom:15,width:520}}><Plate title="经济困难" body="当事人申请＋行政机关批准，可以暂缓或分期缴纳。" color={C.gold}/></div>
  <div data-final-knowledge="fine-surcharge" style={{position:'absolute',left:650,bottom:15,width:520}}><Plate title="按日3%加处罚款" body="累计不超过罚款本金；行政复议、诉讼期间不计算。" color={C.copper}/></div>
  <div data-final-knowledge="fine-enforcement" style={{position:'absolute',right:60,bottom:15,width:520}}><Plate title="强制执行" body="有权机关可直接强制；无权机关只能申请法院强制执行。" color={C.red}/></div>
 </div></Shell>};

export const DetentionSuspensionAirlockScene=()=>{const f=useCurrentFrame();const locks=[['触发事由','复议/诉讼，或升学考试、子女出生、近亲属病危死亡等'],['主动申请','被处罚人提出'],['无社会危险','公安机关作出风险判断'],['担保','保证人，或每日200元保证金']];return <Shell code="23" title="拘留暂缓四锁：四项同时解开，门禁才放行"><div data-layout="four-lock-detention-suspension-airlock" data-visual-anchor="flow-target" data-visual-grammar="pre-execution-suspension-opens-only-when-four-cumulative-locks-release,temporary-exit-during-execution-reuses-risk-and-security-locks-but-excludes-time-outside-from-the-term" data-text-treatments="label-block,stamp,thin-underline" data-focal-rule="suspension-of-administrative-detention" data-focal-channels="icon,enclosure,motion" style={{position:'absolute',inset:10}}>
  <div data-final-knowledge="detention-airlock" style={{position:'absolute',left:650,top:60,width:440,height:520,background:C.ink,color:C.white,borderRadius:'48% 48% 8% 8%',display:'grid',placeItems:'center',textAlign:'center'}}><div><div style={{fontSize:110}}>▣</div><div style={{fontSize:36,fontWeight:950}}>拘留所门禁</div><div style={{fontSize:24,color:C.gold,marginTop:16}}>作出决定的公安机关<br/>送拘留所执行</div></div></div>
  {/* data-final-knowledge="suspension-lock-0" data-final-knowledge="suspension-lock-1" data-final-knowledge="suspension-lock-2" data-final-knowledge="suspension-lock-3" */}
  {locks.map((x,i)=>{const p=[[25,35],[25,390],[1275,35],[1275,390]][i];return <div key={x[0]} data-final-knowledge={`suspension-lock-${i}`} style={{position:'absolute',left:p[0],top:p[1],width:410,height:235,background:C.paper,border:`6px solid ${[C.blue,C.copper,C.red,C.mint][i]}`,padding:22,...reveal(f,8+i*13)}}><div style={{width:42,height:34,border:`6px solid ${C.ink}`,borderTop:'none',position:'relative',marginBottom:8}}><div style={{position:'absolute',left:7,top:-28,width:18,height:28,border:`6px solid ${C.ink}`,borderBottom:'none',borderRadius:'18px 18px 0 0'}}/></div><div style={{fontSize:30,fontWeight:950,color:[C.blue,C.copper,C.red,C.mint][i]}}>{x[0]}</div><div style={{fontSize:22,lineHeight:1.4,marginTop:8}}>{x[1]}</div></div>})}
  <div data-final-knowledge="detention-combined-limit" style={{position:'absolute',left:80,bottom:0}}><Stamp color={C.red}>多种拘留分别决定、合并执行，最长20日</Stamp></div>
  <div data-final-knowledge="temporary-exit" style={{position:'absolute',right:60,bottom:0}}><Stamp color={C.blue}>执行中出所：考生危亡＋申请＋无风险＋担保；出所时间不计入拘留期</Stamp></div>
 </div></Shell>};

export const DetentionNonexecutionScreenScene=()=>{const f=useCurrentFrame();return <Shell code="24" title="拘留不执行筛网：孕妇绝对，其余三类保留例外孔"><div data-layout="age-status-detention-nonexecution-sieve" data-visual-anchor="boundary" data-visual-grammar="four-protected-statuses-are-screened-before-detention-execution,pregnancy-and-nursing-create-an-absolute-bar-while-age-groups-can-pass-through-severity-or-repeat-offense-exceptions" data-text-treatments="external-negation,soft-highlight,stamp" data-focal-rule="nonexecution-of-public-security-detention" data-focal-channels="contrast,enclosure,locator" style={{position:'absolute',inset:10}}>
  <div style={{position:'absolute',left:100,right:100,top:270,height:24,background:`repeating-linear-gradient(90deg,${C.ink} 0 30px,transparent 30px 50px)`}}/>
  <div data-final-knowledge="absolute-nonexecution" style={{position:'absolute',left:600,top:10,width:540,height:230,background:C.red,color:C.white,padding:27,clipPath:'polygon(8% 0,92% 0,100% 20%,92% 100%,8% 100%,0 20%)',textAlign:'center',...reveal(f,5)}}><div style={{fontSize:34,fontWeight:950}}>绝对不执行</div><div style={{fontSize:27,lineHeight:1.55,marginTop:15}}>怀孕，或哺乳自己不满1周岁婴儿</div></div>
  {/* data-final-knowledge="relative-age-14-16" data-final-knowledge="relative-age-16-18" data-final-knowledge="relative-age-70" */}
  {[['14—16周岁','原则不执行'],['16—18周岁初次','原则不执行'],['70周岁以上','原则不执行']].map((x,i)=><div key={x[0]} data-final-knowledge={['relative-age-14-16','relative-age-16-18','relative-age-70'][i]} style={{position:'absolute',left:90+i*560,top:360,width:500,height:210,background:C.paper,border:`6px solid ${[C.blue,C.gold,C.mint][i]}`,padding:25,textAlign:'center',...reveal(f,24+i*14)}}><div style={{fontSize:34,fontWeight:950,color:[C.blue,C.gold,C.mint][i]}}>{x[0]}</div><div style={{fontSize:27,marginTop:20}}>{x[1]}</div></div>)}
  <div data-final-knowledge="relative-exceptions" style={{position:'absolute',left:130,right:130,bottom:0,textAlign:'center',fontSize:23,lineHeight:1.5,fontWeight:850}}>相对不执行的例外：情节严重、影响恶劣；14—16周岁和70岁以上1年内2次以上；16—18周岁第二次即不适用。<br/><span style={{color:C.red}}>孕妇绝对不执行；老人小孩相对不执行。</span></div>
 </div></Shell>};

export const PenaltyVerdictArena=()=> <AbsoluteFill>
  <TimelineSequence name="01" start={SCENES['sanction-definition-filter'].start} duration={SCENES['sanction-definition-filter'].duration}><SanctionDefinitionFilterScene/></TimelineSequence>
  <TimelineSequence name="02" start={SCENES['five-sanction-machines'].start} duration={SCENES['five-sanction-machines'].duration}><FiveSanctionMachinesScene/></TimelineSequence>
  <TimelineSequence name="03" start={SCENES['power-routing-split'].start} duration={SCENES['power-routing-split'].duration}><PowerRoutingSplitScene/></TimelineSequence>
  <TimelineSequence name="04" start={SCENES['rulemaking-mold-ladder'].start} duration={SCENES['rulemaking-mold-ladder'].duration}><RulemakingMoldLadderScene/></TimelineSequence>
  <TimelineSequence name="05" start={SCENES['specification-benchmark-rail'].start} duration={SCENES['specification-benchmark-rail'].duration}><SpecificationBenchmarkRailScene/></TimelineSequence>
  <TimelineSequence name="06" start={SCENES['supplemental-setting-chamber'].start} duration={SCENES['supplemental-setting-chamber'].duration}><SupplementalSettingChamberScene/></TimelineSequence>
  <TimelineSequence name="07" start={SCENES['implementation-role-triangle'].start} duration={SCENES['implementation-role-triangle'].duration}><ImplementationRoleTriangleScene/></TimelineSequence>
  <TimelineSequence name="08" start={SCENES['jurisdiction-arena-map'].start} duration={SCENES['jurisdiction-arena-map'].duration}><JurisdictionArenaMapScene/></TimelineSequence>
  <TimelineSequence name="09" start={SCENES['ordinary-procedure-racetrack'].start} duration={SCENES['ordinary-procedure-racetrack'].duration}><OrdinaryProcedureRacetrackScene/></TimelineSequence>
  <TimelineSequence name="10" start={SCENES['legal-review-lock'].start} duration={SCENES['legal-review-lock'].duration}><LegalReviewLockScene/></TimelineSequence>
  <TimelineSequence name="11" start={SCENES['summary-threshold-scales'].start} duration={SCENES['summary-threshold-scales'].duration}><SummaryThresholdScalesScene/></TimelineSequence>
  <TimelineSequence name="12" start={SCENES['hearing-scope-amphitheater'].start} duration={SCENES['hearing-scope-amphitheater'].duration}><HearingScopeAmphitheaterScene/></TimelineSequence>
  <TimelineSequence name="13" start={SCENES['hearing-procedure-console'].start} duration={SCENES['hearing-procedure-console'].duration}><HearingProcedureConsoleScene/></TimelineSequence>
  <TimelineSequence name="14" start={SCENES['participation-rule-scoreboard'].start} duration={SCENES['participation-rule-scoreboard'].duration}><ParticipationRuleScoreboardScene/></TimelineSequence>
  <TimelineSequence name="15" start={SCENES['limitation-liability-dial'].start} duration={SCENES['limitation-liability-dial'].duration}><LimitationLiabilityDialScene/></TimelineSequence>
  <TimelineSequence name="16" start={SCENES['evidence-monitoring-wall'].start} duration={SCENES['evidence-monitoring-wall'].duration}><EvidenceMonitoringWallScene/></TimelineSequence>
  <TimelineSequence name="17" start={SCENES['public-security-sanction-vault'].start} duration={SCENES['public-security-sanction-vault'].duration}><PublicSecuritySanctionVaultScene/></TimelineSequence>
  <TimelineSequence name="18" start={SCENES['summons-interview-clocks'].start} duration={SCENES['summons-interview-clocks'].duration}><SummonsInterviewClocksScene/></TimelineSequence>
  <TimelineSequence name="19" start={SCENES['inspection-seizure-scene'].start} duration={SCENES['inspection-seizure-scene'].duration}><InspectionSeizureScene/></TimelineSequence>
  <TimelineSequence name="20" start={SCENES['single-officer-camera-wall'].start} duration={SCENES['single-officer-camera-wall'].duration}><SingleOfficerCameraWallScene/></TimelineSequence>
  <TimelineSequence name="21" start={SCENES['mediation-privacy-fork'].start} duration={SCENES['mediation-privacy-fork'].duration}><MediationPrivacyForkScene/></TimelineSequence>
  <TimelineSequence name="22" start={SCENES['fine-execution-settlement-chain'].start} duration={SCENES['fine-execution-settlement-chain'].duration}><FineExecutionSettlementChainScene/></TimelineSequence>
  <TimelineSequence name="23" start={SCENES['detention-suspension-airlock'].start} duration={SCENES['detention-suspension-airlock'].duration}><DetentionSuspensionAirlockScene/></TimelineSequence>
  <TimelineSequence name="24" start={SCENES['detention-nonexecution-screen'].start} duration={SCENES['detention-nonexecution-screen'].duration}><DetentionNonexecutionScreenScene/></TimelineSequence>
</AbsoluteFill>;
